// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0
//
// Package loadbalancer provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package loadbalancer

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for BackendserviceSpecHealthCheckHttpMethod.
const (
	BackendserviceSpecHealthCheckHttpMethodGET  BackendserviceSpecHealthCheckHttpMethod = "GET"
	BackendserviceSpecHealthCheckHttpMethodHEAD BackendserviceSpecHealthCheckHttpMethod = "HEAD"
)

// Defines values for BackendserviceSpecHealthCheckHttpsMethod.
const (
	BackendserviceSpecHealthCheckHttpsMethodGET  BackendserviceSpecHealthCheckHttpsMethod = "GET"
	BackendserviceSpecHealthCheckHttpsMethodHEAD BackendserviceSpecHealthCheckHttpsMethod = "HEAD"
)

// Defines values for BackendserviceStatusConditionsItemStatus.
const (
	BackendserviceStatusConditionsItemStatusFalse   BackendserviceStatusConditionsItemStatus = "False"
	BackendserviceStatusConditionsItemStatusTrue    BackendserviceStatusConditionsItemStatus = "True"
	BackendserviceStatusConditionsItemStatusUnknown BackendserviceStatusConditionsItemStatus = "Unknown"
)

// Defines values for L4routeStatusConditionsItemStatus.
const (
	L4routeStatusConditionsItemStatusFalse   L4routeStatusConditionsItemStatus = "False"
	L4routeStatusConditionsItemStatusTrue    L4routeStatusConditionsItemStatus = "True"
	L4routeStatusConditionsItemStatusUnknown L4routeStatusConditionsItemStatus = "Unknown"
)

// Defines values for LoadbalancerSpecListenersItemProtocol.
const (
	TCP LoadbalancerSpecListenersItemProtocol = "TCP"
)

// Defines values for LoadbalancerStatusConditionsItemStatus.
const (
	False   LoadbalancerStatusConditionsItemStatus = "False"
	True    LoadbalancerStatusConditionsItemStatus = "True"
	Unknown LoadbalancerStatusConditionsItemStatus = "Unknown"
)

// Backendpool defines model for Backendpool.
type Backendpool struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional project-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     BackendpoolSpec          `json:"spec"`
	Status   BackendpoolStatus        `json:"status"`
}

// BackendpoolList defines model for BackendpoolList.
type BackendpoolList struct {
	Items *[]Backendpool `json:"items,omitempty"`
}

// BackendpoolRequest defines model for BackendpoolRequest.
type BackendpoolRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`
	Spec     BackendpoolSpec         `json:"spec"`
}

// BackendpoolSpec defines model for BackendpoolSpec.
type BackendpoolSpec struct {
	// BackendRefs The set of backends (i.e. VMs) that should be pooled as a target for BackendServices.
	BackendRefs *[]string `json:"backendRefs,omitempty"`
}

// BackendpoolStatus defines model for BackendpoolStatus.
type BackendpoolStatus = map[string]interface{}

// Backendservice defines model for Backendservice.
type Backendservice struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional project-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     BackendserviceSpec       `json:"spec"`
	Status   BackendserviceStatus     `json:"status"`
}

// BackendserviceList defines model for BackendserviceList.
type BackendserviceList struct {
	Items *[]Backendservice `json:"items,omitempty"`
}

// BackendserviceRequest defines model for BackendserviceRequest.
type BackendserviceRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`
	Spec     BackendserviceSpec      `json:"spec"`
}

// BackendserviceSpec defines model for BackendserviceSpec.
type BackendserviceSpec struct {
	// BackendPoolRef The pool to handle this BackendService.
	BackendPoolRef *string `json:"backendPoolRef,omitempty"`

	// HealthCheck HealthCheck configures active health checking for this BackendService.
	HealthCheck *BackendserviceSpecHealthCheck `json:"healthCheck,omitempty"`

	// Port The listening port for this Backend Service.
	Port int32 `json:"port"`

	// ProxyProtocol Enables proxy protocol for connections to this Backend Service.
	ProxyProtocol *bool `json:"proxyProtocol,omitempty"`
}

// BackendserviceSpecHealthCheck HealthCheck configures active health checking for this BackendService.
type BackendserviceSpecHealthCheck struct {
	// HealthyThreshold HealthyThreshold is the number of consecutive successes before marking an endpoint healthy.
	HealthyThreshold *int32 `json:"healthyThreshold,omitempty"`

	// Http HTTP configures an HTTP health check.
	Http *struct {
		// ExpectedStatuses ExpectedStatuses is the list of HTTP response status codes considered healthy.
		ExpectedStatuses *[]int32 `json:"expectedStatuses,omitempty"`

		// Host Host is the Host header value.
		Host *string `json:"host,omitempty"`

		// Method Method is the HTTP method used for health checks.
		Method *BackendserviceSpecHealthCheckHttpMethod `json:"method,omitempty"`

		// Path Path is the absolute request path.
		Path string `json:"path"`
	} `json:"http,omitempty"`

	// Https HTTPS configures an HTTPS health check.
	Https *struct {
		// ExpectedStatuses ExpectedStatuses is the list of HTTP response status codes considered healthy.
		ExpectedStatuses *[]int32 `json:"expectedStatuses,omitempty"`

		// Host Host is the Host header value.
		Host *string `json:"host,omitempty"`

		// Method Method is the HTTP method used for health checks.
		Method *BackendserviceSpecHealthCheckHttpsMethod `json:"method,omitempty"`

		// Path Path is the absolute request path.
		Path string `json:"path"`

		// Tls TLS configures health-check-only TLS behavior.
		Tls *BackendserviceSpecHealthCheckTls `json:"tls,omitempty"`
	} `json:"https,omitempty"`

	// Interval Interval is the duration between health check attempts.
	Interval *string `json:"interval,omitempty"`

	// TargetPort TargetPort is the backend endpoint port to check. Defaults to BackendService.spec.port.
	TargetPort *int32 `json:"targetPort,omitempty"`

	// Tcp TCP configures a TCP health check.
	Tcp *struct {
		// Receive Receive is a text payload expected in the response.
		Receive *string `json:"receive,omitempty"`

		// Send Send is a text payload written after connecting.
		Send *string `json:"send,omitempty"`
	} `json:"tcp,omitempty"`

	// Timeout Timeout is the duration allowed for one health check attempt.
	Timeout *string `json:"timeout,omitempty"`

	// UnhealthyThreshold UnhealthyThreshold is the number of consecutive failures before marking an endpoint unhealthy.
	UnhealthyThreshold *int32 `json:"unhealthyThreshold,omitempty"`
}

// BackendserviceSpecHealthCheckHttpMethod Method is the HTTP method used for health checks.
type BackendserviceSpecHealthCheckHttpMethod string

// BackendserviceSpecHealthCheckHttpsMethod Method is the HTTP method used for health checks.
type BackendserviceSpecHealthCheckHttpsMethod string

// BackendserviceSpecHealthCheckTls TLS configures health-check-only TLS behavior.
type BackendserviceSpecHealthCheckTls struct {
	// InsecureSkipVerify InsecureSkipVerify disables certificate verification.
	InsecureSkipVerify *bool `json:"insecureSkipVerify,omitempty"`
}

// BackendserviceStatus defines model for BackendserviceStatus.
type BackendserviceStatus struct {
	// Addresses The list of backend addresses resolved for this service.
	Addresses *[]string `json:"addresses,omitempty"`

	// Backends The count of backend addresses resolved.
	Backends int `json:"backends"`

	// Conditions ConditionsSet is an abstraction over []metav1.Condition that handles the
	// removal of the previous occurrence of the conditionType when marking a condition.
	Conditions *[]BackendserviceStatusConditionsItem `json:"conditions,omitempty"`
}

// BackendserviceStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type BackendserviceStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status BackendserviceStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// BackendserviceStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type BackendserviceStatusConditionsItemStatus string

// BaseMetadataResponse Common metadata fields for all resource responses.
type BaseMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to determine when objects have changed. Any reconciliation, or system-driven status change, can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`
}

// Error Standard error response sent by all endpoints on failure.
type Error struct {
	// Debug Additional human-readable diagnostic information in English. This content is safe to surface to end users. MUST NOT be used for programmatic logic. The content may evolve at any time and is not stable.
	Debug *string `json:"debug,omitempty"`

	// Reason Stable, textual error code. This MUST be used by clients for programmatic handling. Examples include: FieldValueInvalid, Unauthorized, Forbidden.
	Reason string `json:"reason"`
}

// GlobalMetadataRequest Standard metadata for global resources.
type GlobalMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// L4route defines model for L4route.
type L4route struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional project-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     L4routeSpec              `json:"spec"`
	Status   L4routeStatus            `json:"status"`
}

// L4routeList defines model for L4routeList.
type L4routeList struct {
	Items *[]L4route `json:"items,omitempty"`
}

// L4routeRequest defines model for L4routeRequest.
type L4routeRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`
	Spec     L4routeSpec             `json:"spec"`
}

// L4routeSpec defines model for L4routeSpec.
type L4routeSpec struct {
	// DefaultBackendServiceRef BackendService for traffic.
	DefaultBackendServiceRef string `json:"defaultBackendServiceRef"`
}

// L4routeStatus defines model for L4routeStatus.
type L4routeStatus struct {
	// Conditions ConditionsSet is an abstraction over []metav1.Condition that handles the
	// removal of the previous occurrence of the conditionType when marking a condition.
	Conditions *[]L4routeStatusConditionsItem `json:"conditions,omitempty"`
}

// L4routeStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type L4routeStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status L4routeStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// L4routeStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type L4routeStatusConditionsItemStatus string

// Loadbalancer defines model for Loadbalancer.
type Loadbalancer struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional project-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     LoadbalancerSpec         `json:"spec"`
	Status   LoadbalancerStatus       `json:"status"`
}

// LoadbalancerList defines model for LoadbalancerList.
type LoadbalancerList struct {
	Items *[]Loadbalancer `json:"items,omitempty"`
}

// LoadbalancerRequest defines model for LoadbalancerRequest.
type LoadbalancerRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`
	Spec     LoadbalancerSpec        `json:"spec"`
}

// LoadbalancerSpec defines model for LoadbalancerSpec.
type LoadbalancerSpec struct {
	// Listeners The set of Listeners for this Load Balancer.
	Listeners *[]LoadbalancerSpecListenersItem `json:"listeners,omitempty"`

	// PublicIPRef The public IP for the Load Balancer.
	PublicIPRef string `json:"publicIPRef"`
}

// LoadbalancerSpecListenersItem defines model for LoadbalancerSpecListenersItem.
type LoadbalancerSpecListenersItem struct {
	// Name The name of the Listener. Optional. Must be unique per Load Balancer.
	Name *string `json:"name,omitempty"`

	// Port The listening port for this Listener.
	Port int32 `json:"port"`

	// Protocol Network protocol for this Listener. Allowed values: TCP.
	Protocol LoadbalancerSpecListenersItemProtocol `json:"protocol"`

	// RouteRefs The routes for this listener.
	RouteRefs *[]string `json:"routeRefs,omitempty"`
}

// LoadbalancerSpecListenersItemProtocol Network protocol for this Listener. Allowed values: TCP.
type LoadbalancerSpecListenersItemProtocol string

// LoadbalancerStatus defines model for LoadbalancerStatus.
type LoadbalancerStatus struct {
	// Conditions ConditionsSet is an abstraction over []metav1.Condition that handles the
	// removal of the previous occurrence of the conditionType when marking a condition.
	Conditions *[]LoadbalancerStatusConditionsItem `json:"conditions,omitempty"`

	// Networking The current status of the networking set up on the Load Balancer.
	Networking *LoadbalancerStatusNetworking `json:"networking,omitempty"`
}

// LoadbalancerStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type LoadbalancerStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status LoadbalancerStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// LoadbalancerStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type LoadbalancerStatusConditionsItemStatus string

// LoadbalancerStatusNetworking The current status of the networking set up on the Load Balancer.
type LoadbalancerStatusNetworking struct {
	// PublicIPv4Address The assigned public IPv4 address of the Load Balancer.
	PublicIPv4Address *string `json:"publicIPv4Address,omitempty"`
}

// RegionalMetadataRequest defines model for RegionalMetadataRequest.
type RegionalMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Project Project identifier
	Project *string `json:"project,omitempty"`

	// Region Region identifier
	Region *string `json:"region,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// RegionalMetadataResponse defines model for RegionalMetadataResponse.
type RegionalMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Project Project identifier
	Project *string `json:"project,omitempty"`

	// Region Region identifier
	Region *string `json:"region,omitempty"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to determine when objects have changed. Any reconciliation, or system-driven status change, can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// SystemLabels Map of string keys and string values owned and managed by evroc, and automatically set by the system. SystemLabels are read-only and can be referenced by label selectors.
	SystemLabels *SystemLabels `json:"systemLabels,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// SystemLabels Map of string keys and string values owned and managed by evroc, and automatically set by the system. SystemLabels are read-only and can be referenced by label selectors.
type SystemLabels map[string]string

// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
type UserLabels map[string]string

// ApiVersion Identifies the version of the API schema used for this resource.
// It should be the same than the version in the path, otherwise the request will be rejected.
type ApiVersion = string

// Kind Specifies the type of resource this object represents.
type Kind = string

// GetLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendPoolsParams defines parameters for GetLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendPools.
type GetLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendPoolsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendServicesParams defines parameters for GetLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendServices.
type GetLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendServicesParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameL4RoutesParams defines parameters for GetLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameL4Routes.
type GetLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameL4RoutesParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameLoadBalancersParams defines parameters for GetLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameLoadBalancers.
type GetLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameLoadBalancersParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// PostLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendPoolsJSONRequestBody defines body for PostLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendPools for application/json ContentType.
type PostLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendPoolsJSONRequestBody = BackendpoolRequest

// PatchLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendPoolsBackendPoolIDJSONRequestBody defines body for PatchLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendPoolsBackendPoolID for application/json ContentType.
type PatchLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendPoolsBackendPoolIDJSONRequestBody = BackendpoolRequest

// PostLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendServicesJSONRequestBody defines body for PostLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendServices for application/json ContentType.
type PostLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendServicesJSONRequestBody = BackendserviceRequest

// PatchLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendServicesBackendServiceIDJSONRequestBody defines body for PatchLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendServicesBackendServiceID for application/json ContentType.
type PatchLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameBackendServicesBackendServiceIDJSONRequestBody = BackendserviceRequest

// PostLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameL4RoutesJSONRequestBody defines body for PostLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameL4Routes for application/json ContentType.
type PostLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameL4RoutesJSONRequestBody = L4routeRequest

// PatchLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameL4RoutesL4RouteIDJSONRequestBody defines body for PatchLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameL4RoutesL4RouteID for application/json ContentType.
type PatchLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameL4RoutesL4RouteIDJSONRequestBody = L4routeRequest

// PostLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameLoadBalancersJSONRequestBody defines body for PostLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameLoadBalancers for application/json ContentType.
type PostLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameLoadBalancersJSONRequestBody = LoadbalancerRequest

// PatchLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameLoadBalancersLoadBalancerIDJSONRequestBody defines body for PatchLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameLoadBalancersLoadBalancerID for application/json ContentType.
type PatchLoadbalancerV1alpha1ProjectsProjectIDRegionsRegionNameLoadBalancersLoadBalancerIDJSONRequestBody = LoadbalancerRequest
