// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0
//
// Package quotas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package quotas

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// BaseMetadataResponse Common metadata fields for all resource responses.
type BaseMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to  determine when objects have changed. Any reconciliation, or system-driven status change,  can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`
}

// Error Standard error response sent by all endpoints on failure.
type Error struct {
	// Debug Additional human-readable diagnostic information in English. This content is safe to surface to end users. MUST NOT be used for programmatic logic. The content may evolve at any time and is not stable.
	Debug *string `json:"debug,omitempty"`

	// Reason Stable, textual error code. This MUST be used by clients for programmatic handling. Examples include: FieldValueInvalid, Unauthorized, Forbidden.
	Reason string `json:"reason"`
}

// GlobalMetadataRequest Standard metadata for global resources.
type GlobalMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// Orgquota defines model for Orgquota.
type Orgquota struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional organization-scoped resource
	Metadata RegionalOrgMetadataResponse `json:"metadata"`
	Spec     OrgquotaSpec                `json:"spec"`

	// Status OrgQuotaStatus defines the observed state of OrgQuota.
	Status OrgquotaStatus `json:"status"`
}

// OrgquotaSpec defines model for OrgquotaSpec.
type OrgquotaSpec struct {
	// Quotas Quotas defines the quotas (i.e. limits) that this Organization is allowed
	// to use per product.
	Quotas *OrgquotaSpecQuotas `json:"quotas,omitempty"`
}

// OrgquotaSpecQuotas Quotas defines the quotas (i.e. limits) that this Organization is allowed
// to use per product.
type OrgquotaSpecQuotas struct {
	// Compute Compute defines the quotas that this Organization is allowed
	// to use for compute resources.
	Compute *struct {
		// BlockStorage BlockStorage defines the disk storage quota that this Organization is allowed
		// to use, aggregated across all resource groups and VMs, with a unit, e.g. "600 GB".
		BlockStorage *string `json:"blockStorage,omitempty"`

		// Gpus GPUs defines the number of GPU instances that this Organization is allowed to use, aggregated
		// across all resource groups and VMs. There is a quota per GPU model.
		Gpus *OrgquotaSpecQuotasGpus `json:"gpus,omitempty"`

		// Memory Memory defines the memory quota that this Organization is allowed
		// to use, aggregated across all resource groups and VMs, with a unit, e.g. "600 GB".
		Memory *string `json:"memory,omitempty"`

		// VCPUs VCPUs defines the maximum number of vCPUs that this Organization is allowed
		// to use, aggregated across all resource groups and VMs.
		VCPUs *int64 `json:"vCPUs,omitempty"`
	} `json:"compute,omitempty"`

	// Networking Networking defines the quotas that this Organization is allowed
	// to use for networking resources.
	Networking *struct {
		// PublicIPs PublicIPs defines the maximum number of public IPs that this Organization is allowed
		// to use, aggregated across all resource groups.
		PublicIPs *int64 `json:"publicIPs,omitempty"`
	} `json:"networking,omitempty"`
}

// OrgquotaSpecQuotasGpus GPUs defines the number of GPU instances that this Organization is allowed to use, aggregated
// across all resource groups and VMs. There is a quota per GPU model.
type OrgquotaSpecQuotasGpus map[string]int64

// OrgquotaStatus OrgQuotaStatus defines the observed state of OrgQuota.
type OrgquotaStatus struct {
	// QuotaUsage QuotaUsage reports the current usage of quotas for this Organization.
	QuotaUsage *OrgquotaStatusQuotaUsage `json:"quotaUsage,omitempty"`
}

// OrgquotaStatusQuotaUsage QuotaUsage reports the current usage of quotas for this Organization.
type OrgquotaStatusQuotaUsage struct {
	// Compute Compute reports the current usage of compute resources.
	Compute *struct {
		// BlockStorage BlockStorage reports the current usage of block storage
		// in human readable format.
		BlockStorage *string `json:"blockStorage,omitempty"`

		// BlockStorageInMBs BlockStorage reports the current usage of block storage in MBs
		BlockStorageInMBs *int64 `json:"blockStorageInMBs,omitempty"`

		// Gpus GPUs reports the current usage of GPUs.
		Gpus *OrgquotaStatusQuotaUsageGpus `json:"gpus,omitempty"`

		// Memory Memory reports the current usage of memory in human readable format
		Memory *string `json:"memory,omitempty"`

		// MemoryInKiBs Memory reports the current usage of memory in KiBs
		MemoryInKiBs *int64 `json:"memoryInKiBs,omitempty"`

		// VCPUs VCPUs reports the current usage of vCPUs.
		VCPUs *int64 `json:"vCPUs,omitempty"`
	} `json:"compute,omitempty"`

	// Networking Networking reports the current usage of networking resources.
	Networking *struct {
		// PublicIPs PublicIPs reports the current usage of public IPs.
		PublicIPs *int64 `json:"publicIPs,omitempty"`
	} `json:"networking,omitempty"`
}

// OrgquotaStatusQuotaUsageGpus GPUs reports the current usage of GPUs.
type OrgquotaStatusQuotaUsageGpus map[string]int64

// Projectquota defines model for Projectquota.
type Projectquota struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional project-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     ProjectquotaSpec         `json:"spec"`

	// Status ProjectQuotaStatus defines the observed state of ProjectQuota.
	Status ProjectquotaStatus `json:"status"`
}

// ProjectquotaSpec defines model for ProjectquotaSpec.
type ProjectquotaSpec struct {
	// ObjectStorage ObjectStorage defines the quotas that this Project is allowed
	// to use for object storage resources.
	ObjectStorage *ProjectquotaSpecObjectStorage `json:"objectStorage,omitempty"`
}

// ProjectquotaSpecObjectStorage ObjectStorage defines the quotas that this Project is allowed
// to use for object storage resources.
type ProjectquotaSpecObjectStorage struct {
	// TotalSize TotalSize defines the maximum total size of object storage that this Project
	// is allowed to use, with a unit, e.g. "5TB". There is also a special
	// value of 'unlimited' that specifies that no limit is enforced.
	TotalSize *string `json:"totalSize,omitempty"`
}

// ProjectquotaStatus ProjectQuotaStatus defines the observed state of ProjectQuota.
type ProjectquotaStatus struct {
	// QuotaUsage QuotaUsage reports the current usage of quotas for this Project.
	QuotaUsage *ProjectquotaStatusQuotaUsage `json:"quotaUsage,omitempty"`
}

// ProjectquotaStatusQuotaUsage QuotaUsage reports the current usage of quotas for this Project.
type ProjectquotaStatusQuotaUsage struct {
	// ObjectStorage ObjectStorage reports the current usage of object storage resources.
	ObjectStorage *struct {
		// TotalSize TotalSize reports the current usage of object storage in human readable format.
		TotalSize *string `json:"totalSize,omitempty"`
	} `json:"objectStorage,omitempty"`
}

// RegionalMetadataRequest defines model for RegionalMetadataRequest.
type RegionalMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Project Project identifier
	Project *string `json:"project,omitempty"`

	// Region Region identifier
	Region *string `json:"region,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// RegionalMetadataResponse defines model for RegionalMetadataResponse.
type RegionalMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Project Project identifier
	Project *string `json:"project,omitempty"`

	// Region Region identifier
	Region *string `json:"region,omitempty"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to  determine when objects have changed. Any reconciliation, or system-driven status change,  can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// SystemLabels Map of string keys and string values owned and managed by evroc, and automatically set by the system. SystemLabels are read-only and can be referenced by label selectors.
	SystemLabels *SystemLabels `json:"systemLabels,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// RegionalOrgMetadataResponse defines model for RegionalOrgMetadataResponse.
type RegionalOrgMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Organization Organization associated with the resource.
	Organization *string `json:"organization,omitempty"`

	// Region Region identifier.
	Region *string `json:"region,omitempty"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to  determine when objects have changed. Any reconciliation, or system-driven status change,  can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// SystemLabels Map of string keys and string values owned and managed by evroc, and automatically set by the system. SystemLabels are read-only and can be referenced by label selectors.
	SystemLabels *SystemLabels `json:"systemLabels,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// SystemLabels Map of string keys and string values owned and managed by evroc, and automatically set by the system. SystemLabels are read-only and can be referenced by label selectors.
type SystemLabels map[string]string

// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
type UserLabels map[string]string

// ApiVersion Identifies the version of the API schema used for this resource.
// It should be the same than the version in the path, otherwise the request will be rejected.
type ApiVersion = string

// Kind Specifies the type of resource this object represents.
type Kind = string
