// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0
//
// Package iam provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package iam

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for PermissionSetSpecSubjectType.
const (
	User PermissionSetSpecSubjectType = "user"
)

// Defines values for PermissionSetStatusConditionsItemStatus.
const (
	PermissionSetStatusConditionsItemStatusFalse   PermissionSetStatusConditionsItemStatus = "False"
	PermissionSetStatusConditionsItemStatusTrue    PermissionSetStatusConditionsItemStatus = "True"
	PermissionSetStatusConditionsItemStatusUnknown PermissionSetStatusConditionsItemStatus = "Unknown"
)

// Defines values for ProjectStatusConditionsItemStatus.
const (
	ProjectStatusConditionsItemStatusFalse   ProjectStatusConditionsItemStatus = "False"
	ProjectStatusConditionsItemStatusTrue    ProjectStatusConditionsItemStatus = "True"
	ProjectStatusConditionsItemStatusUnknown ProjectStatusConditionsItemStatus = "Unknown"
)

// Defines values for RoleInfoScope.
const (
	RoleInfoScopeOrganization RoleInfoScope = "organization"
	RoleInfoScopeProject      RoleInfoScope = "project"
)

// Defines values for RolebindingStatusConditionsItemStatus.
const (
	RolebindingStatusConditionsItemStatusFalse   RolebindingStatusConditionsItemStatus = "False"
	RolebindingStatusConditionsItemStatusTrue    RolebindingStatusConditionsItemStatus = "True"
	RolebindingStatusConditionsItemStatusUnknown RolebindingStatusConditionsItemStatus = "Unknown"
)

// Defines values for ServiceaccountStatusConditionsItemStatus.
const (
	ServiceaccountStatusConditionsItemStatusFalse   ServiceaccountStatusConditionsItemStatus = "False"
	ServiceaccountStatusConditionsItemStatusTrue    ServiceaccountStatusConditionsItemStatus = "True"
	ServiceaccountStatusConditionsItemStatusUnknown ServiceaccountStatusConditionsItemStatus = "Unknown"
)

// Defines values for ServiceaccountcredentialSpecType.
const (
	Rs256Jwt ServiceaccountcredentialSpecType = "rs256-jwt"
)

// Defines values for ServiceaccountcredentialStatusConditionsItemStatus.
const (
	False   ServiceaccountcredentialStatusConditionsItemStatus = "False"
	True    ServiceaccountcredentialStatusConditionsItemStatus = "True"
	Unknown ServiceaccountcredentialStatusConditionsItemStatus = "Unknown"
)

// AssignRoleRequest Grants one role to one principal, optionally limited to specific resources.
type AssignRoleRequest struct {
	// Principal The identity to grant the role to, as a fully-qualified identifier:
	// /iam/users/{userID} or /iam/projects/{projectID}/serviceAccounts/{serviceAccountID}.
	Principal string `json:"principal"`

	// Resources Optional list of resources the role is limited to, using the same FQID and wildcard rules as a role binding's `roles[].resources`. Omit to grant the role on every applicable resource in scope.
	Resources *[]string `json:"resources,omitempty"`

	// Role The role to grant, as a role FQID.
	Role string `json:"role"`
}

// BaseMetadataResponse Common metadata fields for all resource responses.
type BaseMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to determine when objects have changed. Any reconciliation, or system-driven status change, can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`
}

// CheckAccessRequest The set of permissions to evaluate for a given principal.
type CheckAccessRequest struct {
	Checks []PermissionCheck `json:"checks"`

	// Principal The identity whose access is being inspected, as a fully-qualified identifier.
	Principal string `json:"principal"`
}

// CheckAccessResponse One verdict per requested check, in request order.
type CheckAccessResponse struct {
	Results *[]PermissionResult `json:"results,omitempty"`
}

// Error Standard error response sent by all endpoints on failure.
type Error struct {
	// Debug Additional human-readable diagnostic information in English. This content is safe to surface to end users. MUST NOT be used for programmatic logic. The content may evolve at any time and is not stable.
	Debug *string `json:"debug,omitempty"`

	// Reason Stable, textual error code. This MUST be used by clients for programmatic handling. Examples include: FieldValueInvalid, Unauthorized, Forbidden.
	Reason string `json:"reason"`
}

// GlobalMetadataRequest Standard metadata for global resources.
type GlobalMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalMetadataRequestPatch Standard metadata for global resources used for PATCH operations.
type GlobalMetadataRequestPatch struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id *string `json:"id,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalMetadataResponse defines model for GlobalMetadataResponse.
type GlobalMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to determine when objects have changed. Any reconciliation, or system-driven status change, can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalOrgMetadataRequest defines model for GlobalOrgMetadataRequest.
type GlobalOrgMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Organization Organization associated with the resource.
	Organization *string `json:"organization,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalOrgMetadataRequestPatch defines model for GlobalOrgMetadataRequestPatch.
type GlobalOrgMetadataRequestPatch struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id *string `json:"id,omitempty"`

	// Organization Organization associated with the resource.
	Organization *string `json:"organization,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalOrgMetadataResponse defines model for GlobalOrgMetadataResponse.
type GlobalOrgMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Organization Organization associated with the resource.
	Organization *string `json:"organization,omitempty"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to determine when objects have changed. Any reconciliation, or system-driven status change, can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalProjectMetadataRequest defines model for GlobalProjectMetadataRequest.
type GlobalProjectMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Project Project to which this resource belongs.
	Project *string `json:"project,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalProjectMetadataRequestPatch defines model for GlobalProjectMetadataRequestPatch.
type GlobalProjectMetadataRequestPatch struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id *string `json:"id,omitempty"`

	// Project Project to which this resource belongs.
	Project *string `json:"project,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalProjectMetadataResponse defines model for GlobalProjectMetadataResponse.
type GlobalProjectMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Project Project to which this resource belongs.
	Project *string `json:"project,omitempty"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to determine when objects have changed. Any reconciliation, or system-driven status change, can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// OrgListResponse defines model for OrgListResponse.
type OrgListResponse struct {
	Items *[]OrgResponse `json:"items,omitempty"`
}

// OrgPatchRequest Partial role binding used with JSON Merge Patch. Only the supplied fields are changed.
type OrgPatchRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion *ApiVersion `json:"apiVersion,omitempty"`

	// Kind Specifies the type of resource this object represents.
	Kind *Kind `json:"kind,omitempty"`

	// Metadata Standard metadata for global, organization-scoped resource  used for PATCH operations.
	Metadata *GlobalOrgMetadataRequestPatch `json:"metadata,omitempty"`

	// Spec Desired configuration of the role binding.
	Spec *RolebindingSpec `json:"spec,omitempty"`
}

// OrgRequest defines model for OrgRequest.
type OrgRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global, organization-scoped resource
	Metadata GlobalOrgMetadataRequest `json:"metadata"`

	// Spec Desired configuration of the role binding.
	Spec RolebindingSpec `json:"spec"`
}

// OrgResponse defines model for OrgResponse.
type OrgResponse struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global organization-scoped resources.
	Metadata GlobalOrgMetadataResponse `json:"metadata"`

	// Spec Desired configuration of the role binding.
	Spec RolebindingSpec `json:"spec"`

	// Status Observed state of the role binding, set by the system.
	Status RolebindingStatus `json:"status"`
}

// Organization defines model for Organization.
type Organization struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind     Kind `json:"kind"`
	Metadata struct {
		// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
		CreationTimestamp time.Time `json:"creationTimestamp"`

		// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
		Generation int64 `json:"generation"`

		// Id Unique identifier for the organization. Immutable.
		Id *openapi_types.UUID `json:"id,omitempty"`

		// ResourceVersion String that identifies the internal version of this object that can be used by clients to determine when objects have changed. Any reconciliation, or system-driven status change, can change the resourceVersion, not only a change of spec.
		ResourceVersion *string `json:"resourceVersion,omitempty"`

		// Uid System-assigned unique identifier for the resource. Immutable.
		Uid openapi_types.UUID `json:"uid"`
	} `json:"metadata"`
	Spec OrganizationSpec `json:"spec"`

	// Status OrgQuotaStatus defines the observed state of OrgQuota.
	Status OrganizationStatus `json:"status"`
}

// OrganizationList defines model for OrganizationList.
type OrganizationList struct {
	Items *[]Organization `json:"items,omitempty"`
}

// OrganizationPatchRequest defines model for OrganizationPatchRequest.
type OrganizationPatchRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion *ApiVersion `json:"apiVersion,omitempty"`

	// Kind Specifies the type of resource this object represents.
	Kind     *Kind      `json:"kind,omitempty"`
	Metadata *Metadata  `json:"metadata,omitempty"`
	Spec     *PatchSpec `json:"spec,omitempty"`
}

// OrganizationSpec defines model for OrganizationSpec.
type OrganizationSpec struct {
	// Name Human-friendly name for the resource. Mutable. Not required to be unique.
	Name *string `json:"name,omitempty"`

	// Quotas Quotas defines the quotas (i.e. limits) that this Organization is allowed
	// to use per product.
	Quotas *OrganizationSpecQuotas `json:"quotas,omitempty"`
}

// OrganizationSpecQuotas Quotas defines the quotas (i.e. limits) that this Organization is allowed
// to use per product.
type OrganizationSpecQuotas struct {
	// Compute Compute defines the quotas that this Organization is allowed
	// to use for compute resources.
	Compute *struct {
		// BlockStorage BlockStorage defines the disk storage quota that this Organization is allowed
		// to use, aggregated across all resource groups and VMs, with a unit, e.g. "600 GB".
		BlockStorage *string `json:"blockStorage,omitempty"`

		// Gpus GPUs defines the number of GPU instances that this Organization is allowed to use, aggregated
		// across all resource groups and VMs. There is a quota per GPU model.
		Gpus *OrganizationSpecQuotasGpus `json:"gpus,omitempty"`

		// Memory Memory defines the memory quota that this Organization is allowed
		// to use, aggregated across all resource groups and VMs, with a unit, e.g. "600 GB".
		Memory *string `json:"memory,omitempty"`

		// VCPUs VCPUs defines the maximum number of vCPUs that this Organization is allowed
		// to use, aggregated across all resource groups and VMs.
		VCPUs *int64 `json:"vCPUs,omitempty"`
	} `json:"compute,omitempty"`

	// Networking Networking defines the quotas that this Organization is allowed
	// to use for networking resources.
	Networking *struct {
		// PublicIPs PublicIPs defines the maximum number of public IPs that this Organization is allowed
		// to use, aggregated across all resource groups.
		PublicIPs *int64 `json:"publicIPs,omitempty"`
	} `json:"networking,omitempty"`

	// ObjectStorage ObjectStorage defines the quotas that this Organization is allowed
	// to use for the Object Storage product.
	ObjectStorage *struct {
		// TotalSize TotalSize defines the maximum storage capacity that this Organization
		// may use, aggregated across all resource groups and buckets. It is defined
		// with a value and a unit of KB, MB, GB, or TB. There is also a special
		// value of 'unlimited' that specifies that no limit is enforced.
		TotalSize *string `json:"totalSize,omitempty"`
	} `json:"objectStorage,omitempty"`
}

// OrganizationSpecQuotasGpus GPUs defines the number of GPU instances that this Organization is allowed to use, aggregated
// across all resource groups and VMs. There is a quota per GPU model.
type OrganizationSpecQuotasGpus map[string]int64

// OrganizationStatus OrgQuotaStatus defines the observed state of OrgQuota.
type OrganizationStatus struct {
	// QuotaUsage QuotaUsage reports the current usage of quotas for this Organization.
	QuotaUsage *OrganizationStatusQuotaUsage `json:"quotaUsage,omitempty"`
}

// OrganizationStatusQuotaUsage QuotaUsage reports the current usage of quotas for this Organization.
type OrganizationStatusQuotaUsage struct {
	// Compute Compute reports the current usage of compute resources.
	Compute *struct {
		// BlockStorage BlockStorage reports the current usage of block storage
		// in human readable format.
		BlockStorage *string `json:"blockStorage,omitempty"`

		// BlockStorageInMBs BlockStorage reports the current usage of block storage in MBs
		BlockStorageInMBs *int64 `json:"blockStorageInMBs,omitempty"`

		// Gpus GPUs reports the current usage of GPUs.
		Gpus *OrganizationStatusQuotaUsageGpus `json:"gpus,omitempty"`

		// Memory Memory reports the current usage of memory in human readable format
		Memory *string `json:"memory,omitempty"`

		// MemoryInKiBs Memory reports the current usage of memory in KiBs
		MemoryInKiBs *int64 `json:"memoryInKiBs,omitempty"`

		// VCPUs VCPUs reports the current usage of vCPUs.
		VCPUs *int64 `json:"vCPUs,omitempty"`
	} `json:"compute,omitempty"`

	// Networking Networking reports the current usage of networking resources.
	Networking *struct {
		// PublicIPs PublicIPs reports the current usage of public IPs.
		PublicIPs *int64 `json:"publicIPs,omitempty"`
	} `json:"networking,omitempty"`
}

// OrganizationStatusQuotaUsageGpus GPUs reports the current usage of GPUs.
type OrganizationStatusQuotaUsageGpus map[string]int64

// PermissionCheck A single permission to evaluate against a resource.
type PermissionCheck struct {
	// Permission The permission to check, in `service.resource.action` form.
	Permission string `json:"permission"`

	// Resource The resource FQID to check the permission on. To check a scope-wide permission, pass the scope's own FQID (e.g. `/iam/projects/{projectID}`). Every resource in a single request must belong to the same project or organization.
	Resource string `json:"resource"`
}

// PermissionResult The outcome of one permission check.
type PermissionResult struct {
	// Allowed Whether the permission is granted on the resource.
	Allowed bool `json:"allowed"`

	// Permission The checked permission, echoed from the request.
	Permission string `json:"permission"`

	// Resource The checked resource FQID, echoed from the request.
	Resource string `json:"resource"`
}

// PermissionSet defines model for PermissionSet.
type PermissionSet struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global project-scoped resources.
	Metadata GlobalProjectMetadataResponse `json:"metadata"`
	Spec     PermissionSetSpec             `json:"spec"`

	// Status PermissionSetStatus defines the observed state of permission sets.
	Status PermissionSetStatus `json:"status"`
}

// PermissionSetList defines model for PermissionSetList.
type PermissionSetList struct {
	Items *[]PermissionSet `json:"items,omitempty"`
}

// PermissionSetPatchRequest defines model for PermissionSetPatchRequest.
type PermissionSetPatchRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion *ApiVersion `json:"apiVersion,omitempty"`

	// Kind Specifies the type of resource this object represents.
	Kind *Kind `json:"kind,omitempty"`

	// Metadata Standard metadata for global, project-scoped resource  used for PATCH operations.
	Metadata *GlobalProjectMetadataRequestPatch `json:"metadata,omitempty"`
	Spec     *PatchSpec                         `json:"spec,omitempty"`
}

// PermissionSetRequest defines model for PermissionSetRequest.
type PermissionSetRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global, project-scoped resource
	Metadata GlobalProjectMetadataRequest `json:"metadata"`
	Spec     PermissionSetSpec            `json:"spec"`
}

// PermissionSetSpec defines model for PermissionSetSpec.
type PermissionSetSpec struct {
	Admin   bool                     `json:"admin"`
	Subject PermissionSetSpecSubject `json:"subject"`
}

// PermissionSetSpecSubject defines model for PermissionSetSpecSubject.
type PermissionSetSpecSubject struct {
	Type PermissionSetSpecSubjectType `json:"type"`
	User struct {
		Email string `json:"email"`
	} `json:"user"`
}

// PermissionSetSpecSubjectType defines model for PermissionSetSpecSubject.Type.
type PermissionSetSpecSubjectType string

// PermissionSetStatus PermissionSetStatus defines the observed state of permission sets.
type PermissionSetStatus struct {
	// Conditions Conditions represents the state of the PermissionSet over time.
	Conditions *[]PermissionSetStatusConditionsItem `json:"conditions,omitempty"`
}

// PermissionSetStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type PermissionSetStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status PermissionSetStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// PermissionSetStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type PermissionSetStatusConditionsItemStatus string

// Project defines model for Project.
type Project struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global resources.
	Metadata GlobalMetadataResponse `json:"metadata"`

	// Spec ProjectSpec defines the desired state of project.
	Spec ProjectSpec `json:"spec"`

	// Status ProjectStatus defines the observed state of project.
	Status ProjectStatus `json:"status"`
}

// ProjectList defines model for ProjectList.
type ProjectList struct {
	Items *[]Project `json:"items,omitempty"`
}

// ProjectPatchRequest defines model for ProjectPatchRequest.
type ProjectPatchRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion *ApiVersion `json:"apiVersion,omitempty"`

	// Kind Specifies the type of resource this object represents.
	Kind *Kind `json:"kind,omitempty"`

	// Metadata Standard metadata for global resources used for PATCH operations.
	Metadata *GlobalMetadataRequestPatch `json:"metadata,omitempty"`
	Spec     *PatchSpec                  `json:"spec,omitempty"`
}

// ProjectRequest defines model for ProjectRequest.
type ProjectRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global resources.
	Metadata GlobalMetadataRequest `json:"metadata"`

	// Spec ProjectSpec defines the desired state of project.
	Spec ProjectSpec `json:"spec"`
}

// ProjectSpec ProjectSpec defines the desired state of project.
type ProjectSpec struct {
	// Name Human-friendly name for the resource. Mutable. Not required to be unique.
	Name *string `json:"name,omitempty"`

	// Organization Organization is the id of the Organization resource this project belongs to.
	// This field is required and immutable after creation.
	Organization string `json:"organization"`
}

// ProjectStatus ProjectStatus defines the observed state of project.
type ProjectStatus struct {
	// Conditions Conditions represents the state of the Project over time.
	// Each condition follows the Kubernetes API conventions for a condition:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
	// Conditions ConditionsSet `json:"conditions,omitempty"`
	Conditions *[]ProjectStatusConditionsItem `json:"conditions,omitempty"`
}

// ProjectStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type ProjectStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status ProjectStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// ProjectStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type ProjectStatusConditionsItemStatus string

// RevokeRequest defines model for RevokeRequest.
type RevokeRequest struct {
	// Reason Reason is the reason for revoking the credential.
	Reason string `json:"reason"`
}

// RevokeRoleRequest Removes one role from one principal in the scope.
type RevokeRoleRequest struct {
	// Principal The identity to remove the role from, as a fully-qualified identifier.
	Principal string `json:"principal"`

	// Role The role to remove, as a role FQID.
	Role string `json:"role"`
}

// RoleEntry A granted role and the resources it applies to.
type RoleEntry struct {
	// Name The role to grant, as a role FQID. Use `GET /iam/v1beta1/roles` to list the available roles and the permissions each one grants.
	Name string `json:"name"`

	// Resources Optional list of resources the role is limited to. Omit to grant the role on
	// every applicable resource in the binding scope.
	// Each entry is a resource FQID and may use `*` wildcards. A `*` may stand for
	// any single path segment except the service group (e.g. `compute`) and the
	// scope id (the project or organization id) — those must always be literal.
	// Examples:
	//   - /compute/projects/my-project/regions/se-sto/virtualMachines/my-vm   (one resource)
	//   - /compute/projects/my-project/regions/se-sto/virtualMachines/*       (all VMs in a region)
	//   - /compute/projects/my-project/regions/*/virtualMachines/*            (all VMs in any region)
	Resources *[]string `json:"resources,omitempty"`
}

// RoleInfo A predefined role and the permissions it grants.
type RoleInfo struct {
	// Description Human-readable summary of what the role is for.
	Description *string `json:"description,omitempty"`

	// Id The role FQID.
	Id string `json:"id"`

	// Permissions The permissions the role grants, in `service.resource.action` form.
	Permissions []string `json:"permissions"`

	// Scope The scope at which the role can be granted.
	Scope RoleInfoScope `json:"scope"`
}

// RoleInfoScope The scope at which the role can be granted.
type RoleInfoScope string

// RoleListResponse The full catalog of predefined roles.
type RoleListResponse struct {
	Items *[]RoleInfo `json:"items,omitempty"`
}

// Rolebinding defines model for Rolebinding.
type Rolebinding struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global project-scoped resources.
	Metadata GlobalProjectMetadataResponse `json:"metadata"`

	// Spec Desired configuration of the role binding.
	Spec RolebindingSpec `json:"spec"`

	// Status Observed state of the role binding, set by the system.
	Status RolebindingStatus `json:"status"`
}

// RolebindingList defines model for RolebindingList.
type RolebindingList struct {
	Items *[]Rolebinding `json:"items,omitempty"`
}

// RolebindingPatchRequest Partial role binding used with JSON Merge Patch. Only the supplied fields are changed.
type RolebindingPatchRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion *ApiVersion `json:"apiVersion,omitempty"`

	// Kind Specifies the type of resource this object represents.
	Kind *Kind `json:"kind,omitempty"`

	// Metadata Standard metadata for global, project-scoped resource  used for PATCH operations.
	Metadata *GlobalProjectMetadataRequestPatch `json:"metadata,omitempty"`

	// Spec Desired configuration of the role binding.
	Spec *RolebindingSpec `json:"spec,omitempty"`
}

// RolebindingRequest defines model for RolebindingRequest.
type RolebindingRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global, project-scoped resource
	Metadata GlobalProjectMetadataRequest `json:"metadata"`

	// Spec Desired configuration of the role binding.
	Spec RolebindingSpec `json:"spec"`
}

// RolebindingSpec Desired configuration of the role binding.
type RolebindingSpec struct {
	// Name Optional human-friendly display name for the binding. It can be changed at any time and does not need to be unique.
	Name *string `json:"name,omitempty"`

	// Principal The identity this binding grants roles to, as a fully-qualified identifier.
	// One of:
	//   - a user:            /iam/users/{userID}
	//   - a service account: /iam/projects/{projectID}/serviceAccounts/{serviceAccountID}
	// This field cannot be changed after the binding is created.
	Principal string `json:"principal"`

	// Roles The roles granted to the principal in this scope. At least one entry is required. Roles are additive: the principal receives the union of the permissions of every listed role. Each role may optionally be limited to specific resources.
	Roles []RoleEntry `json:"roles"`
}

// RolebindingStatus Observed state of the role binding, set by the system.
type RolebindingStatus struct {
	// Conditions The state of the role binding over time.
	Conditions *[]RolebindingStatusConditionsItem `json:"conditions,omitempty"`
}

// RolebindingStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type RolebindingStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status RolebindingStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// RolebindingStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type RolebindingStatusConditionsItemStatus string

// Serviceaccount defines model for Serviceaccount.
type Serviceaccount struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global project-scoped resources.
	Metadata GlobalProjectMetadataResponse `json:"metadata"`
	Spec     ServiceaccountSpec            `json:"spec"`

	// Status ServiceAccountStatus defines the observed state of ServiceAccount.
	Status ServiceaccountStatus `json:"status"`
}

// ServiceaccountList defines model for ServiceaccountList.
type ServiceaccountList struct {
	Items *[]Serviceaccount `json:"items,omitempty"`
}

// ServiceaccountPatchRequest defines model for ServiceaccountPatchRequest.
type ServiceaccountPatchRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion *ApiVersion `json:"apiVersion,omitempty"`

	// Kind Specifies the type of resource this object represents.
	Kind *Kind `json:"kind,omitempty"`

	// Metadata Standard metadata for global, project-scoped resource  used for PATCH operations.
	Metadata *GlobalProjectMetadataRequestPatch `json:"metadata,omitempty"`
	Spec     *PatchSpec                         `json:"spec,omitempty"`
}

// ServiceaccountRequest defines model for ServiceaccountRequest.
type ServiceaccountRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global, project-scoped resource
	Metadata GlobalProjectMetadataRequest `json:"metadata"`
	Spec     ServiceaccountSpec           `json:"spec"`
}

// ServiceaccountSpec defines model for ServiceaccountSpec.
type ServiceaccountSpec struct {
	// Description Description is a human-readable description of the service account.
	Description *string `json:"description,omitempty"`

	// Enabled Enabled indicates whether the service account is enabled. Disabled service accounts cannot be used for authentication.
	Enabled *bool `json:"enabled,omitempty"`
}

// ServiceaccountStatus ServiceAccountStatus defines the observed state of ServiceAccount.
type ServiceaccountStatus struct {
	// Conditions Conditions represents the state of the ServiceAccount over time.
	Conditions *[]ServiceaccountStatusConditionsItem `json:"conditions,omitempty"`

	// LastRevocationTime LastRevocationTime is the timestamp of the most recent credential revocation.
	LastRevocationTime *time.Time `json:"lastRevocationTime,omitempty"`

	// OauthClientId OAuthClientID is the identifier to be used for login in OAuth2/OIDC.
	OauthClientId *string `json:"oauthClientId,omitempty"`
}

// ServiceaccountStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type ServiceaccountStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status ServiceaccountStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// ServiceaccountStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type ServiceaccountStatusConditionsItemStatus string

// Serviceaccountcredential Response schema for a ServiceAccountCredential. Note: The privateKeyJwk field in status is a base64-encoded JSON string only populated in the CreateCredential API response.
type Serviceaccountcredential struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global project-scoped resources.
	Metadata GlobalProjectMetadataResponse `json:"metadata"`
	Spec     ServiceaccountcredentialSpec  `json:"spec"`

	// Status ServiceAccountCredentialStatus defines the observed state of ServiceAccountCredential.
	Status ServiceaccountcredentialStatus `json:"status"`
}

// ServiceaccountcredentialList defines model for ServiceaccountcredentialList.
type ServiceaccountcredentialList struct {
	Items *[]Serviceaccountcredential `json:"items,omitempty"`
}

// ServiceaccountcredentialRequest defines model for ServiceaccountcredentialRequest.
type ServiceaccountcredentialRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global, project-scoped resource
	Metadata GlobalProjectMetadataRequest `json:"metadata"`
	Spec     ServiceaccountcredentialSpec `json:"spec"`
}

// ServiceaccountcredentialSpec defines model for ServiceaccountcredentialSpec.
type ServiceaccountcredentialSpec struct {
	// AccountRef AccountRef is the reference to the parent ServiceAccount.
	AccountRef ServiceaccountcredentialSpecAccountRef `json:"accountRef"`

	// Description Description is a human-readable description of the credential.
	Description *string `json:"description,omitempty"`

	// ExpiresAt ExpiresAt is the timestamp when the credential expires.
	ExpiresAt time.Time `json:"expiresAt"`

	// RevocationRequest RevocationRequest is used to request revocation of this credential.
	RevocationRequest *ServiceaccountcredentialSpecRevocationRequest `json:"revocationRequest,omitempty"`

	// Rs256Jwt RS256Jwt contains the RSA key pair credential details. This field is required when type is "rs256-jwt".
	Rs256Jwt *ServiceaccountcredentialSpecRs256Jwt `json:"rs256Jwt,omitempty"`

	// Type Type is the type of credential.
	Type ServiceaccountcredentialSpecType `json:"type"`
}

// ServiceaccountcredentialSpecType Type is the type of credential.
type ServiceaccountcredentialSpecType string

// ServiceaccountcredentialSpecAccountRef AccountRef is the reference to the parent ServiceAccount.
type ServiceaccountcredentialSpecAccountRef struct {
	// Fqid FQID is the fully qualified identifier of the ServiceAccount. Example: /iam/projects/abcd/serviceAccounts/sa-cicd-123
	Fqid string `json:"fqid"`
}

// ServiceaccountcredentialSpecRevocationRequest RevocationRequest is used to request revocation of this credential.
type ServiceaccountcredentialSpecRevocationRequest struct {
	// Reason Reason is the reason for the revocation request.
	Reason *string `json:"reason,omitempty"`

	// Requested Requested indicates whether revocation has been requested.
	Requested bool `json:"requested"`
}

// ServiceaccountcredentialSpecRs256Jwt RS256Jwt contains the RSA key pair credential details. This field is required when type is "rs256-jwt".
type ServiceaccountcredentialSpecRs256Jwt struct {
	// AccessTokenLifetime AccessTokenLifetime is the lifetime of access tokens issued for this credential, in seconds.
	AccessTokenLifetime *int `json:"accessTokenLifetime,omitempty"`
}

// ServiceaccountcredentialStatus ServiceAccountCredentialStatus defines the observed state of ServiceAccountCredential.
type ServiceaccountcredentialStatus struct {
	// Conditions Conditions represents the state of the ServiceAccountCredential over time. Each condition follows the Kubernetes API conventions for a condition.
	Conditions *[]ServiceaccountcredentialStatusConditionsItem `json:"conditions,omitempty"`

	// PrivateKeyJwk PrivateKeyJWK contains the private key components as a base64-encoded JSON string. This field is only populated in the CreateCredential API response and is not stored.
	PrivateKeyJwk *string `json:"privateKeyJwk,omitempty"`

	// RevokedAt RevokedAt is the timestamp when the credential has been revoked.
	RevokedAt *time.Time `json:"revokedAt,omitempty"`
}

// ServiceaccountcredentialStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type ServiceaccountcredentialStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status ServiceaccountcredentialStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// ServiceaccountcredentialStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type ServiceaccountcredentialStatusConditionsItemStatus string

// TestPermissionsRequest The set of permissions to evaluate for the calling identity.
type TestPermissionsRequest struct {
	Checks []PermissionCheck `json:"checks"`
}

// TestPermissionsResponse One result per requested check, in request order.
type TestPermissionsResponse struct {
	Results *[]PermissionResult `json:"results,omitempty"`
}

// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
type UserLabels map[string]string

// ApiVersion Identifies the version of the API schema used for this resource.
// It should be the same than the version in the path, otherwise the request will be rejected.
type ApiVersion = string

// Kind Specifies the type of resource this object represents.
type Kind = string

// Metadata defines model for metadata.
type Metadata struct {
	// Id Unique identifier for the organization. Immutable.
	Id *openapi_types.UUID `json:"id,omitempty"`
}

// PatchSpec defines model for patchSpec.
type PatchSpec struct {
	// Description Description is a human-readable description of the service account.
	Description *string `json:"description,omitempty"`

	// Enabled Enabled indicates whether the service account is enabled. Disabled service accounts cannot be used for authentication.
	Enabled *bool `json:"enabled,omitempty"`
}

// GetIamV1beta1OrganizationsOrganizationIDRoleBindingsParams defines parameters for GetIamV1beta1OrganizationsOrganizationIDRoleBindings.
type GetIamV1beta1OrganizationsOrganizationIDRoleBindingsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetIamV1beta1ProjectsProjectIDPermissionSetsParams defines parameters for GetIamV1beta1ProjectsProjectIDPermissionSets.
type GetIamV1beta1ProjectsProjectIDPermissionSetsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetIamV1beta1ProjectsProjectIDRoleBindingsParams defines parameters for GetIamV1beta1ProjectsProjectIDRoleBindings.
type GetIamV1beta1ProjectsProjectIDRoleBindingsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetIamV1beta1ProjectsProjectIDServiceAccountsParams defines parameters for GetIamV1beta1ProjectsProjectIDServiceAccounts.
type GetIamV1beta1ProjectsProjectIDServiceAccountsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentialsParams defines parameters for GetIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentials.
type GetIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentialsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// PostIamV1beta1CheckAccessJSONRequestBody defines body for PostIamV1beta1CheckAccess for application/json ContentType.
type PostIamV1beta1CheckAccessJSONRequestBody = CheckAccessRequest

// PatchIamV1beta1OrganizationsOrganizationIDJSONRequestBody defines body for PatchIamV1beta1OrganizationsOrganizationID for application/json ContentType.
type PatchIamV1beta1OrganizationsOrganizationIDJSONRequestBody = OrganizationPatchRequest

// PostIamV1beta1OrganizationsOrganizationIDRoleBindingsJSONRequestBody defines body for PostIamV1beta1OrganizationsOrganizationIDRoleBindings for application/json ContentType.
type PostIamV1beta1OrganizationsOrganizationIDRoleBindingsJSONRequestBody = OrgRequest

// PostIamV1beta1OrganizationsOrganizationIDRoleBindingsAssignJSONRequestBody defines body for PostIamV1beta1OrganizationsOrganizationIDRoleBindingsAssign for application/json ContentType.
type PostIamV1beta1OrganizationsOrganizationIDRoleBindingsAssignJSONRequestBody = AssignRoleRequest

// PostIamV1beta1OrganizationsOrganizationIDRoleBindingsRevokeJSONRequestBody defines body for PostIamV1beta1OrganizationsOrganizationIDRoleBindingsRevoke for application/json ContentType.
type PostIamV1beta1OrganizationsOrganizationIDRoleBindingsRevokeJSONRequestBody = RevokeRoleRequest

// PatchIamV1beta1OrganizationsOrganizationIDRoleBindingsRoleBindingIDJSONRequestBody defines body for PatchIamV1beta1OrganizationsOrganizationIDRoleBindingsRoleBindingID for application/json ContentType.
type PatchIamV1beta1OrganizationsOrganizationIDRoleBindingsRoleBindingIDJSONRequestBody = OrgPatchRequest

// PostIamV1beta1ProjectsJSONRequestBody defines body for PostIamV1beta1Projects for application/json ContentType.
type PostIamV1beta1ProjectsJSONRequestBody = ProjectRequest

// PatchIamV1beta1ProjectsProjectIDJSONRequestBody defines body for PatchIamV1beta1ProjectsProjectID for application/json ContentType.
type PatchIamV1beta1ProjectsProjectIDJSONRequestBody = ProjectPatchRequest

// PostIamV1beta1ProjectsProjectIDPermissionSetsJSONRequestBody defines body for PostIamV1beta1ProjectsProjectIDPermissionSets for application/json ContentType.
type PostIamV1beta1ProjectsProjectIDPermissionSetsJSONRequestBody = PermissionSetRequest

// PatchIamV1beta1ProjectsProjectIDPermissionSetsPermissionSetIDJSONRequestBody defines body for PatchIamV1beta1ProjectsProjectIDPermissionSetsPermissionSetID for application/json ContentType.
type PatchIamV1beta1ProjectsProjectIDPermissionSetsPermissionSetIDJSONRequestBody = PermissionSetPatchRequest

// PostIamV1beta1ProjectsProjectIDRoleBindingsJSONRequestBody defines body for PostIamV1beta1ProjectsProjectIDRoleBindings for application/json ContentType.
type PostIamV1beta1ProjectsProjectIDRoleBindingsJSONRequestBody = RolebindingRequest

// PostIamV1beta1ProjectsProjectIDRoleBindingsAssignJSONRequestBody defines body for PostIamV1beta1ProjectsProjectIDRoleBindingsAssign for application/json ContentType.
type PostIamV1beta1ProjectsProjectIDRoleBindingsAssignJSONRequestBody = AssignRoleRequest

// PostIamV1beta1ProjectsProjectIDRoleBindingsRevokeJSONRequestBody defines body for PostIamV1beta1ProjectsProjectIDRoleBindingsRevoke for application/json ContentType.
type PostIamV1beta1ProjectsProjectIDRoleBindingsRevokeJSONRequestBody = RevokeRoleRequest

// PatchIamV1beta1ProjectsProjectIDRoleBindingsRoleBindingIDJSONRequestBody defines body for PatchIamV1beta1ProjectsProjectIDRoleBindingsRoleBindingID for application/json ContentType.
type PatchIamV1beta1ProjectsProjectIDRoleBindingsRoleBindingIDJSONRequestBody = RolebindingPatchRequest

// PostIamV1beta1ProjectsProjectIDServiceAccountsJSONRequestBody defines body for PostIamV1beta1ProjectsProjectIDServiceAccounts for application/json ContentType.
type PostIamV1beta1ProjectsProjectIDServiceAccountsJSONRequestBody = ServiceaccountRequest

// PatchIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDJSONRequestBody defines body for PatchIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountID for application/json ContentType.
type PatchIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDJSONRequestBody = ServiceaccountPatchRequest

// PostIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentialsJSONRequestBody defines body for PostIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentials for application/json ContentType.
type PostIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentialsJSONRequestBody = ServiceaccountcredentialRequest

// PostIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentialsCredentialIDRevokeJSONRequestBody defines body for PostIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentialsCredentialIDRevoke for application/json ContentType.
type PostIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentialsCredentialIDRevokeJSONRequestBody = RevokeRequest

// PostIamV1beta1TestPermissionsJSONRequestBody defines body for PostIamV1beta1TestPermissions for application/json ContentType.
type PostIamV1beta1TestPermissionsJSONRequestBody = TestPermissionsRequest
