// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0
//
// Package iam provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package iam

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for PermissionSetSpecSubjectType.
const (
	User PermissionSetSpecSubjectType = "user"
)

// Defines values for PermissionSetStatusConditionsItemStatus.
const (
	PermissionSetStatusConditionsItemStatusFalse   PermissionSetStatusConditionsItemStatus = "False"
	PermissionSetStatusConditionsItemStatusTrue    PermissionSetStatusConditionsItemStatus = "True"
	PermissionSetStatusConditionsItemStatusUnknown PermissionSetStatusConditionsItemStatus = "Unknown"
)

// Defines values for ProjectStatusConditionsItemStatus.
const (
	ProjectStatusConditionsItemStatusFalse   ProjectStatusConditionsItemStatus = "False"
	ProjectStatusConditionsItemStatusTrue    ProjectStatusConditionsItemStatus = "True"
	ProjectStatusConditionsItemStatusUnknown ProjectStatusConditionsItemStatus = "Unknown"
)

// Defines values for ServiceaccountStatusConditionsItemStatus.
const (
	ServiceaccountStatusConditionsItemStatusFalse   ServiceaccountStatusConditionsItemStatus = "False"
	ServiceaccountStatusConditionsItemStatusTrue    ServiceaccountStatusConditionsItemStatus = "True"
	ServiceaccountStatusConditionsItemStatusUnknown ServiceaccountStatusConditionsItemStatus = "Unknown"
)

// Defines values for ServiceaccountcredentialSpecType.
const (
	Rs256Jwt ServiceaccountcredentialSpecType = "rs256-jwt"
)

// Defines values for ServiceaccountcredentialStatusConditionsItemStatus.
const (
	ServiceaccountcredentialStatusConditionsItemStatusFalse   ServiceaccountcredentialStatusConditionsItemStatus = "False"
	ServiceaccountcredentialStatusConditionsItemStatusTrue    ServiceaccountcredentialStatusConditionsItemStatus = "True"
	ServiceaccountcredentialStatusConditionsItemStatusUnknown ServiceaccountcredentialStatusConditionsItemStatus = "Unknown"
)

// BaseMetadataResponse Common metadata fields for all resource responses.
type BaseMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to determine when objects have changed. Any reconciliation, or system-driven status change, can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`
}

// Error Standard error response sent by all endpoints on failure.
type Error struct {
	// Debug Additional human-readable diagnostic information in English. This content is safe to surface to end users. MUST NOT be used for programmatic logic. The content may evolve at any time and is not stable.
	Debug *string `json:"debug,omitempty"`

	// Reason Stable, textual error code. This MUST be used by clients for programmatic handling. Examples include: FieldValueInvalid, Unauthorized, Forbidden.
	Reason string `json:"reason"`
}

// GlobalMetadataRequest Standard metadata for global resources.
type GlobalMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalMetadataRequestPatch Standard metadata for global resources used for PATCH operations.
type GlobalMetadataRequestPatch struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id *string `json:"id,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalMetadataResponse defines model for GlobalMetadataResponse.
type GlobalMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to determine when objects have changed. Any reconciliation, or system-driven status change, can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalProjectMetadataRequest defines model for GlobalProjectMetadataRequest.
type GlobalProjectMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Project Project to which this resource belongs.
	Project *string `json:"project,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalProjectMetadataRequestPatch defines model for GlobalProjectMetadataRequestPatch.
type GlobalProjectMetadataRequestPatch struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id *string `json:"id,omitempty"`

	// Project Project to which this resource belongs.
	Project *string `json:"project,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalProjectMetadataResponse defines model for GlobalProjectMetadataResponse.
type GlobalProjectMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Project Project to which this resource belongs.
	Project *string `json:"project,omitempty"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to determine when objects have changed. Any reconciliation, or system-driven status change, can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// Organization defines model for Organization.
type Organization struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind     Kind `json:"kind"`
	Metadata struct {
		// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
		CreationTimestamp time.Time `json:"creationTimestamp"`

		// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
		Generation int64 `json:"generation"`

		// Id Unique identifier for the organization. Immutable.
		Id *openapi_types.UUID `json:"id,omitempty"`

		// ResourceVersion String that identifies the internal version of this object that can be used by clients to determine when objects have changed. Any reconciliation, or system-driven status change, can change the resourceVersion, not only a change of spec.
		ResourceVersion *string `json:"resourceVersion,omitempty"`

		// Uid System-assigned unique identifier for the resource. Immutable.
		Uid openapi_types.UUID `json:"uid"`
	} `json:"metadata"`
	Spec OrganizationSpec `json:"spec"`

	// Status OrgQuotaStatus defines the observed state of OrgQuota.
	Status OrganizationStatus `json:"status"`
}

// OrganizationList defines model for OrganizationList.
type OrganizationList struct {
	Items *[]Organization `json:"items,omitempty"`
}

// OrganizationPatchRequest defines model for OrganizationPatchRequest.
type OrganizationPatchRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion *ApiVersion `json:"apiVersion,omitempty"`

	// Kind Specifies the type of resource this object represents.
	Kind     *Kind      `json:"kind,omitempty"`
	Metadata *Metadata  `json:"metadata,omitempty"`
	Spec     *PatchSpec `json:"spec,omitempty"`
}

// OrganizationSpec defines model for OrganizationSpec.
type OrganizationSpec struct {
	// Name Human-friendly name for the resource. Mutable. Not required to be unique.
	Name *string `json:"name,omitempty"`

	// Quotas Quotas defines the quotas (i.e. limits) that this Organization is allowed
	// to use per product.
	Quotas *OrganizationSpecQuotas `json:"quotas,omitempty"`
}

// OrganizationSpecQuotas Quotas defines the quotas (i.e. limits) that this Organization is allowed
// to use per product.
type OrganizationSpecQuotas struct {
	// Compute Compute defines the quotas that this Organization is allowed
	// to use for compute resources.
	Compute *struct {
		// BlockStorage BlockStorage defines the disk storage quota that this Organization is allowed
		// to use, aggregated across all resource groups and VMs, with a unit, e.g. "600 GB".
		BlockStorage *string `json:"blockStorage,omitempty"`

		// Gpus GPUs defines the number of GPU instances that this Organization is allowed to use, aggregated
		// across all resource groups and VMs. There is a quota per GPU model.
		Gpus *OrganizationSpecQuotasGpus `json:"gpus,omitempty"`

		// Memory Memory defines the memory quota that this Organization is allowed
		// to use, aggregated across all resource groups and VMs, with a unit, e.g. "600 GB".
		Memory *string `json:"memory,omitempty"`

		// VCPUs VCPUs defines the maximum number of vCPUs that this Organization is allowed
		// to use, aggregated across all resource groups and VMs.
		VCPUs *int64 `json:"vCPUs,omitempty"`
	} `json:"compute,omitempty"`

	// Networking Networking defines the quotas that this Organization is allowed
	// to use for networking resources.
	Networking *struct {
		// PublicIPs PublicIPs defines the maximum number of public IPs that this Organization is allowed
		// to use, aggregated across all resource groups.
		PublicIPs *int64 `json:"publicIPs,omitempty"`
	} `json:"networking,omitempty"`

	// ObjectStorage ObjectStorage defines the quotas that this Organization is allowed
	// to use for the Object Storage product.
	ObjectStorage *struct {
		// TotalSize TotalSize defines the maximum storage capacity that this Organization
		// may use, aggregated across all resource groups and buckets. It is defined
		// with a value and a unit of KB, MB, GB, or TB. There is also a special
		// value of 'unlimited' that specifies that no limit is enforced.
		TotalSize *string `json:"totalSize,omitempty"`
	} `json:"objectStorage,omitempty"`
}

// OrganizationSpecQuotasGpus GPUs defines the number of GPU instances that this Organization is allowed to use, aggregated
// across all resource groups and VMs. There is a quota per GPU model.
type OrganizationSpecQuotasGpus map[string]int64

// OrganizationStatus OrgQuotaStatus defines the observed state of OrgQuota.
type OrganizationStatus struct {
	// QuotaUsage QuotaUsage reports the current usage of quotas for this Organization.
	QuotaUsage *OrganizationStatusQuotaUsage `json:"quotaUsage,omitempty"`
}

// OrganizationStatusQuotaUsage QuotaUsage reports the current usage of quotas for this Organization.
type OrganizationStatusQuotaUsage struct {
	// Compute Compute reports the current usage of compute resources.
	Compute *struct {
		// BlockStorage BlockStorage reports the current usage of block storage
		// in human readable format.
		BlockStorage *string `json:"blockStorage,omitempty"`

		// BlockStorageInMBs BlockStorage reports the current usage of block storage in MBs
		BlockStorageInMBs *int64 `json:"blockStorageInMBs,omitempty"`

		// Gpus GPUs reports the current usage of GPUs.
		Gpus *OrganizationStatusQuotaUsageGpus `json:"gpus,omitempty"`

		// Memory Memory reports the current usage of memory in human readable format
		Memory *string `json:"memory,omitempty"`

		// MemoryInKiBs Memory reports the current usage of memory in KiBs
		MemoryInKiBs *int64 `json:"memoryInKiBs,omitempty"`

		// VCPUs VCPUs reports the current usage of vCPUs.
		VCPUs *int64 `json:"vCPUs,omitempty"`
	} `json:"compute,omitempty"`

	// Networking Networking reports the current usage of networking resources.
	Networking *struct {
		// PublicIPs PublicIPs reports the current usage of public IPs.
		PublicIPs *int64 `json:"publicIPs,omitempty"`
	} `json:"networking,omitempty"`
}

// OrganizationStatusQuotaUsageGpus GPUs reports the current usage of GPUs.
type OrganizationStatusQuotaUsageGpus map[string]int64

// PermissionSet defines model for PermissionSet.
type PermissionSet struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global project-scoped resources.
	Metadata GlobalProjectMetadataResponse `json:"metadata"`
	Spec     PermissionSetSpec             `json:"spec"`

	// Status PermissionSetStatus defines the observed state of permission sets.
	Status PermissionSetStatus `json:"status"`
}

// PermissionSetList defines model for PermissionSetList.
type PermissionSetList struct {
	Items *[]PermissionSet `json:"items,omitempty"`
}

// PermissionSetPatchRequest defines model for PermissionSetPatchRequest.
type PermissionSetPatchRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion *ApiVersion `json:"apiVersion,omitempty"`

	// Kind Specifies the type of resource this object represents.
	Kind *Kind `json:"kind,omitempty"`

	// Metadata Standard metadata for global, project-scoped resource  used for PATCH operations.
	Metadata *GlobalProjectMetadataRequestPatch `json:"metadata,omitempty"`
	Spec     *PatchSpec                         `json:"spec,omitempty"`
}

// PermissionSetRequest defines model for PermissionSetRequest.
type PermissionSetRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global, project-scoped resource
	Metadata GlobalProjectMetadataRequest `json:"metadata"`
	Spec     PermissionSetSpec            `json:"spec"`
}

// PermissionSetSpec defines model for PermissionSetSpec.
type PermissionSetSpec struct {
	Admin   bool                     `json:"admin"`
	Subject PermissionSetSpecSubject `json:"subject"`
}

// PermissionSetSpecSubject defines model for PermissionSetSpecSubject.
type PermissionSetSpecSubject struct {
	Type PermissionSetSpecSubjectType `json:"type"`
	User struct {
		Email string `json:"email"`
	} `json:"user"`
}

// PermissionSetSpecSubjectType defines model for PermissionSetSpecSubject.Type.
type PermissionSetSpecSubjectType string

// PermissionSetStatus PermissionSetStatus defines the observed state of permission sets.
type PermissionSetStatus struct {
	// Conditions Conditions represents the state of the PermissionSet over time.
	Conditions *[]PermissionSetStatusConditionsItem `json:"conditions,omitempty"`
}

// PermissionSetStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type PermissionSetStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status PermissionSetStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// PermissionSetStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type PermissionSetStatusConditionsItemStatus string

// Project defines model for Project.
type Project struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global resources.
	Metadata GlobalMetadataResponse `json:"metadata"`

	// Spec ProjectSpec defines the desired state of project.
	Spec ProjectSpec `json:"spec"`

	// Status ProjectStatus defines the observed state of project.
	Status ProjectStatus `json:"status"`
}

// ProjectList defines model for ProjectList.
type ProjectList struct {
	Items *[]Project `json:"items,omitempty"`
}

// ProjectPatchRequest defines model for ProjectPatchRequest.
type ProjectPatchRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion *ApiVersion `json:"apiVersion,omitempty"`

	// Kind Specifies the type of resource this object represents.
	Kind *Kind `json:"kind,omitempty"`

	// Metadata Standard metadata for global resources used for PATCH operations.
	Metadata *GlobalMetadataRequestPatch `json:"metadata,omitempty"`
	Spec     *PatchSpec                  `json:"spec,omitempty"`
}

// ProjectRequest defines model for ProjectRequest.
type ProjectRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global resources.
	Metadata GlobalMetadataRequest `json:"metadata"`

	// Spec ProjectSpec defines the desired state of project.
	Spec ProjectSpec `json:"spec"`
}

// ProjectSpec ProjectSpec defines the desired state of project.
type ProjectSpec struct {
	// Name Human-friendly name for the resource. Mutable. Not required to be unique.
	Name *string `json:"name,omitempty"`

	// Organization Organization is the id of the Organization resource this project belongs to.
	// This field is required and immutable after creation.
	Organization string `json:"organization"`
}

// ProjectStatus ProjectStatus defines the observed state of project.
type ProjectStatus struct {
	// Conditions Conditions represents the state of the Project over time.
	// Each condition follows the Kubernetes API conventions for a condition:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
	// Conditions ConditionsSet `json:"conditions,omitempty"`
	Conditions *[]ProjectStatusConditionsItem `json:"conditions,omitempty"`
}

// ProjectStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type ProjectStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status ProjectStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// ProjectStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type ProjectStatusConditionsItemStatus string

// RevokeRequest defines model for RevokeRequest.
type RevokeRequest struct {
	// Reason Reason is the reason for revoking the credential.
	Reason string `json:"reason"`
}

// Serviceaccount defines model for Serviceaccount.
type Serviceaccount struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global project-scoped resources.
	Metadata GlobalProjectMetadataResponse `json:"metadata"`
	Spec     ServiceaccountSpec            `json:"spec"`

	// Status ServiceAccountStatus defines the observed state of ServiceAccount.
	Status ServiceaccountStatus `json:"status"`
}

// ServiceaccountList defines model for ServiceaccountList.
type ServiceaccountList struct {
	Items *[]Serviceaccount `json:"items,omitempty"`
}

// ServiceaccountPatchRequest defines model for ServiceaccountPatchRequest.
type ServiceaccountPatchRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion *ApiVersion `json:"apiVersion,omitempty"`

	// Kind Specifies the type of resource this object represents.
	Kind *Kind `json:"kind,omitempty"`

	// Metadata Standard metadata for global, project-scoped resource  used for PATCH operations.
	Metadata *GlobalProjectMetadataRequestPatch `json:"metadata,omitempty"`
	Spec     *PatchSpec                         `json:"spec,omitempty"`
}

// ServiceaccountRequest defines model for ServiceaccountRequest.
type ServiceaccountRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global, project-scoped resource
	Metadata GlobalProjectMetadataRequest `json:"metadata"`
	Spec     ServiceaccountSpec           `json:"spec"`
}

// ServiceaccountSpec defines model for ServiceaccountSpec.
type ServiceaccountSpec struct {
	// Description Description is a human-readable description of the service account.
	Description *string `json:"description,omitempty"`

	// Enabled Enabled indicates whether the service account is enabled. Disabled service accounts cannot be used for authentication.
	Enabled *bool `json:"enabled,omitempty"`
}

// ServiceaccountStatus ServiceAccountStatus defines the observed state of ServiceAccount.
type ServiceaccountStatus struct {
	// Conditions Conditions represents the state of the ServiceAccount over time.
	Conditions *[]ServiceaccountStatusConditionsItem `json:"conditions,omitempty"`

	// LastRevocationTime LastRevocationTime is the timestamp of the most recent credential revocation.
	LastRevocationTime *time.Time `json:"lastRevocationTime,omitempty"`

	// OauthClientId OAuthClientID is the identifier to be used for login in OAuth2/OIDC.
	OauthClientId *string `json:"oauthClientId,omitempty"`
}

// ServiceaccountStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type ServiceaccountStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status ServiceaccountStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// ServiceaccountStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type ServiceaccountStatusConditionsItemStatus string

// Serviceaccountcredential Response schema for a ServiceAccountCredential. Note: The privateKeyJwk field in status is a base64-encoded JSON string only populated in the CreateCredential API response.
type Serviceaccountcredential struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global project-scoped resources.
	Metadata GlobalProjectMetadataResponse `json:"metadata"`
	Spec     ServiceaccountcredentialSpec  `json:"spec"`

	// Status ServiceAccountCredentialStatus defines the observed state of ServiceAccountCredential.
	Status ServiceaccountcredentialStatus `json:"status"`
}

// ServiceaccountcredentialList defines model for ServiceaccountcredentialList.
type ServiceaccountcredentialList struct {
	Items *[]Serviceaccountcredential `json:"items,omitempty"`
}

// ServiceaccountcredentialRequest defines model for ServiceaccountcredentialRequest.
type ServiceaccountcredentialRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global, project-scoped resource
	Metadata GlobalProjectMetadataRequest `json:"metadata"`
	Spec     ServiceaccountcredentialSpec `json:"spec"`
}

// ServiceaccountcredentialSpec defines model for ServiceaccountcredentialSpec.
type ServiceaccountcredentialSpec struct {
	// AccountRef AccountRef is the reference to the parent ServiceAccount.
	AccountRef ServiceaccountcredentialSpecAccountRef `json:"accountRef"`

	// Description Description is a human-readable description of the credential.
	Description *string `json:"description,omitempty"`

	// ExpiresAt ExpiresAt is the timestamp when the credential expires.
	ExpiresAt time.Time `json:"expiresAt"`

	// RevocationRequest RevocationRequest is used to request revocation of this credential.
	RevocationRequest *ServiceaccountcredentialSpecRevocationRequest `json:"revocationRequest,omitempty"`

	// Rs256Jwt RS256Jwt contains the RSA key pair credential details. This field is required when type is "rs256-jwt".
	Rs256Jwt *ServiceaccountcredentialSpecRs256Jwt `json:"rs256Jwt,omitempty"`

	// Type Type is the type of credential.
	Type ServiceaccountcredentialSpecType `json:"type"`
}

// ServiceaccountcredentialSpecType Type is the type of credential.
type ServiceaccountcredentialSpecType string

// ServiceaccountcredentialSpecAccountRef AccountRef is the reference to the parent ServiceAccount.
type ServiceaccountcredentialSpecAccountRef struct {
	// Fqid FQID is the fully qualified identifier of the ServiceAccount. Example: /iam/projects/abcd/serviceAccounts/sa-cicd-123
	Fqid string `json:"fqid"`
}

// ServiceaccountcredentialSpecRevocationRequest RevocationRequest is used to request revocation of this credential.
type ServiceaccountcredentialSpecRevocationRequest struct {
	// Reason Reason is the reason for the revocation request.
	Reason *string `json:"reason,omitempty"`

	// Requested Requested indicates whether revocation has been requested.
	Requested bool `json:"requested"`
}

// ServiceaccountcredentialSpecRs256Jwt RS256Jwt contains the RSA key pair credential details. This field is required when type is "rs256-jwt".
type ServiceaccountcredentialSpecRs256Jwt struct {
	// AccessTokenLifetime AccessTokenLifetime is the lifetime of access tokens issued for this credential, in seconds.
	AccessTokenLifetime *int `json:"accessTokenLifetime,omitempty"`
}

// ServiceaccountcredentialStatus ServiceAccountCredentialStatus defines the observed state of ServiceAccountCredential.
type ServiceaccountcredentialStatus struct {
	// Conditions Conditions represents the state of the ServiceAccountCredential over time. Each condition follows the Kubernetes API conventions for a condition.
	Conditions *[]ServiceaccountcredentialStatusConditionsItem `json:"conditions,omitempty"`

	// PrivateKeyJwk PrivateKeyJWK contains the private key components as a base64-encoded JSON string. This field is only populated in the CreateCredential API response and is not stored.
	PrivateKeyJwk *string `json:"privateKeyJwk,omitempty"`

	// RevokedAt RevokedAt is the timestamp when the credential has been revoked.
	RevokedAt *time.Time `json:"revokedAt,omitempty"`
}

// ServiceaccountcredentialStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type ServiceaccountcredentialStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status ServiceaccountcredentialStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// ServiceaccountcredentialStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type ServiceaccountcredentialStatusConditionsItemStatus string

// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
type UserLabels map[string]string

// ApiVersion Identifies the version of the API schema used for this resource.
// It should be the same than the version in the path, otherwise the request will be rejected.
type ApiVersion = string

// Kind Specifies the type of resource this object represents.
type Kind = string

// Metadata defines model for metadata.
type Metadata struct {
	// Id Unique identifier for the organization. Immutable.
	Id *openapi_types.UUID `json:"id,omitempty"`
}

// PatchSpec defines model for patchSpec.
type PatchSpec struct {
	// Description Description is a human-readable description of the service account.
	Description *string `json:"description,omitempty"`

	// Enabled Enabled indicates whether the service account is enabled. Disabled service accounts cannot be used for authentication.
	Enabled *bool `json:"enabled,omitempty"`
}

// GetIamV1beta1ProjectsProjectIDPermissionSetsParams defines parameters for GetIamV1beta1ProjectsProjectIDPermissionSets.
type GetIamV1beta1ProjectsProjectIDPermissionSetsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetIamV1beta1ProjectsProjectIDServiceAccountsParams defines parameters for GetIamV1beta1ProjectsProjectIDServiceAccounts.
type GetIamV1beta1ProjectsProjectIDServiceAccountsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentialsParams defines parameters for GetIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentials.
type GetIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentialsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// PatchIamV1beta1OrganizationsOrganizationIDJSONRequestBody defines body for PatchIamV1beta1OrganizationsOrganizationID for application/json ContentType.
type PatchIamV1beta1OrganizationsOrganizationIDJSONRequestBody = OrganizationPatchRequest

// PostIamV1beta1ProjectsJSONRequestBody defines body for PostIamV1beta1Projects for application/json ContentType.
type PostIamV1beta1ProjectsJSONRequestBody = ProjectRequest

// PatchIamV1beta1ProjectsProjectIDJSONRequestBody defines body for PatchIamV1beta1ProjectsProjectID for application/json ContentType.
type PatchIamV1beta1ProjectsProjectIDJSONRequestBody = ProjectPatchRequest

// PostIamV1beta1ProjectsProjectIDPermissionSetsJSONRequestBody defines body for PostIamV1beta1ProjectsProjectIDPermissionSets for application/json ContentType.
type PostIamV1beta1ProjectsProjectIDPermissionSetsJSONRequestBody = PermissionSetRequest

// PatchIamV1beta1ProjectsProjectIDPermissionSetsPermissionSetIDJSONRequestBody defines body for PatchIamV1beta1ProjectsProjectIDPermissionSetsPermissionSetID for application/json ContentType.
type PatchIamV1beta1ProjectsProjectIDPermissionSetsPermissionSetIDJSONRequestBody = PermissionSetPatchRequest

// PostIamV1beta1ProjectsProjectIDServiceAccountsJSONRequestBody defines body for PostIamV1beta1ProjectsProjectIDServiceAccounts for application/json ContentType.
type PostIamV1beta1ProjectsProjectIDServiceAccountsJSONRequestBody = ServiceaccountRequest

// PatchIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDJSONRequestBody defines body for PatchIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountID for application/json ContentType.
type PatchIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDJSONRequestBody = ServiceaccountPatchRequest

// PostIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentialsJSONRequestBody defines body for PostIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentials for application/json ContentType.
type PostIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentialsJSONRequestBody = ServiceaccountcredentialRequest

// PostIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentialsCredentialIDRevokeJSONRequestBody defines body for PostIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentialsCredentialIDRevoke for application/json ContentType.
type PostIamV1beta1ProjectsProjectIDServiceAccountsServiceAccountIDServiceAccountCredentialsCredentialIDRevokeJSONRequestBody = RevokeRequest
