// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package quotas

import (
	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/metrics"
	"github.com/evroc-oss/evroc-go-sdk/types/quotas"
)

const (
	apiVersion = "v1alpha2"

	// Resource type constants
	resourceOrgQuotas     = "orgQuotas"
	resourceProjectQuotas = "projectQuotas"
)

// ContextProvider provides access to context configuration
type ContextProvider interface {
	DefaultProject() string
	DefaultRegion() string
	DefaultOrganization() string
}

// Client provides access to evroc quotas API
type Client struct {
	rest    *rest.Client
	path    rest.ServicePath
	parent  ContextProvider
	metrics *metrics.Manager
}

// List response types
type (
	OrgquotaList struct {
		Items []quotas.Orgquota `json:"items,omitempty"`
	}

	ProjectquotaList struct {
		Items []quotas.Projectquota `json:"items,omitempty"`
	}
)

// NewClient creates a new quotas API client with a parent context provider
func NewClient(restClient *rest.Client, parent ContextProvider) *Client {
	return &Client{
		rest:   restClient,
		path:   rest.NewServicePath("quotas", apiVersion),
		parent: parent,
	}
}

// OrganizationQuotas returns the OrganizationQuotas service
func (c *Client) OrganizationQuotas() *OrganizationQuotasService {
	return &OrganizationQuotasService{client: c}
}

// ProjectQuotas returns the ProjectQuotas service
func (c *Client) ProjectQuotas() *ProjectQuotasService {
	return &ProjectQuotasService{client: c}
}
