// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 evroc

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package quotas

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/quotas"
)

// OrganizationQuotasService provides operations for OrganizationQuotas
type OrganizationQuotasService struct {
	client *Client
}

// Get retrieves a Orgquota by name
func (s *OrganizationQuotasService) Get(ctx context.Context, name string) (*quotas.Orgquota, error) {
	path := s.client.path.GlobalResourcePath(resourceOrganizationQuotas, name)
	return rest.GetResource[*quotas.Orgquota](ctx, s.client.rest, path)
}
