// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package quotas

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/quotas"
)

// OrganizationQuotasService provides operations for OrganizationQuotas
type OrganizationQuotasService struct {
	client *Client
}

// Get retrieves a Orgquota using organization/region from config
func (s *OrganizationQuotasService) Get(ctx context.Context) (*quotas.Orgquota, error) {
	path := s.client.path.OrgCollectionPath(
		s.client.parent.DefaultOrganization(),
		s.client.parent.DefaultRegion(),
		resourceOrgQuotas)
	return rest.GetResource[*quotas.Orgquota](ctx, s.client.rest, path)
}
