// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 evroc

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package quotas

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/quotas"
)

// ProjectQuotasService provides operations for ProjectQuotas
type ProjectQuotasService struct {
	client *Client
}

// Get retrieves a Projectquota by name
func (s *ProjectQuotasService) Get(ctx context.Context, name string) (*quotas.Projectquota, error) {
	path := s.client.path.GlobalResourcePath(resourceProjectQuotas, name)
	return rest.GetResource[*quotas.Projectquota](ctx, s.client.rest, path)
}
