// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package quotas

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/quotas"
)

// ProjectQuotasService provides operations for ProjectQuotas
type ProjectQuotasService struct {
	client *Client
}

// Get retrieves a Projectquota using project/region from config
func (s *ProjectQuotasService) Get(ctx context.Context) (*quotas.Projectquota, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceProjectQuotas)
	return rest.GetResource[*quotas.Projectquota](ctx, s.client.rest, path)
}
