// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package networking

import (
	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/metrics"
	"github.com/evroc-oss/evroc-go-sdk/types/networking"
)

const (
	apiVersion = "v1beta1"

	// Resource type constants
	resourcePublicIPs            = "publicIPs"
	resourceSecurityGroups       = "securityGroups"
	resourceSubnets              = "subnets"
	resourceVirtualPrivateClouds = "virtualPrivateClouds"
)

// ContextProvider provides access to context configuration
type ContextProvider interface {
	DefaultProject() string
	DefaultRegion() string
	DefaultOrganization() string
}

// Client provides access to evroc networking API
type Client struct {
	rest    *rest.Client
	path    rest.ServicePath
	parent  ContextProvider
	metrics *metrics.Manager
}

// List response types
type (
	PublicIPList struct {
		Items []networking.PublicIP `json:"items,omitempty"`
	}

	SecurityGroupList struct {
		Items []networking.SecurityGroup `json:"items,omitempty"`
	}

	SubnetList struct {
		Items []networking.Subnet `json:"items,omitempty"`
	}

	VirtualPrivateCloudList struct {
		Items []networking.VirtualPrivateCloud `json:"items,omitempty"`
	}
)

// NewClient creates a new networking API client with a parent context provider
func NewClient(restClient *rest.Client, parent ContextProvider) *Client {
	return &Client{
		rest:   restClient,
		path:   rest.NewServicePath("networking", apiVersion),
		parent: parent,
	}
}

// PublicIPs returns the PublicIPs service
func (c *Client) PublicIPs() *PublicIPsService {
	return &PublicIPsService{client: c}
}

// SecurityGroups returns the SecurityGroups service
func (c *Client) SecurityGroups() *SecurityGroupsService {
	return &SecurityGroupsService{client: c}
}

// Subnets returns the Subnets service
func (c *Client) Subnets() *SubnetsService {
	return &SubnetsService{client: c}
}

// VirtualPrivateClouds returns the VirtualPrivateClouds service
func (c *Client) VirtualPrivateClouds() *VirtualPrivateCloudsService {
	return &VirtualPrivateCloudsService{client: c}
}
