// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package networking

import (
	"github.com/evroc-oss/evroc-go-sdk/labels"
	networking "github.com/evroc-oss/evroc-go-sdk/types/networking"
)

// Labels returns a label helper for PublicIPs.
func (s *PublicIPsService) Labels() *labels.Helper[*networking.PublicIP] {
	return labels.For[*networking.PublicIP](s, func(r *networking.PublicIP) map[string]string {
		if r.Metadata.UserLabels == nil {
			return nil
		}
		return map[string]string(*r.Metadata.UserLabels)
	})
}

// Labels returns a label helper for SecurityGroups.
func (s *SecurityGroupsService) Labels() *labels.Helper[*networking.SecurityGroup] {
	return labels.For[*networking.SecurityGroup](s, func(r *networking.SecurityGroup) map[string]string {
		if r.Metadata.UserLabels == nil {
			return nil
		}
		return map[string]string(*r.Metadata.UserLabels)
	})
}
