// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package networking

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/networking"
)

// PublicIPsService provides operations for PublicIPs
type PublicIPsService struct {
	client *Client
}

// Create creates a PublicIP using project/region from config.
func (s *PublicIPsService) Create(ctx context.Context, request *networking.PublicIPRequest) (*networking.PublicIP, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourcePublicIPs)
	return rest.CreateResource[*networking.PublicIP](ctx, s.client.rest, path, request)
}

// Delete deletes a PublicIP using project/region from config
func (s *PublicIPsService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourcePublicIPs,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a PublicIP by name using project/region from config
func (s *PublicIPsService) Get(ctx context.Context, name string) (*networking.PublicIP, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourcePublicIPs,
		name)
	return rest.GetResource[*networking.PublicIP](ctx, s.client.rest, path)
}

// List retrieves all PublicIPs using project/region from config with optional filters
func (s *PublicIPsService) List(ctx context.Context, filters ...rest.ListFilter) (*PublicIPList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourcePublicIPs)
	return rest.ListWithFilters[*PublicIPList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a PublicIP using project/region from config
func (s *PublicIPsService) Patch(ctx context.Context, name string, patch interface{}) (*networking.PublicIP, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourcePublicIPs,
		name)
	return rest.PatchResource[*networking.PublicIP](ctx, s.client.rest, path, patch)
}
