// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 evroc

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package networking

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/networking"
)

// SecurityGroupsService provides operations for SecurityGroups
type SecurityGroupsService struct {
	client *Client
}

// Create creates a SecurityGroup using project/region from config
func (s *SecurityGroupsService) Create(ctx context.Context, request *networking.SecurityGroupRequest) (*networking.SecurityGroup, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceSecurityGroups)
	return rest.CreateResource[*networking.SecurityGroup](ctx, s.client.rest, path, request)
}

// Delete deletes a SecurityGroup using project/region from config
func (s *SecurityGroupsService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceSecurityGroups,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a SecurityGroup by name using project/region from config
func (s *SecurityGroupsService) Get(ctx context.Context, name string) (*networking.SecurityGroup, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceSecurityGroups,
		name)
	return rest.GetResource[*networking.SecurityGroup](ctx, s.client.rest, path)
}

// List retrieves all SecurityGroups using project/region from config with optional filters
func (s *SecurityGroupsService) List(ctx context.Context, filters ...rest.ListFilter) (*SecurityGroupList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceSecurityGroups)
	return rest.ListWithFilters[*SecurityGroupList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a SecurityGroup using project/region from config
func (s *SecurityGroupsService) Patch(ctx context.Context, name string, patch interface{}) (*networking.SecurityGroup, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceSecurityGroups,
		name)
	return rest.PatchResource[*networking.SecurityGroup](ctx, s.client.rest, path, patch)
}

// Update updates a SecurityGroup using project/region from config
func (s *SecurityGroupsService) Update(ctx context.Context, name string, resource *networking.SecurityGroup) (*networking.SecurityGroup, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceSecurityGroups,
		name)
	return rest.UpdateResource[*networking.SecurityGroup](ctx, s.client.rest, path, resource)
}
