// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 evroc

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package networking

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/networking"
)

// SubnetsService provides operations for Subnets
type SubnetsService struct {
	client *Client
}

// Get retrieves a Subnet by name using project/region from config
func (s *SubnetsService) Get(ctx context.Context, name string) (*networking.Subnet, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceSubnets,
		name)
	return rest.GetResource[*networking.Subnet](ctx, s.client.rest, path)
}

// List retrieves all Subnets using project/region from config with optional filters
func (s *SubnetsService) List(ctx context.Context, filters ...rest.ListFilter) (*SubnetList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceSubnets)
	return rest.ListWithFilters[*SubnetList](ctx, s.client.rest, path, filters...)
}
