// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package networking

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/networking"
)

// VirtualPrivateCloudsService provides operations for VirtualPrivateClouds
type VirtualPrivateCloudsService struct {
	client *Client
}

// Create creates a VirtualPrivateCloud using project/region from config.
func (s *VirtualPrivateCloudsService) Create(ctx context.Context, request *networking.VirtualPrivateCloudRequest) (*networking.VirtualPrivateCloud, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceVirtualPrivateClouds)
	return rest.CreateResource[*networking.VirtualPrivateCloud](ctx, s.client.rest, path, request)
}

// Delete deletes a VirtualPrivateCloud using project/region from config
func (s *VirtualPrivateCloudsService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceVirtualPrivateClouds,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a VirtualPrivateCloud by name using project/region from config
func (s *VirtualPrivateCloudsService) Get(ctx context.Context, name string) (*networking.VirtualPrivateCloud, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceVirtualPrivateClouds,
		name)
	return rest.GetResource[*networking.VirtualPrivateCloud](ctx, s.client.rest, path)
}

// List retrieves all VirtualPrivateClouds using project/region from config with optional filters
func (s *VirtualPrivateCloudsService) List(ctx context.Context, filters ...rest.ListFilter) (*VirtualPrivateCloudList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceVirtualPrivateClouds)
	return rest.ListWithFilters[*VirtualPrivateCloudList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a VirtualPrivateCloud using project/region from config
func (s *VirtualPrivateCloudsService) Patch(ctx context.Context, name string, patch interface{}) (*networking.VirtualPrivateCloud, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceVirtualPrivateClouds,
		name)
	return rest.PatchResource[*networking.VirtualPrivateCloud](ctx, s.client.rest, path, patch)
}
