// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package think

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/think"
)

// ApiKeysService provides operations for ApiKeys
type ApiKeysService struct {
	client *Client
}

// Create creates a Apikey using project from config
func (s *ApiKeysService) Create(ctx context.Context, request *think.ApikeyRequest) (*think.Apikey, error) {
	path := s.client.path.ProjectCollectionPath(
		s.client.parent.DefaultProject(),
		resourceApiKeys)
	return rest.CreateResource[*think.Apikey](ctx, s.client.rest, path, request)
}

// Delete deletes a Apikey using project from config
func (s *ApiKeysService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ProjectResourcePath(
		s.client.parent.DefaultProject(),
		resourceApiKeys,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// List retrieves all Apikeys using project from config with optional filters
func (s *ApiKeysService) List(ctx context.Context, filters ...rest.ListFilter) (*ApikeyList, error) {
	path := s.client.path.ProjectCollectionPath(
		s.client.parent.DefaultProject(),
		resourceApiKeys)
	return rest.ListWithFilters[*ApikeyList](ctx, s.client.rest, path, filters...)
}
