// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package think

import (
	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/metrics"
	"github.com/evroc-oss/evroc-go-sdk/types/think"
)

const (
	apiVersion = "v1beta2"

	// Resource type constants
	resourceApiKeys      = "apiKeys"
	resourceModels       = "models"
	resourceSharedModels = "sharedModels"
	resourceSizes        = "sizes"
	resourceInstances    = "instances"
)

// ContextProvider provides access to context configuration
type ContextProvider interface {
	DefaultProject() string
	DefaultRegion() string
	DefaultOrganization() string
}

// Client provides access to evroc think API
type Client struct {
	rest    *rest.Client
	path    rest.ServicePath
	parent  ContextProvider
	metrics *metrics.Manager
}

// List response types
type (
	ApikeyList struct {
		Items []think.Apikey `json:"items,omitempty"`
	}

	ModelList struct {
		Items []think.Model `json:"items,omitempty"`
	}

	SharedmodelList struct {
		Items []think.Sharedmodel `json:"items,omitempty"`
	}

	SizeList struct {
		Items []think.Size `json:"items,omitempty"`
	}

	InstanceList struct {
		Items []think.Instance `json:"items,omitempty"`
	}
)

// NewClient creates a new think API client with a parent context provider
func NewClient(restClient *rest.Client, parent ContextProvider) *Client {
	return &Client{
		rest:   restClient,
		path:   rest.NewServicePath("think", apiVersion),
		parent: parent,
	}
}

// ApiKeys returns the ApiKeys service
func (c *Client) ApiKeys() *ApiKeysService {
	return &ApiKeysService{client: c}
}

// Models returns the Models service
func (c *Client) Models() *ModelsService {
	return &ModelsService{client: c}
}

// SharedModels returns the SharedModels service
func (c *Client) SharedModels() *SharedModelsService {
	return &SharedModelsService{client: c}
}

// Sizes returns the Sizes service
func (c *Client) Sizes() *SizesService {
	return &SizesService{client: c}
}

// Instances returns the Instances service
func (c *Client) Instances() *InstancesService {
	return &InstancesService{client: c}
}
