// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package think

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/think"
)

// InstancesService provides operations for Instances
type InstancesService struct {
	client *Client
}

// Create creates a Instance using project/region from config.
func (s *InstancesService) Create(ctx context.Context, request *think.InstanceRequest) (*think.Instance, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceInstances)
	return rest.CreateResource[*think.Instance](ctx, s.client.rest, path, request)
}

// Get retrieves a Instance by name using project/region from config
func (s *InstancesService) Get(ctx context.Context, name string) (*think.Instance, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceInstances,
		name)
	return rest.GetResource[*think.Instance](ctx, s.client.rest, path)
}

// List retrieves all Instances using project/region from config with optional filters
func (s *InstancesService) List(ctx context.Context, filters ...rest.ListFilter) (*InstanceList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceInstances)
	return rest.ListWithFilters[*InstanceList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a Instance using project/region from config
func (s *InstancesService) Patch(ctx context.Context, name string, patch interface{}) (*think.Instance, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceInstances,
		name)
	return rest.PatchResource[*think.Instance](ctx, s.client.rest, path, patch)
}

// Delete deletes a Instance using project/region from config
func (s *InstancesService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceInstances,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}
