// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package think

import (
	"github.com/evroc-oss/evroc-go-sdk/labels"
	think "github.com/evroc-oss/evroc-go-sdk/types/think"
)

// Labels returns a label helper for Instances.
func (s *InstancesService) Labels() *labels.Helper[*think.Instance] {
	return labels.For[*think.Instance](s, func(r *think.Instance) map[string]string {
		if r.Metadata.UserLabels == nil {
			return nil
		}
		return map[string]string(*r.Metadata.UserLabels)
	})
}
