// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package think

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/think"
)

// ModelsService provides operations for Models
type ModelsService struct {
	client *Client
}

// Get retrieves a Model by name using project from config
func (s *ModelsService) Get(ctx context.Context, name string) (*think.Model, error) {
	path := s.client.path.ProjectResourcePath(
		s.client.parent.DefaultProject(),
		resourceModels,
		name)
	return rest.GetResource[*think.Model](ctx, s.client.rest, path)
}

// List retrieves all Models using project from config with optional filters
func (s *ModelsService) List(ctx context.Context, filters ...rest.ListFilter) (*ModelList, error) {
	path := s.client.path.ProjectCollectionPath(
		s.client.parent.DefaultProject(),
		resourceModels)
	return rest.ListWithFilters[*ModelList](ctx, s.client.rest, path, filters...)
}
