// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package think

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
)

// SharedModelsService provides operations for SharedModels
type SharedModelsService struct {
	client *Client
}

// List retrieves all Sharedmodels using project from config with optional filters
func (s *SharedModelsService) List(ctx context.Context, filters ...rest.ListFilter) (*SharedmodelList, error) {
	path := s.client.path.ProjectCollectionPath(
		s.client.parent.DefaultProject(),
		resourceSharedModels)
	return rest.ListWithFilters[*SharedmodelList](ctx, s.client.rest, path, filters...)
}
