// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package think

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
)

// SizesService provides operations for Sizes
type SizesService struct {
	client *Client
}

// List retrieves all Sizes using project from config with optional filters
func (s *SizesService) List(ctx context.Context, filters ...rest.ListFilter) (*SizeList, error) {
	path := s.client.path.ProjectCollectionPath(
		s.client.parent.DefaultProject(),
		resourceSizes)
	return rest.ListWithFilters[*SizeList](ctx, s.client.rest, path, filters...)
}
