// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 evroc

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package storage

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/storage"
)

// BucketsService provides operations for Buckets
type BucketsService struct {
	client *Client
}

// Create creates a Bucket using project/region from config.
func (s *BucketsService) Create(ctx context.Context, request *storage.BucketRequest) (*storage.Bucket, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBuckets)
	return rest.CreateResource[*storage.Bucket](ctx, s.client.rest, path, request)
}

// Delete deletes a Bucket using project/region from config
func (s *BucketsService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBuckets,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a Bucket by name using project/region from config
func (s *BucketsService) Get(ctx context.Context, name string) (*storage.Bucket, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBuckets,
		name)
	return rest.GetResource[*storage.Bucket](ctx, s.client.rest, path)
}

// List retrieves all Buckets using project/region from config with optional filters
func (s *BucketsService) List(ctx context.Context, filters ...rest.ListFilter) (*BucketList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBuckets)
	return rest.ListWithFilters[*BucketList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a Bucket using project/region from config
func (s *BucketsService) Patch(ctx context.Context, name string, patch interface{}) (*storage.Bucket, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBuckets,
		name)
	return rest.PatchResource[*storage.Bucket](ctx, s.client.rest, path, patch)
}

// Update updates a Bucket using project/region from config
func (s *BucketsService) Update(ctx context.Context, name string, resource *storage.Bucket) (*storage.Bucket, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBuckets,
		name)
	return rest.UpdateResource[*storage.Bucket](ctx, s.client.rest, path, resource)
}
