// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package storage

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/storage"
)

// BucketServiceAccountSecretsService provides operations for BucketServiceAccountSecrets
type BucketServiceAccountSecretsService struct {
	client *Client
}

// Get retrieves a Bucketserviceaccountsecret by name using project/region from config
func (s *BucketServiceAccountSecretsService) Get(ctx context.Context, name string) (*storage.Bucketserviceaccountsecret, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBucketServiceAccountSecrets,
		name)
	return rest.GetResource[*storage.Bucketserviceaccountsecret](ctx, s.client.rest, path)
}
