// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package storage

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/storage"
)

// BucketServiceAccountsService provides operations for BucketServiceAccounts
type BucketServiceAccountsService struct {
	client *Client
}

// Create creates a BucketServiceAccount using project/region from config.
func (s *BucketServiceAccountsService) Create(ctx context.Context, request *storage.BucketServiceAccountRequest) (*storage.BucketServiceAccount, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBucketServiceAccounts)
	return rest.CreateResource[*storage.BucketServiceAccount](ctx, s.client.rest, path, request)
}

// Delete deletes a BucketServiceAccount using project/region from config
func (s *BucketServiceAccountsService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBucketServiceAccounts,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a BucketServiceAccount by name using project/region from config
func (s *BucketServiceAccountsService) Get(ctx context.Context, name string) (*storage.BucketServiceAccount, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBucketServiceAccounts,
		name)
	return rest.GetResource[*storage.BucketServiceAccount](ctx, s.client.rest, path)
}

// List retrieves all BucketServiceAccounts using project/region from config with optional filters
func (s *BucketServiceAccountsService) List(ctx context.Context, filters ...rest.ListFilter) (*BucketServiceAccountList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBucketServiceAccounts)
	return rest.ListWithFilters[*BucketServiceAccountList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a BucketServiceAccount using project/region from config
func (s *BucketServiceAccountsService) Patch(ctx context.Context, name string, patch interface{}) (*storage.BucketServiceAccount, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBucketServiceAccounts,
		name)
	return rest.PatchResource[*storage.BucketServiceAccount](ctx, s.client.rest, path, patch)
}
