// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 evroc

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package storage

import (
	"github.com/evroc-oss/evroc-go-sdk/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/storage"
)

const (
	apiVersion = "v1"

	// Resource type constants
	resourceBucketServiceAccounts = "bucketServiceAccounts"
	resourceBuckets               = "buckets"
)

// ContextProvider provides access to context configuration
type ContextProvider interface {
	DefaultProject() string
	DefaultRegion() string
	DefaultOrganization() string
}

// Client provides access to evroc storage API
type Client struct {
	rest   *rest.Client
	path   rest.ServicePath
	parent ContextProvider
}

// List response types
type (
	BucketServiceAccountList struct {
		Items []storage.BucketServiceAccount `json:"items,omitempty"`
	}

	BucketList struct {
		Items []storage.Bucket `json:"items,omitempty"`
	}
)

// NewClient creates a new storage API client
func NewClient(restClient *rest.Client) *Client {
	return &Client{
		rest: restClient,
		path: rest.NewServicePath("storage", apiVersion),
	}
}

// NewClientWithParent creates a new storage API client with a parent context provider
func NewClientWithParent(restClient *rest.Client, parent ContextProvider) *Client {
	return &Client{
		rest:   restClient,
		path:   rest.NewServicePath("storage", apiVersion),
		parent: parent,
	}
}

// BucketServiceAccounts returns the BucketServiceAccounts service
func (c *Client) BucketServiceAccounts() *BucketServiceAccountsService {
	return &BucketServiceAccountsService{client: c}
}

// Buckets returns the Buckets service
func (c *Client) Buckets() *BucketsService {
	return &BucketsService{client: c}
}
