// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package storage

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/storage"
)

// FileStoresService provides operations for FileStores
type FileStoresService struct {
	client *Client
}

// Create creates a Filestore using project/region from config.
func (s *FileStoresService) Create(ctx context.Context, request *storage.FilestoreRequest) (*storage.Filestore, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceFileStores)
	return rest.CreateResource[*storage.Filestore](ctx, s.client.rest, path, request)
}

// Delete deletes a Filestore using project/region from config
func (s *FileStoresService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceFileStores,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a Filestore by name using project/region from config
func (s *FileStoresService) Get(ctx context.Context, name string) (*storage.Filestore, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceFileStores,
		name)
	return rest.GetResource[*storage.Filestore](ctx, s.client.rest, path)
}

// List retrieves all Filestores using project/region from config with optional filters
func (s *FileStoresService) List(ctx context.Context, filters ...rest.ListFilter) (*FilestoreList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceFileStores)
	return rest.ListWithFilters[*FilestoreList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a Filestore using project/region from config
func (s *FileStoresService) Patch(ctx context.Context, name string, patch interface{}) (*storage.Filestore, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceFileStores,
		name)
	return rest.PatchResource[*storage.Filestore](ctx, s.client.rest, path, patch)
}
