// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package storage

import (
	"github.com/evroc-oss/evroc-go-sdk/labels"
	storage "github.com/evroc-oss/evroc-go-sdk/types/storage"
)

// Labels returns a label helper for BucketServiceAccounts.
func (s *BucketServiceAccountsService) Labels() *labels.Helper[*storage.BucketServiceAccount] {
	return labels.For[*storage.BucketServiceAccount](s, func(r *storage.BucketServiceAccount) map[string]string {
		if r.Metadata.UserLabels == nil {
			return nil
		}
		return map[string]string(*r.Metadata.UserLabels)
	})
}

// Labels returns a label helper for Buckets.
func (s *BucketsService) Labels() *labels.Helper[*storage.Bucket] {
	return labels.For[*storage.Bucket](s, func(r *storage.Bucket) map[string]string {
		if r.Metadata.UserLabels == nil {
			return nil
		}
		return map[string]string(*r.Metadata.UserLabels)
	})
}
