// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package loadbalancer

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/loadbalancer"
)

// BackendPoolsService provides operations for BackendPools
type BackendPoolsService struct {
	client *Client
}

// Create creates a Backendpool using project/region from config.
func (s *BackendPoolsService) Create(ctx context.Context, request *loadbalancer.BackendpoolRequest) (*loadbalancer.Backendpool, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBackendPools)
	return rest.CreateResource[*loadbalancer.Backendpool](ctx, s.client.rest, path, request)
}

// Delete deletes a Backendpool using project/region from config
func (s *BackendPoolsService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBackendPools,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a Backendpool by name using project/region from config
func (s *BackendPoolsService) Get(ctx context.Context, name string) (*loadbalancer.Backendpool, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBackendPools,
		name)
	return rest.GetResource[*loadbalancer.Backendpool](ctx, s.client.rest, path)
}

// List retrieves all Backendpools using project/region from config with optional filters
func (s *BackendPoolsService) List(ctx context.Context, filters ...rest.ListFilter) (*BackendpoolList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBackendPools)
	return rest.ListWithFilters[*BackendpoolList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a Backendpool using project/region from config
func (s *BackendPoolsService) Patch(ctx context.Context, name string, patch interface{}) (*loadbalancer.Backendpool, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBackendPools,
		name)
	return rest.PatchResource[*loadbalancer.Backendpool](ctx, s.client.rest, path, patch)
}
