// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package loadbalancer

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/loadbalancer"
)

// BackendServicesService provides operations for BackendServices
type BackendServicesService struct {
	client *Client
}

// Create creates a Backendservice using project/region from config.
func (s *BackendServicesService) Create(ctx context.Context, request *loadbalancer.BackendserviceRequest) (*loadbalancer.Backendservice, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBackendServices)
	return rest.CreateResource[*loadbalancer.Backendservice](ctx, s.client.rest, path, request)
}

// Delete deletes a Backendservice using project/region from config
func (s *BackendServicesService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBackendServices,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a Backendservice by name using project/region from config
func (s *BackendServicesService) Get(ctx context.Context, name string) (*loadbalancer.Backendservice, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBackendServices,
		name)
	return rest.GetResource[*loadbalancer.Backendservice](ctx, s.client.rest, path)
}

// List retrieves all Backendservices using project/region from config with optional filters
func (s *BackendServicesService) List(ctx context.Context, filters ...rest.ListFilter) (*BackendserviceList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBackendServices)
	return rest.ListWithFilters[*BackendserviceList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a Backendservice using project/region from config
func (s *BackendServicesService) Patch(ctx context.Context, name string, patch interface{}) (*loadbalancer.Backendservice, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceBackendServices,
		name)
	return rest.PatchResource[*loadbalancer.Backendservice](ctx, s.client.rest, path, patch)
}
