// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package loadbalancer

import (
	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/metrics"
	"github.com/evroc-oss/evroc-go-sdk/types/loadbalancer"
)

const (
	apiVersion = "v1alpha1"

	// Resource type constants
	resourceLoadBalancers   = "loadBalancers"
	resourceBackendPools    = "backendPools"
	resourceBackendServices = "backendServices"
	resourceL4Routes        = "l4Routes"
)

// ContextProvider provides access to context configuration
type ContextProvider interface {
	DefaultProject() string
	DefaultRegion() string
	DefaultOrganization() string
}

// Client provides access to evroc loadbalancer API
type Client struct {
	rest    *rest.Client
	path    rest.ServicePath
	parent  ContextProvider
	metrics *metrics.Manager
}

// List response types
type (
	LoadbalancerList struct {
		Items []loadbalancer.Loadbalancer `json:"items,omitempty"`
	}

	BackendpoolList struct {
		Items []loadbalancer.Backendpool `json:"items,omitempty"`
	}

	BackendserviceList struct {
		Items []loadbalancer.Backendservice `json:"items,omitempty"`
	}

	L4routeList struct {
		Items []loadbalancer.L4route `json:"items,omitempty"`
	}
)

// NewClient creates a new loadbalancer API client with a parent context provider
func NewClient(restClient *rest.Client, parent ContextProvider) *Client {
	return &Client{
		rest:   restClient,
		path:   rest.NewServicePath("loadbalancer", apiVersion),
		parent: parent,
	}
}

// LoadBalancers returns the LoadBalancers service
func (c *Client) LoadBalancers() *LoadBalancersService {
	return &LoadBalancersService{client: c}
}

// BackendPools returns the BackendPools service
func (c *Client) BackendPools() *BackendPoolsService {
	return &BackendPoolsService{client: c}
}

// BackendServices returns the BackendServices service
func (c *Client) BackendServices() *BackendServicesService {
	return &BackendServicesService{client: c}
}

// L4Routes returns the L4Routes service
func (c *Client) L4Routes() *L4RoutesService {
	return &L4RoutesService{client: c}
}
