// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package loadbalancer

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/loadbalancer"
)

// L4RoutesService provides operations for L4Routes
type L4RoutesService struct {
	client *Client
}

// Create creates a L4route using project/region from config.
func (s *L4RoutesService) Create(ctx context.Context, request *loadbalancer.L4routeRequest) (*loadbalancer.L4route, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceL4Routes)
	return rest.CreateResource[*loadbalancer.L4route](ctx, s.client.rest, path, request)
}

// Delete deletes a L4route using project/region from config
func (s *L4RoutesService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceL4Routes,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a L4route by name using project/region from config
func (s *L4RoutesService) Get(ctx context.Context, name string) (*loadbalancer.L4route, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceL4Routes,
		name)
	return rest.GetResource[*loadbalancer.L4route](ctx, s.client.rest, path)
}

// List retrieves all L4routes using project/region from config with optional filters
func (s *L4RoutesService) List(ctx context.Context, filters ...rest.ListFilter) (*L4routeList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceL4Routes)
	return rest.ListWithFilters[*L4routeList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a L4route using project/region from config
func (s *L4RoutesService) Patch(ctx context.Context, name string, patch interface{}) (*loadbalancer.L4route, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceL4Routes,
		name)
	return rest.PatchResource[*loadbalancer.L4route](ctx, s.client.rest, path, patch)
}
