// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package loadbalancer

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/loadbalancer"
)

// LoadBalancersService provides operations for LoadBalancers
type LoadBalancersService struct {
	client *Client
}

// Create creates a Loadbalancer using project/region from config.
func (s *LoadBalancersService) Create(ctx context.Context, request *loadbalancer.LoadbalancerRequest) (*loadbalancer.Loadbalancer, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceLoadBalancers)
	return rest.CreateResource[*loadbalancer.Loadbalancer](ctx, s.client.rest, path, request)
}

// Delete deletes a Loadbalancer using project/region from config
func (s *LoadBalancersService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceLoadBalancers,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a Loadbalancer by name using project/region from config
func (s *LoadBalancersService) Get(ctx context.Context, name string) (*loadbalancer.Loadbalancer, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceLoadBalancers,
		name)
	return rest.GetResource[*loadbalancer.Loadbalancer](ctx, s.client.rest, path)
}

// List retrieves all Loadbalancers using project/region from config with optional filters
func (s *LoadBalancersService) List(ctx context.Context, filters ...rest.ListFilter) (*LoadbalancerList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceLoadBalancers)
	return rest.ListWithFilters[*LoadbalancerList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a Loadbalancer using project/region from config
func (s *LoadBalancersService) Patch(ctx context.Context, name string, patch interface{}) (*loadbalancer.Loadbalancer, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceLoadBalancers,
		name)
	return rest.PatchResource[*loadbalancer.Loadbalancer](ctx, s.client.rest, path, patch)
}
