// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 evroc

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package compute

import (
	"github.com/evroc-oss/evroc-go-sdk/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/compute"
)

const (
	apiVersion = "v1alpha2"

	// Resource type constants
	resourceDisks                  = "disks"
	resourceHotswapDiskAttachments = "hotswapDiskAttachments"
	resourcePlacementGroups        = "placementGroups"
	resourceVirtualMachines        = "virtualMachines"
)

// ContextProvider provides access to context configuration
type ContextProvider interface {
	DefaultProject() string
	DefaultRegion() string
	DefaultOrganization() string
}

// Client provides access to evroc compute API
type Client struct {
	rest   *rest.Client
	path   rest.ServicePath
	parent ContextProvider
}

// List response types
type (
	DiskList struct {
		Items []compute.Disk `json:"items,omitempty"`
	}

	HotswapDiskAttachmentList struct {
		Items []compute.HotswapDiskAttachment `json:"items,omitempty"`
	}

	PlacementGroupList struct {
		Items []compute.PlacementGroup `json:"items,omitempty"`
	}

	VirtualMachineList struct {
		Items []compute.VirtualMachine `json:"items,omitempty"`
	}
)

// NewClient creates a new compute API client
func NewClient(restClient *rest.Client) *Client {
	return &Client{
		rest: restClient,
		path: rest.NewServicePath("compute", apiVersion),
	}
}

// NewClientWithParent creates a new compute API client with a parent context provider
func NewClientWithParent(restClient *rest.Client, parent ContextProvider) *Client {
	return &Client{
		rest:   restClient,
		path:   rest.NewServicePath("compute", apiVersion),
		parent: parent,
	}
}

// Disks returns the Disks service
func (c *Client) Disks() *DisksService {
	return &DisksService{client: c}
}

// HotswapDiskAttachments returns the HotswapDiskAttachments service
func (c *Client) HotswapDiskAttachments() *HotswapDiskAttachmentsService {
	return &HotswapDiskAttachmentsService{client: c}
}

// PlacementGroups returns the PlacementGroups service
func (c *Client) PlacementGroups() *PlacementGroupsService {
	return &PlacementGroupsService{client: c}
}

// VirtualMachines returns the VirtualMachines service
func (c *Client) VirtualMachines() *VirtualMachinesService {
	return &VirtualMachinesService{client: c}
}
