// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package compute

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/compute"
)

// ComputeProfilesService provides operations for ComputeProfiles
type ComputeProfilesService struct {
	client *Client
}

// Get retrieves a Computeprofile by name
func (s *ComputeProfilesService) Get(ctx context.Context, name string) (*compute.Computeprofile, error) {
	path := s.client.path.GlobalResourcePath(resourceComputeProfiles, name)
	return rest.GetResource[*compute.Computeprofile](ctx, s.client.rest, path)
}

// List retrieves all Computeprofiles with optional filters
func (s *ComputeProfilesService) List(ctx context.Context, filters ...rest.ListFilter) (*ComputeprofileList, error) {
	path := s.client.path.GlobalCollectionPath(resourceComputeProfiles)
	return rest.ListWithFilters[*ComputeprofileList](ctx, s.client.rest, path, filters...)
}
