// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package compute

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/compute"
)

// CustomDiskImagesService provides operations for CustomDiskImages
type CustomDiskImagesService struct {
	client *Client
}

// Create creates a CustomDiskImage using project/region from config.
func (s *CustomDiskImagesService) Create(ctx context.Context, request *compute.CustomDiskImageRequest) (*compute.CustomDiskImage, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceCustomDiskImages)
	return rest.CreateResource[*compute.CustomDiskImage](ctx, s.client.rest, path, request)
}

// Delete deletes a CustomDiskImage using project/region from config
func (s *CustomDiskImagesService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceCustomDiskImages,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a CustomDiskImage by name using project/region from config
func (s *CustomDiskImagesService) Get(ctx context.Context, name string) (*compute.CustomDiskImage, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceCustomDiskImages,
		name)
	return rest.GetResource[*compute.CustomDiskImage](ctx, s.client.rest, path)
}

// List retrieves all CustomDiskImages using project/region from config with optional filters
func (s *CustomDiskImagesService) List(ctx context.Context, filters ...rest.ListFilter) (*CustomDiskImageList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceCustomDiskImages)
	return rest.ListWithFilters[*CustomDiskImageList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a CustomDiskImage using project/region from config
func (s *CustomDiskImagesService) Patch(ctx context.Context, name string, patch interface{}) (*compute.CustomDiskImage, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceCustomDiskImages,
		name)
	return rest.PatchResource[*compute.CustomDiskImage](ctx, s.client.rest, path, patch)
}
