// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package compute

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/compute"
)

// DiskImagesService provides operations for DiskImages
type DiskImagesService struct {
	client *Client
}

// Get retrieves a Diskimage by name
func (s *DiskImagesService) Get(ctx context.Context, name string) (*compute.Diskimage, error) {
	path := s.client.path.GlobalResourcePath(resourceDiskImages, name)
	return rest.GetResource[*compute.Diskimage](ctx, s.client.rest, path)
}

// List retrieves all Diskimages with optional filters
func (s *DiskImagesService) List(ctx context.Context, filters ...rest.ListFilter) (*DiskimageList, error) {
	path := s.client.path.GlobalCollectionPath(resourceDiskImages)
	return rest.ListWithFilters[*DiskimageList](ctx, s.client.rest, path, filters...)
}
