// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 evroc

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package compute

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/compute"
)

// DisksService provides operations for Disks
type DisksService struct {
	client *Client
}

// Create creates a Disk using project/region from config.
func (s *DisksService) Create(ctx context.Context, request *compute.DiskRequest) (*compute.Disk, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceDisks)
	return rest.CreateResource[*compute.Disk](ctx, s.client.rest, path, request)
}

// Delete deletes a Disk using project/region from config
func (s *DisksService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceDisks,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a Disk by name using project/region from config
func (s *DisksService) Get(ctx context.Context, name string) (*compute.Disk, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceDisks,
		name)
	return rest.GetResource[*compute.Disk](ctx, s.client.rest, path)
}

// List retrieves all Disks using project/region from config with optional filters
func (s *DisksService) List(ctx context.Context, filters ...rest.ListFilter) (*DiskList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceDisks)
	return rest.ListWithFilters[*DiskList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a Disk using project/region from config
func (s *DisksService) Patch(ctx context.Context, name string, patch interface{}) (*compute.Disk, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceDisks,
		name)
	return rest.PatchResource[*compute.Disk](ctx, s.client.rest, path, patch)
}

// Update updates a Disk using project/region from config
func (s *DisksService) Update(ctx context.Context, name string, resource *compute.Disk) (*compute.Disk, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceDisks,
		name)
	return rest.UpdateResource[*compute.Disk](ctx, s.client.rest, path, resource)
}
