// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 evroc

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package compute

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/compute"
)

// HotswapDiskAttachmentsService provides operations for HotswapDiskAttachments
type HotswapDiskAttachmentsService struct {
	client *Client
}

// Create creates a HotswapDiskAttachment using project/region from config
func (s *HotswapDiskAttachmentsService) Create(ctx context.Context, request *compute.HotswapDiskAttachmentRequest) (*compute.HotswapDiskAttachment, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceHotswapDiskAttachments)
	return rest.CreateResource[*compute.HotswapDiskAttachment](ctx, s.client.rest, path, request)
}

// Delete deletes a HotswapDiskAttachment using project/region from config
func (s *HotswapDiskAttachmentsService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceHotswapDiskAttachments,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a HotswapDiskAttachment by name using project/region from config
func (s *HotswapDiskAttachmentsService) Get(ctx context.Context, name string) (*compute.HotswapDiskAttachment, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceHotswapDiskAttachments,
		name)
	return rest.GetResource[*compute.HotswapDiskAttachment](ctx, s.client.rest, path)
}

// List retrieves all HotswapDiskAttachments using project/region from config with optional filters
func (s *HotswapDiskAttachmentsService) List(ctx context.Context, filters ...rest.ListFilter) (*HotswapDiskAttachmentList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceHotswapDiskAttachments)
	return rest.ListWithFilters[*HotswapDiskAttachmentList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a HotswapDiskAttachment using project/region from config
func (s *HotswapDiskAttachmentsService) Patch(ctx context.Context, name string, patch interface{}) (*compute.HotswapDiskAttachment, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceHotswapDiskAttachments,
		name)
	return rest.PatchResource[*compute.HotswapDiskAttachment](ctx, s.client.rest, path, patch)
}

// Update updates a HotswapDiskAttachment using project/region from config
func (s *HotswapDiskAttachmentsService) Update(ctx context.Context, name string, resource *compute.HotswapDiskAttachment) (*compute.HotswapDiskAttachment, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceHotswapDiskAttachments,
		name)
	return rest.UpdateResource[*compute.HotswapDiskAttachment](ctx, s.client.rest, path, resource)
}
