// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package compute

import (
	"github.com/evroc-oss/evroc-go-sdk/labels"
	compute "github.com/evroc-oss/evroc-go-sdk/types/compute"
)

// Labels returns a label helper for Disks.
func (s *DisksService) Labels() *labels.Helper[*compute.Disk] {
	return labels.For[*compute.Disk](s, func(r *compute.Disk) map[string]string {
		if r.Metadata.UserLabels == nil {
			return nil
		}
		return map[string]string(*r.Metadata.UserLabels)
	})
}

// Labels returns a label helper for HotswapDiskAttachments.
func (s *HotswapDiskAttachmentsService) Labels() *labels.Helper[*compute.HotswapDiskAttachment] {
	return labels.For[*compute.HotswapDiskAttachment](s, func(r *compute.HotswapDiskAttachment) map[string]string {
		if r.Metadata.UserLabels == nil {
			return nil
		}
		return map[string]string(*r.Metadata.UserLabels)
	})
}

// Labels returns a label helper for PlacementGroups.
func (s *PlacementGroupsService) Labels() *labels.Helper[*compute.PlacementGroup] {
	return labels.For[*compute.PlacementGroup](s, func(r *compute.PlacementGroup) map[string]string {
		if r.Metadata.UserLabels == nil {
			return nil
		}
		return map[string]string(*r.Metadata.UserLabels)
	})
}

// Labels returns a label helper for VirtualMachines.
func (s *VirtualMachinesService) Labels() *labels.Helper[*compute.VirtualMachine] {
	return labels.For[*compute.VirtualMachine](s, func(r *compute.VirtualMachine) map[string]string {
		if r.Metadata.UserLabels == nil {
			return nil
		}
		return map[string]string(*r.Metadata.UserLabels)
	})
}
