// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 evroc

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package compute

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/compute"
)

// PlacementGroupsService provides operations for PlacementGroups
type PlacementGroupsService struct {
	client *Client
}

// Create creates a PlacementGroup using project/region from config
func (s *PlacementGroupsService) Create(ctx context.Context, request *compute.PlacementGroupRequest) (*compute.PlacementGroup, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourcePlacementGroups)
	return rest.CreateResource[*compute.PlacementGroup](ctx, s.client.rest, path, request)
}

// Delete deletes a PlacementGroup using project/region from config
func (s *PlacementGroupsService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourcePlacementGroups,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a PlacementGroup by name using project/region from config
func (s *PlacementGroupsService) Get(ctx context.Context, name string) (*compute.PlacementGroup, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourcePlacementGroups,
		name)
	return rest.GetResource[*compute.PlacementGroup](ctx, s.client.rest, path)
}

// List retrieves all PlacementGroups using project/region from config with optional filters
func (s *PlacementGroupsService) List(ctx context.Context, filters ...rest.ListFilter) (*PlacementGroupList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourcePlacementGroups)
	return rest.ListWithFilters[*PlacementGroupList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a PlacementGroup using project/region from config
func (s *PlacementGroupsService) Patch(ctx context.Context, name string, patch interface{}) (*compute.PlacementGroup, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourcePlacementGroups,
		name)
	return rest.PatchResource[*compute.PlacementGroup](ctx, s.client.rest, path, patch)
}

// Update updates a PlacementGroup using project/region from config
func (s *PlacementGroupsService) Update(ctx context.Context, name string, resource *compute.PlacementGroup) (*compute.PlacementGroup, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourcePlacementGroups,
		name)
	return rest.UpdateResource[*compute.PlacementGroup](ctx, s.client.rest, path, resource)
}
