// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package compute

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/compute"
)

// SnapshotsService provides operations for Snapshots
type SnapshotsService struct {
	client *Client
}

// Create creates a Snapshot using project/region from config.
func (s *SnapshotsService) Create(ctx context.Context, request *compute.SnapshotRequest) (*compute.Snapshot, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceSnapshots)
	return rest.CreateResource[*compute.Snapshot](ctx, s.client.rest, path, request)
}

// Delete deletes a Snapshot using project/region from config
func (s *SnapshotsService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceSnapshots,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a Snapshot by name using project/region from config
func (s *SnapshotsService) Get(ctx context.Context, name string) (*compute.Snapshot, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceSnapshots,
		name)
	return rest.GetResource[*compute.Snapshot](ctx, s.client.rest, path)
}

// List retrieves all Snapshots using project/region from config with optional filters
func (s *SnapshotsService) List(ctx context.Context, filters ...rest.ListFilter) (*SnapshotList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceSnapshots)
	return rest.ListWithFilters[*SnapshotList](ctx, s.client.rest, path, filters...)
}
