// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 evroc

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package compute

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/compute"
)

// VirtualMachinesService provides operations for VirtualMachines
type VirtualMachinesService struct {
	client *Client
}

// Create creates a VirtualMachine using project/region from config
func (s *VirtualMachinesService) Create(ctx context.Context, request *compute.VirtualMachineRequest) (*compute.VirtualMachine, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceVirtualMachines)
	return rest.CreateResource[*compute.VirtualMachine](ctx, s.client.rest, path, request)
}

// Delete deletes a VirtualMachine using project/region from config
func (s *VirtualMachinesService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceVirtualMachines,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a VirtualMachine by name using project/region from config
func (s *VirtualMachinesService) Get(ctx context.Context, name string) (*compute.VirtualMachine, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceVirtualMachines,
		name)
	return rest.GetResource[*compute.VirtualMachine](ctx, s.client.rest, path)
}

// List retrieves all VirtualMachines using project/region from config with optional filters
func (s *VirtualMachinesService) List(ctx context.Context, filters ...rest.ListFilter) (*VirtualMachineList, error) {
	path := s.client.path.CollectionPath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceVirtualMachines)
	return rest.ListWithFilters[*VirtualMachineList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a VirtualMachine using project/region from config
func (s *VirtualMachinesService) Patch(ctx context.Context, name string, patch interface{}) (*compute.VirtualMachine, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceVirtualMachines,
		name)
	return rest.PatchResource[*compute.VirtualMachine](ctx, s.client.rest, path, patch)
}

// Update updates a VirtualMachine using project/region from config
func (s *VirtualMachinesService) Update(ctx context.Context, name string, resource *compute.VirtualMachine) (*compute.VirtualMachine, error) {
	path := s.client.path.ResourcePath(
		s.client.parent.DefaultProject(),
		s.client.parent.DefaultRegion(),
		resourceVirtualMachines,
		name)
	return rest.UpdateResource[*compute.VirtualMachine](ctx, s.client.rest, path, resource)
}
