// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0
//
// Package think provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package think

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for InstanceStatusPhase.
const (
	Creating InstanceStatusPhase = "Creating"
	Deleted  InstanceStatusPhase = "Deleted"
	Failed   InstanceStatusPhase = "Failed"
	Pending  InstanceStatusPhase = "Pending"
	Running  InstanceStatusPhase = "Running"
	Stopped  InstanceStatusPhase = "Stopped"
)

// Defines values for ModelSpecCapabilities.
const (
	ModelSpecCapabilitiesChat          ModelSpecCapabilities = "chat"
	ModelSpecCapabilitiesCode          ModelSpecCapabilities = "code"
	ModelSpecCapabilitiesEmbedding     ModelSpecCapabilities = "embedding"
	ModelSpecCapabilitiesTranscription ModelSpecCapabilities = "transcription"
	ModelSpecCapabilitiesVision        ModelSpecCapabilities = "vision"
)

// Defines values for SharedmodelSpecCapabilities.
const (
	SharedmodelSpecCapabilitiesChat          SharedmodelSpecCapabilities = "chat"
	SharedmodelSpecCapabilitiesCode          SharedmodelSpecCapabilities = "code"
	SharedmodelSpecCapabilitiesEmbedding     SharedmodelSpecCapabilities = "embedding"
	SharedmodelSpecCapabilitiesTranscription SharedmodelSpecCapabilities = "transcription"
	SharedmodelSpecCapabilitiesVision        SharedmodelSpecCapabilities = "vision"
)

// Apikey defines model for Apikey.
type Apikey struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global project-scoped resources.
	Metadata GlobalProjectMetadataResponse `json:"metadata"`
	Spec     ApikeySpec                    `json:"spec"`
	Status   ApikeyStatus                  `json:"status"`
}

// ApikeyList defines model for ApikeyList.
type ApikeyList struct {
	Items *[]Apikey `json:"items,omitempty"`
}

// ApikeyRequest defines model for ApikeyRequest.
type ApikeyRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global, project-scoped resource
	Metadata GlobalProjectMetadataRequest `json:"metadata"`
	Spec     ApikeySpec                   `json:"spec"`
}

// ApikeySpec defines model for ApikeySpec.
type ApikeySpec struct {
	// ExpiryTimestamp Timestamp at which this API key should expire.
	ExpiryTimestamp *time.Time `json:"expiryTimestamp,omitempty"`
}

// ApikeyStatus defines model for ApikeyStatus.
type ApikeyStatus struct {
	// Token The full API key secret. This will ONLY be returned when the API key is first created.
	Token *string `json:"token,omitempty"`

	// TokenPrefix A short prefix of the API key secret, as a mnemonic. Always returned.
	TokenPrefix *string `json:"tokenPrefix,omitempty"`
}

// BaseMetadataResponse Common metadata fields for all resource responses.
type BaseMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to  determine when objects have changed. Any reconciliation, or system-driven status change,  can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`
}

// Error Standard error response sent by all endpoints on failure.
type Error struct {
	// Debug Additional human-readable diagnostic information in English. This content is safe to surface to end users. MUST NOT be used for programmatic logic. The content may evolve at any time and is not stable.
	Debug *string `json:"debug,omitempty"`

	// Reason Stable, textual error code. This MUST be used by clients for programmatic handling. Examples include: FieldValueInvalid, Unauthorized, Forbidden.
	Reason string `json:"reason"`
}

// GlobalMetadataRequest Standard metadata for global resources.
type GlobalMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalMetadataResponse defines model for GlobalMetadataResponse.
type GlobalMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to  determine when objects have changed. Any reconciliation, or system-driven status change,  can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalOrgMetadataRequest defines model for GlobalOrgMetadataRequest.
type GlobalOrgMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Organization Organization associated with the resource.
	Organization *string `json:"organization,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalProjectMetadataRequest defines model for GlobalProjectMetadataRequest.
type GlobalProjectMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Project Project to which this resource belongs.
	Project *string `json:"project,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// GlobalProjectMetadataResponse defines model for GlobalProjectMetadataResponse.
type GlobalProjectMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Organization Organization associated with the resource.
	Organization *string `json:"organization,omitempty"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to  determine when objects have changed. Any reconciliation, or system-driven status change,  can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// Instance defines model for Instance.
type Instance struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional project-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     InstanceSpec             `json:"spec"`
	Status   InstanceStatus           `json:"status"`
}

// InstanceList defines model for InstanceList.
type InstanceList struct {
	Items *[]Instance `json:"items,omitempty"`
}

// InstanceRequest defines model for InstanceRequest.
type InstanceRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`
	Spec     InstanceSpec            `json:"spec"`
}

// InstanceSpec defines model for InstanceSpec.
type InstanceSpec struct {
	// Model The model to start. This should be the metadata.name of a Model object.
	Model string `json:"model"`

	// Size The instance size to use. This should be the metadata.name of a Size object. If omitted, the Model.Spec.DefaultSize is used.
	Size *string `json:"size,omitempty"`

	// Stopped If true, the instance is created but no actual resources are allocated. The instance is not usable until started.
	Stopped *bool `json:"stopped,omitempty"`
}

// InstanceStatus defines model for InstanceStatus.
type InstanceStatus struct {
	// Endpoint The OpenAI-compatible endpoint on which this model is served.
	Endpoint *string `json:"endpoint,omitempty"`

	// LastError The last error message from the model, if any.
	LastError *string `json:"lastError,omitempty"`

	// Message The last status message from the model, if any.
	Message *string `json:"message,omitempty"`

	// Phase The current lifecycle phase of this model.
	Phase *InstanceStatusPhase `json:"phase,omitempty"`

	// Token The API token needed to access the serving endpoint for this model.
	Token *string `json:"token,omitempty"`
}

// InstanceStatusPhase The current lifecycle phase of this model.
type InstanceStatusPhase string

// Model defines model for Model.
type Model struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global resources.
	Metadata GlobalMetadataResponse `json:"metadata"`
	Spec     ModelSpec              `json:"spec"`
	Status   ModelStatus            `json:"status"`
}

// ModelList defines model for ModelList.
type ModelList struct {
	Items *[]Model `json:"items,omitempty"`
}

// ModelSpec defines model for ModelSpec.
type ModelSpec struct {
	// Capabilities Array of capabilities this model has.
	Capabilities *[]ModelSpecCapabilities `json:"capabilities,omitempty"`

	// DefaultSize Suggested instance size for this model (as the metadata.name of a Size object). The model may not start successfully on a smaller instance.
	DefaultSize interface{} `json:"defaultSize,omitempty"`

	// Description Longer description of the model.
	Description *string `json:"description,omitempty"`

	// Handle The model handle, as used by HuggingFace or similar.
	Handle *string `json:"handle,omitempty"`

	// InstanceType Platform on which this model runs.
	InstanceType *string `json:"instanceType,omitempty"`

	// License Name of the license which applies to this model.
	License *string `json:"license,omitempty"`

	// LicenseUrl Link to the full model license, if any.
	LicenseUrl *string `json:"licenseUrl,omitempty"`
}

// ModelSpecCapabilities defines model for ModelSpec.Capabilities.
type ModelSpecCapabilities string

// ModelStatus defines model for ModelStatus.
type ModelStatus = map[string]interface{}

// RegionalMetadataRequest defines model for RegionalMetadataRequest.
type RegionalMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Project Project identifier
	Project *string `json:"project,omitempty"`

	// Region Region identifier
	Region *string `json:"region,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// RegionalMetadataResponse defines model for RegionalMetadataResponse.
type RegionalMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Project Project identifier
	Project *string `json:"project,omitempty"`

	// Region Region identifier
	Region *string `json:"region,omitempty"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to  determine when objects have changed. Any reconciliation, or system-driven status change,  can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// SystemLabels Map of string keys and string values owned and managed by evroc, and automatically set by the system. SystemLabels are read-only and can be referenced by label selectors.
	SystemLabels *SystemLabels `json:"systemLabels,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// Sharedmodel defines model for Sharedmodel.
type Sharedmodel struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global resources.
	Metadata GlobalMetadataResponse `json:"metadata"`
	Spec     SharedmodelSpec        `json:"spec"`
	Status   SharedmodelStatus      `json:"status"`
}

// SharedmodelList defines model for SharedmodelList.
type SharedmodelList struct {
	Items *[]Sharedmodel `json:"items,omitempty"`
}

// SharedmodelSpec defines model for SharedmodelSpec.
type SharedmodelSpec struct {
	// Aliases Model aliases which should be used as the model: value when calling the shared model service.
	Aliases *[]string `json:"aliases,omitempty"`

	// Capabilities Array of capabilities this model has.
	Capabilities *[]SharedmodelSpecCapabilities `json:"capabilities,omitempty"`

	// Description Description of this shared model.
	Description *string `json:"description,omitempty"`

	// License Name of the license which applies to this model.
	License *string `json:"license,omitempty"`

	// LicenseUrl Link to the full model license, if any.
	LicenseUrl *string `json:"licenseUrl,omitempty"`
}

// SharedmodelSpecCapabilities defines model for SharedmodelSpec.Capabilities.
type SharedmodelSpecCapabilities string

// SharedmodelStatus defines model for SharedmodelStatus.
type SharedmodelStatus = map[string]interface{}

// Size defines model for Size.
type Size struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for global resources.
	Metadata GlobalMetadataResponse `json:"metadata"`
	Spec     SizeSpec               `json:"spec"`
	Status   SizeStatus             `json:"status"`
}

// SizeList defines model for SizeList.
type SizeList struct {
	Items *[]Size `json:"items,omitempty"`
}

// SizeSpec defines model for SizeSpec.
type SizeSpec struct {
	// Description Description of this instance size.
	Description *string `json:"description,omitempty"`
}

// SizeStatus defines model for SizeStatus.
type SizeStatus = map[string]interface{}

// SystemLabels Map of string keys and string values owned and managed by evroc, and automatically set by the system. SystemLabels are read-only and can be referenced by label selectors.
type SystemLabels map[string]string

// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
type UserLabels map[string]string

// ApiVersion Identifies the version of the API schema used for this resource.
// It should be the same than the version in the path, otherwise the request will be rejected.
type ApiVersion = string

// Kind Specifies the type of resource this object represents.
type Kind = string

// PostThinkV1beta2ProjectsProjectIDApiKeysJSONRequestBody defines body for PostThinkV1beta2ProjectsProjectIDApiKeys for application/json ContentType.
type PostThinkV1beta2ProjectsProjectIDApiKeysJSONRequestBody = ApikeyRequest

// PostThinkV1beta2ProjectsProjectIDRegionsRegionIDInstancesJSONRequestBody defines body for PostThinkV1beta2ProjectsProjectIDRegionsRegionIDInstances for application/json ContentType.
type PostThinkV1beta2ProjectsProjectIDRegionsRegionIDInstancesJSONRequestBody = InstanceRequest

// PatchThinkV1beta2ProjectsProjectIDRegionsRegionIDInstancesInstanceIDJSONRequestBody defines body for PatchThinkV1beta2ProjectsProjectIDRegionsRegionIDInstancesInstanceID for application/json ContentType.
type PatchThinkV1beta2ProjectsProjectIDRegionsRegionIDInstancesInstanceIDJSONRequestBody = InstanceRequest
