// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package iam

import (
	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/metrics"
	"github.com/evroc-oss/evroc-go-sdk/types/iam"
)

const (
	apiVersion = "v1beta1"

	// Resource type constants
	resourceOrganizations             = "organizations"
	resourceProjects                  = "projects"
	resourceRoleBindings              = "roleBindings"
	resourceServiceAccountCredentials = "serviceAccountCredentials"
	resourceServiceAccounts           = "serviceAccounts"
)

// ContextProvider provides access to context configuration
type ContextProvider interface {
	DefaultProject() string
	DefaultRegion() string
	DefaultOrganization() string
}

// Client provides access to evroc iam API
type Client struct {
	rest    *rest.Client
	path    rest.ServicePath
	parent  ContextProvider
	metrics *metrics.Manager
}

// List response types
type (
	OrganizationList struct {
		Items []iam.Organization `json:"items,omitempty"`
	}

	ProjectList struct {
		Items []iam.Project `json:"items,omitempty"`
	}

	RoleBindingList = iam.RolebindingList

	OrgRoleBindingList = iam.OrgListResponse

	ServiceaccountcredentialList struct {
		Items []iam.Serviceaccountcredential `json:"items,omitempty"`
	}

	ServiceaccountList struct {
		Items []iam.Serviceaccount `json:"items,omitempty"`
	}
)

// NewClient creates a new iam API client with a parent context provider
func NewClient(restClient *rest.Client, parent ContextProvider) *Client {
	return &Client{
		rest:   restClient,
		path:   rest.NewServicePath("iam", apiVersion),
		parent: parent,
	}
}

// Organizations returns the Organizations service
func (c *Client) Organizations() *OrganizationsService {
	return &OrganizationsService{client: c}
}

// Projects returns the Projects service
func (c *Client) Projects() *ProjectsService {
	return &ProjectsService{client: c}
}

// RoleBindings returns the RoleBindings service
func (c *Client) RoleBindings() *RoleBindingsService {
	return &RoleBindingsService{client: c}
}

// ServiceAccountCredentials returns the ServiceAccountCredentials service scoped to the given parent ServiceAccounts.
func (c *Client) ServiceAccountCredentials(parentID string) *ServiceAccountCredentialsService {
	return &ServiceAccountCredentialsService{client: c, parentID: parentID}
}

// ServiceAccounts returns the ServiceAccounts service
func (c *Client) ServiceAccounts() *ServiceAccountsService {
	return &ServiceAccountsService{client: c}
}
