// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 evroc

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package iam

import (
	"github.com/evroc-oss/evroc-go-sdk/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/iam"
)

const (
	apiVersion = "v1alpha4"

	// Resource type constants
	resourcePermissionSets = "permissionSets"
	resourceProjects       = "projects"
)

// ContextProvider provides access to context configuration
type ContextProvider interface {
	DefaultProject() string
	DefaultRegion() string
	DefaultOrganization() string
}

// Client provides access to evroc iam API
type Client struct {
	rest   *rest.Client
	path   rest.ServicePath
	parent ContextProvider
}

// List response types
type (
	PermissionSetList struct {
		Items []iam.PermissionSet `json:"items,omitempty"`
	}

	ProjectList struct {
		Items []iam.Project `json:"items,omitempty"`
	}
)

// NewClient creates a new iam API client
func NewClient(restClient *rest.Client) *Client {
	return &Client{
		rest: restClient,
		path: rest.NewServicePath("iam", apiVersion),
	}
}

// NewClientWithParent creates a new iam API client with a parent context provider
func NewClientWithParent(restClient *rest.Client, parent ContextProvider) *Client {
	return &Client{
		rest:   restClient,
		path:   rest.NewServicePath("iam", apiVersion),
		parent: parent,
	}
}

// PermissionSets returns the PermissionSets service
func (c *Client) PermissionSets() *PermissionSetsService {
	return &PermissionSetsService{client: c}
}

// Projects returns the Projects service
func (c *Client) Projects() *ProjectsService {
	return &ProjectsService{client: c}
}
