// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 evroc

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package iam

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/iam"
)

// OrganizationsService provides operations for Organizations
type OrganizationsService struct {
	client *Client
}

// Get retrieves a Organization by name
func (s *OrganizationsService) Get(ctx context.Context, name string) (*iam.Organization, error) {
	path := s.client.path.GlobalResourcePath(resourceOrganizations, name)
	return rest.GetResource[*iam.Organization](ctx, s.client.rest, path)
}

// List retrieves all Organizations with optional filters
func (s *OrganizationsService) List(ctx context.Context, filters ...rest.ListFilter) (*OrganizationList, error) {
	path := s.client.path.GlobalCollectionPath(resourceOrganizations)
	return rest.ListWithFilters[*OrganizationList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a Organization
func (s *OrganizationsService) Patch(ctx context.Context, name string, patch interface{}) (*iam.Organization, error) {
	path := s.client.path.GlobalResourcePath(resourceOrganizations, name)
	return rest.PatchResource[*iam.Organization](ctx, s.client.rest, path, patch)
}
