// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package iam

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/iam"
)

// PermissionSetsService provides operations for PermissionSets
type PermissionSetsService struct {
	client *Client
}

// Create creates a PermissionSet using project from config
func (s *PermissionSetsService) Create(ctx context.Context, request *iam.PermissionSetRequest) (*iam.PermissionSet, error) {
	path := s.client.path.ProjectCollectionPath(
		s.client.parent.DefaultProject(),
		resourcePermissionSets)
	return rest.CreateResource[*iam.PermissionSet](ctx, s.client.rest, path, request)
}

// Delete deletes a PermissionSet using project from config
func (s *PermissionSetsService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ProjectResourcePath(
		s.client.parent.DefaultProject(),
		resourcePermissionSets,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a PermissionSet by name using project from config
func (s *PermissionSetsService) Get(ctx context.Context, name string) (*iam.PermissionSet, error) {
	path := s.client.path.ProjectResourcePath(
		s.client.parent.DefaultProject(),
		resourcePermissionSets,
		name)
	return rest.GetResource[*iam.PermissionSet](ctx, s.client.rest, path)
}

// List retrieves all PermissionSets using project from config with optional filters
func (s *PermissionSetsService) List(ctx context.Context, filters ...rest.ListFilter) (*PermissionSetList, error) {
	path := s.client.path.ProjectCollectionPath(
		s.client.parent.DefaultProject(),
		resourcePermissionSets)
	return rest.ListWithFilters[*PermissionSetList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a PermissionSet using project from config
func (s *PermissionSetsService) Patch(ctx context.Context, name string, patch interface{}) (*iam.PermissionSet, error) {
	path := s.client.path.ProjectResourcePath(
		s.client.parent.DefaultProject(),
		resourcePermissionSets,
		name)
	return rest.PatchResource[*iam.PermissionSet](ctx, s.client.rest, path, patch)
}
