// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 evroc

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package iam

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/iam"
)

// ProjectsService provides operations for Projects
type ProjectsService struct {
	client *Client
}

// Create creates a new Project
func (s *ProjectsService) Create(ctx context.Context, request *iam.ProjectRequest) (*iam.Project, error) {
	path := s.client.path.GlobalCollectionPath(resourceProjects)
	return rest.CreateResource[*iam.Project](ctx, s.client.rest, path, request)
}

// Delete deletes a Project
func (s *ProjectsService) Delete(ctx context.Context, name string) error {
	path := s.client.path.GlobalResourcePath(resourceProjects, name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a Project by name
func (s *ProjectsService) Get(ctx context.Context, name string) (*iam.Project, error) {
	path := s.client.path.GlobalResourcePath(resourceProjects, name)
	return rest.GetResource[*iam.Project](ctx, s.client.rest, path)
}

// List retrieves all Projects with optional filters
func (s *ProjectsService) List(ctx context.Context, filters ...rest.ListFilter) (*ProjectList, error) {
	path := s.client.path.GlobalCollectionPath(resourceProjects)
	return rest.ListWithFilters[*ProjectList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a Project
func (s *ProjectsService) Patch(ctx context.Context, name string, patch interface{}) (*iam.Project, error) {
	path := s.client.path.GlobalResourcePath(resourceProjects, name)
	return rest.PatchResource[*iam.Project](ctx, s.client.rest, path, patch)
}

// Update updates a Project
func (s *ProjectsService) Update(ctx context.Context, name string, resource *iam.Project) (*iam.Project, error) {
	path := s.client.path.GlobalResourcePath(resourceProjects, name)
	return rest.UpdateResource[*iam.Project](ctx, s.client.rest, path, resource)
}
