// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package iam

import (
	"context"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/iam"
)

// ServiceAccountsService provides operations for ServiceAccounts
type ServiceAccountsService struct {
	client *Client
}

// Create creates a Serviceaccount using project from config
func (s *ServiceAccountsService) Create(ctx context.Context, request *iam.ServiceaccountRequest) (*iam.Serviceaccount, error) {
	path := s.client.path.ProjectCollectionPath(
		s.client.parent.DefaultProject(),
		resourceServiceAccounts)
	return rest.CreateResource[*iam.Serviceaccount](ctx, s.client.rest, path, request)
}

// Delete deletes a Serviceaccount using project from config
func (s *ServiceAccountsService) Delete(ctx context.Context, name string) error {
	path := s.client.path.ProjectResourcePath(
		s.client.parent.DefaultProject(),
		resourceServiceAccounts,
		name)
	return rest.DeleteResource(ctx, s.client.rest, path)
}

// Get retrieves a Serviceaccount by name using project from config
func (s *ServiceAccountsService) Get(ctx context.Context, name string) (*iam.Serviceaccount, error) {
	path := s.client.path.ProjectResourcePath(
		s.client.parent.DefaultProject(),
		resourceServiceAccounts,
		name)
	return rest.GetResource[*iam.Serviceaccount](ctx, s.client.rest, path)
}

// List retrieves all Serviceaccounts using project from config with optional filters
func (s *ServiceAccountsService) List(ctx context.Context, filters ...rest.ListFilter) (*ServiceaccountList, error) {
	path := s.client.path.ProjectCollectionPath(
		s.client.parent.DefaultProject(),
		resourceServiceAccounts)
	return rest.ListWithFilters[*ServiceaccountList](ctx, s.client.rest, path, filters...)
}

// Patch partially updates a Serviceaccount using project from config
func (s *ServiceAccountsService) Patch(ctx context.Context, name string, patch interface{}) (*iam.Serviceaccount, error) {
	path := s.client.path.ProjectResourcePath(
		s.client.parent.DefaultProject(),
		resourceServiceAccounts,
		name)
	return rest.PatchResource[*iam.Serviceaccount](ctx, s.client.rest, path, patch)
}
