// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate_services.go from services.yaml. DO NOT EDIT.

package iam

import (
	"context"
	"path"

	"github.com/evroc-oss/evroc-go-sdk/internal/rest"
	"github.com/evroc-oss/evroc-go-sdk/types/iam"
)

// ServiceAccountCredentialsService provides operations for ServiceAccountCredentials
type ServiceAccountCredentialsService struct {
	client   *Client
	parentID string
}

func (s *ServiceAccountCredentialsService) collectionPath() string {
	return path.Join("/", "iam", apiVersion, "projects",
		s.client.parent.DefaultProject(),
		resourceServiceAccounts, s.parentID,
		resourceServiceAccountCredentials)
}

func (s *ServiceAccountCredentialsService) resourcePath(name string) string {
	return path.Join(s.collectionPath(), name)
}

// Create creates a Serviceaccountcredential under the parent ServiceAccounts
func (s *ServiceAccountCredentialsService) Create(ctx context.Context, request *iam.ServiceaccountcredentialRequest) (*iam.Serviceaccountcredential, error) {
	return rest.CreateResource[*iam.Serviceaccountcredential](ctx, s.client.rest, s.collectionPath(), request)
}

// Delete deletes a Serviceaccountcredential by name
func (s *ServiceAccountCredentialsService) Delete(ctx context.Context, name string) error {
	return rest.DeleteResource(ctx, s.client.rest, s.resourcePath(name))
}

// Get retrieves a Serviceaccountcredential by name
func (s *ServiceAccountCredentialsService) Get(ctx context.Context, name string) (*iam.Serviceaccountcredential, error) {
	return rest.GetResource[*iam.Serviceaccountcredential](ctx, s.client.rest, s.resourcePath(name))
}

// List retrieves all Serviceaccountcredentials for the parent ServiceAccounts with optional filters
func (s *ServiceAccountCredentialsService) List(ctx context.Context, filters ...rest.ListFilter) (*ServiceaccountcredentialList, error) {
	return rest.ListWithFilters[*ServiceaccountcredentialList](ctx, s.client.rest, s.collectionPath(), filters...)
}
