// Package storage provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package storage

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for BucketServiceAccountStatusConditionsItemStatus.
const (
	BucketServiceAccountStatusConditionsItemStatusFalse   BucketServiceAccountStatusConditionsItemStatus = "False"
	BucketServiceAccountStatusConditionsItemStatusTrue    BucketServiceAccountStatusConditionsItemStatus = "True"
	BucketServiceAccountStatusConditionsItemStatusUnknown BucketServiceAccountStatusConditionsItemStatus = "Unknown"
)

// Defines values for BucketSpecObjectRetentionMode.
const (
	Disabled  BucketSpecObjectRetentionMode = "Disabled"
	Locking   BucketSpecObjectRetentionMode = "Locking"
	Suspended BucketSpecObjectRetentionMode = "Suspended"
	Versioned BucketSpecObjectRetentionMode = "Versioned"
)

// Defines values for BucketSpecDefaultObjectLockingMode.
const (
	Immutable BucketSpecDefaultObjectLockingMode = "Immutable"
	Soft      BucketSpecDefaultObjectLockingMode = "Soft"
)

// Defines values for BucketStatusConditionsItemStatus.
const (
	BucketStatusConditionsItemStatusFalse   BucketStatusConditionsItemStatus = "False"
	BucketStatusConditionsItemStatusTrue    BucketStatusConditionsItemStatus = "True"
	BucketStatusConditionsItemStatusUnknown BucketStatusConditionsItemStatus = "Unknown"
)

// BaseMetadataResponse Common metadata fields for all resource responses.
type BaseMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`
}

// Bucket defines model for Bucket.
type Bucket struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	// For example: "VirtualMachine", or "Bucket".
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`

	// Spec BucketSpec defines the desired state of Bucket.
	Spec BucketSpec `json:"spec"`

	// Status BucketStatus defines the observed state of Bucket.
	Status BucketStatus `json:"status"`
}

// BucketList defines model for BucketList.
type BucketList struct {
	Items *[]Bucket `json:"items,omitempty"`
}

// BucketRequest defines model for BucketRequest.
type BucketRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	// For example: "VirtualMachine", or "Bucket".
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`

	// Spec BucketSpec defines the desired state of Bucket.
	Spec BucketSpec `json:"spec"`
}

// BucketServiceAccount defines model for BucketServiceAccount.
type BucketServiceAccount struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	// For example: "VirtualMachine", or "Bucket".
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`

	// Spec BucketServiceAccountSpec defines the desired state of BucketServiceAccount.
	Spec BucketServiceAccountSpec `json:"spec"`

	// Status BucketServiceAccountStatus defines the observed state of BucketServiceAccount.
	Status BucketServiceAccountStatus `json:"status"`
}

// BucketServiceAccountList defines model for BucketServiceAccountList.
type BucketServiceAccountList struct {
	Items *[]BucketServiceAccount `json:"items,omitempty"`
}

// BucketServiceAccountRequest defines model for BucketServiceAccountRequest.
type BucketServiceAccountRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	// For example: "VirtualMachine", or "Bucket".
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`

	// Spec BucketServiceAccountSpec defines the desired state of BucketServiceAccount.
	Spec BucketServiceAccountSpec `json:"spec"`
}

// BucketServiceAccountSpec BucketServiceAccountSpec defines the desired state of BucketServiceAccount.
type BucketServiceAccountSpec struct {
	// Buckets Buckets is a list of buckets that the service account has access to. Each
	// element in the list is the name of a bucket in the same project as the
	// BucketServiceAccount.
	Buckets *[]string `json:"buckets,omitempty"`
}

// BucketServiceAccountStatus BucketServiceAccountStatus defines the observed state of BucketServiceAccount.
type BucketServiceAccountStatus struct {
	// Conditions Conditions represents the state of the BucketServiceAccount over time.
	// Each condition follows the Kubernetes API conventions for a condition:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
	// Conditions ConditionsSet `json:"conditions,omitempty"`
	Conditions *[]BucketServiceAccountStatusConditionsItem `json:"conditions,omitempty"`

	// S3CredentialsSecretName S3CredentialsSecretName contains the name of the secret that was created to
	// connect to the S3 API. It contains an AWS_ACCESS_KEY_ID and an AWS_SECRET_ACCESS_KEY.
	S3CredentialsSecretName *string `json:"s3CredentialsSecretName,omitempty"`
}

// BucketServiceAccountStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type BucketServiceAccountStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status BucketServiceAccountStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// BucketServiceAccountStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type BucketServiceAccountStatusConditionsItemStatus string

// BucketSpec BucketSpec defines the desired state of Bucket.
type BucketSpec struct {
	// DefaultObjectLocking DefaultObjectLocking can be used when `ObjectRetentionMode` is set to "Locking". It controls
	// the default object lock behavior for objects stored in the bucket. The defaults can be overridden
	// on a per-object level.
	DefaultObjectLocking *BucketSpecDefaultObjectLocking `json:"defaultObjectLocking,omitempty"`

	// ObjectRetentionMode ObjectRetentionMode controls how object retention is managed. If not explicitly set, the
	// default is `Disabled`, meaning that no version history is kept for objects, and objects
	// can not be locked. If the retention mode is ever set to some value other than `Disabled`,
	// it can never be set to `Disabled` again. If the mode is set to `Locking`, object locking
	// features are enabled. Object locking means that objects can be locked for a duration of time
	// from being modified and/or deleted. When the `Locking` mode is set, the `DefaultObjectLocking`
	// property can be used to configure default locking behavior.
	// Can be set to one of: [Disabled, Suspended, Versioned, Locking].
	ObjectRetentionMode *BucketSpecObjectRetentionMode `json:"objectRetentionMode,omitempty"`
}

// BucketSpecObjectRetentionMode ObjectRetentionMode controls how object retention is managed. If not explicitly set, the
// default is `Disabled`, meaning that no version history is kept for objects, and objects
// can not be locked. If the retention mode is ever set to some value other than `Disabled`,
// it can never be set to `Disabled` again. If the mode is set to `Locking`, object locking
// features are enabled. Object locking means that objects can be locked for a duration of time
// from being modified and/or deleted. When the `Locking` mode is set, the `DefaultObjectLocking`
// property can be used to configure default locking behavior.
// Can be set to one of: [Disabled, Suspended, Versioned, Locking].
type BucketSpecObjectRetentionMode string

// BucketSpecDefaultObjectLocking DefaultObjectLocking can be used when `ObjectRetentionMode` is set to "Locking". It controls
// the default object lock behavior for objects stored in the bucket. The defaults can be overridden
// on a per-object level.
type BucketSpecDefaultObjectLocking struct {
	// DurationDays DurationDays specifies the default duration (in days) that objects are locked,
	// when object locking is enabled and no other value is explicitly provided.
	DurationDays int32 `json:"durationDays"`

	// Mode Mode defines what type of protection is applied on objects by default
	// when object locking is enabled.
	Mode BucketSpecDefaultObjectLockingMode `json:"mode"`
}

// BucketSpecDefaultObjectLockingMode Mode defines what type of protection is applied on objects by default
// when object locking is enabled.
type BucketSpecDefaultObjectLockingMode string

// BucketStatus BucketStatus defines the observed state of Bucket.
type BucketStatus struct {
	// Conditions Conditions represents the state of the Bucket over time.
	// Each condition follows the Kubernetes API conventions for a condition:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
	// Conditions ConditionsSet `json:"conditions,omitempty"`
	Conditions *[]BucketStatusConditionsItem `json:"conditions,omitempty"`
	LastError  *string                       `json:"lastError,omitempty"`
}

// BucketStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type BucketStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status BucketStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// BucketStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type BucketStatusConditionsItemStatus string

// Bucketserviceaccountsecret defines model for Bucketserviceaccountsecret.
type Bucketserviceaccountsecret struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Data Contains S3-compatible secret credentials for a BucketServiceAccount.
	// WARNING: these are sensitive credentials! Do not share or expose them unnecessarily.
	Data Data `json:"data"`

	// Kind Specifies the type of resource this object represents.
	// For example: "VirtualMachine", or "Bucket".
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
}

// Error Standard error response sent by all endpoints on failure.
type Error struct {
	// Debug Additional human-readable diagnostic information in English. This content is safe to surface to end users. MUST NOT be used for programmatic logic. The content may evolve at any time and is not stable.
	Debug *string `json:"debug,omitempty"`

	// Reason Stable, textual error code. This MUST be used by clients for programmatic handling. Examples include: FieldValueInvalid, Unauthorized, Forbidden.
	Reason string `json:"reason"`
}

// GlobalMetadataRequest Standard metadata for global resources.
type GlobalMetadataRequest struct {
	// Name Unique identifier for the resource within its namespace. Immutable.
	Name *string `json:"name,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// RegionalMetadataRequest defines model for RegionalMetadataRequest.
type RegionalMetadataRequest struct {
	// Name Unique identifier for the resource within its namespace. Immutable.
	Name *string `json:"name,omitempty"`

	// Project Project identifier
	Project *string `json:"project,omitempty"`

	// Region Region identifier
	Region *string `json:"region,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// RegionalMetadataResponse defines model for RegionalMetadataResponse.
type RegionalMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Name Unique identifier for the resource within its namespace. Immutable.
	Name *string `json:"name,omitempty"`

	// Project Project identifier
	Project *string `json:"project,omitempty"`

	// Region Region identifier
	Region *string `json:"region,omitempty"`

	// SystemLabels Map of string keys and string values owned and managed by evroc, and automatically set by the system. SystemLabels are read-only and can be referenced by label selectors.
	SystemLabels *SystemLabels `json:"systemLabels,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// SystemLabels Map of string keys and string values owned and managed by evroc, and automatically set by the system. SystemLabels are read-only and can be referenced by label selectors.
type SystemLabels map[string]string

// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
type UserLabels map[string]string

// ApiVersion Identifies the version of the API schema used for this resource.
// It should be the same than the version in the path, otherwise the request will be rejected.
type ApiVersion = string

// Data Contains S3-compatible secret credentials for a BucketServiceAccount.
// WARNING: these are sensitive credentials! Do not share or expose them unnecessarily.
type Data struct {
	// AccessKeyID Access key ID for the associated BucketServiceAccount.
	AccessKeyID *string `json:"accessKeyID,omitempty"`

	// SecretAccessKey Secret access key for the associated BucketServiceAccount.
	SecretAccessKey *string `json:"secretAccessKey,omitempty"`
}

// Kind Specifies the type of resource this object represents.
// For example: "VirtualMachine", or "Bucket".
type Kind = string

// PostStorageV1ProjectsProjectNameRegionsRegionNameBucketServiceAccountsParams defines parameters for PostStorageV1ProjectsProjectNameRegionsRegionNameBucketServiceAccounts.
type PostStorageV1ProjectsProjectNameRegionsRegionNameBucketServiceAccountsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetStorageV1ProjectsProjectNameRegionsRegionNameBucketsParams defines parameters for GetStorageV1ProjectsProjectNameRegionsRegionNameBuckets.
type GetStorageV1ProjectsProjectNameRegionsRegionNameBucketsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// PostStorageV1ProjectsProjectNameRegionsRegionNameBucketServiceAccountsJSONRequestBody defines body for PostStorageV1ProjectsProjectNameRegionsRegionNameBucketServiceAccounts for application/json ContentType.
type PostStorageV1ProjectsProjectNameRegionsRegionNameBucketServiceAccountsJSONRequestBody = BucketServiceAccountRequest

// PatchStorageV1ProjectsProjectNameRegionsRegionNameBucketServiceAccountsBucketServiceAccountNameJSONRequestBody defines body for PatchStorageV1ProjectsProjectNameRegionsRegionNameBucketServiceAccountsBucketServiceAccountName for application/json ContentType.
type PatchStorageV1ProjectsProjectNameRegionsRegionNameBucketServiceAccountsBucketServiceAccountNameJSONRequestBody = BucketServiceAccountRequest

// PutStorageV1ProjectsProjectNameRegionsRegionNameBucketServiceAccountsBucketServiceAccountNameJSONRequestBody defines body for PutStorageV1ProjectsProjectNameRegionsRegionNameBucketServiceAccountsBucketServiceAccountName for application/json ContentType.
type PutStorageV1ProjectsProjectNameRegionsRegionNameBucketServiceAccountsBucketServiceAccountNameJSONRequestBody = BucketServiceAccountRequest

// PostStorageV1ProjectsProjectNameRegionsRegionNameBucketsJSONRequestBody defines body for PostStorageV1ProjectsProjectNameRegionsRegionNameBuckets for application/json ContentType.
type PostStorageV1ProjectsProjectNameRegionsRegionNameBucketsJSONRequestBody = BucketRequest

// PatchStorageV1ProjectsProjectNameRegionsRegionNameBucketsBucketNameJSONRequestBody defines body for PatchStorageV1ProjectsProjectNameRegionsRegionNameBucketsBucketName for application/json ContentType.
type PatchStorageV1ProjectsProjectNameRegionsRegionNameBucketsBucketNameJSONRequestBody = BucketRequest

// PutStorageV1ProjectsProjectNameRegionsRegionNameBucketsBucketNameJSONRequestBody defines body for PutStorageV1ProjectsProjectNameRegionsRegionNameBucketsBucketName for application/json ContentType.
type PutStorageV1ProjectsProjectNameRegionsRegionNameBucketsBucketNameJSONRequestBody = BucketRequest
