// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0
//
// Package compute provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package compute

import (
	"time"
)

// Defines values for CustomDiskImageSpecArchitecture.
const (
	CustomDiskImageSpecArchitectureAmd64 CustomDiskImageSpecArchitecture = "amd64"
)

// Defines values for CustomDiskImageSpecDefaultDiskSizeUnit.
const (
	CustomDiskImageSpecDefaultDiskSizeUnitGB CustomDiskImageSpecDefaultDiskSizeUnit = "GB"
	CustomDiskImageSpecDefaultDiskSizeUnitKB CustomDiskImageSpecDefaultDiskSizeUnit = "KB"
	CustomDiskImageSpecDefaultDiskSizeUnitMB CustomDiskImageSpecDefaultDiskSizeUnit = "MB"
	CustomDiskImageSpecDefaultDiskSizeUnitTB CustomDiskImageSpecDefaultDiskSizeUnit = "TB"
)

// Defines values for CustomDiskImageStatusConditionsItemStatus.
const (
	CustomDiskImageStatusConditionsItemStatusFalse   CustomDiskImageStatusConditionsItemStatus = "False"
	CustomDiskImageStatusConditionsItemStatusTrue    CustomDiskImageStatusConditionsItemStatus = "True"
	CustomDiskImageStatusConditionsItemStatusUnknown CustomDiskImageStatusConditionsItemStatus = "Unknown"
)

// CustomDiskImage defines model for CustomDiskImage.
type CustomDiskImage struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional project-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     CustomDiskImageSpec      `json:"spec"`
	Status   CustomDiskImageStatus    `json:"status"`
}

// CustomDiskImageList defines model for CustomDiskImageList.
type CustomDiskImageList struct {
	Items *[]CustomDiskImage `json:"items,omitempty"`
}

// CustomDiskImageRequest defines model for CustomDiskImageRequest.
type CustomDiskImageRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`
	Spec     CustomDiskImageSpec     `json:"spec"`
}

// CustomDiskImageSpec defines model for CustomDiskImageSpec.
type CustomDiskImageSpec struct {
	Architecture    CustomDiskImageSpecArchitecture    `json:"architecture"`
	DefaultDiskSize CustomDiskImageSpecDefaultDiskSize `json:"defaultDiskSize"`

	// Description Optional image description for user's own information.
	Description *string `json:"description,omitempty"`

	// ImageVersion Optional image version for user's own information.
	ImageVersion *string `json:"imageVersion,omitempty"`

	// OsName Optional OS name for user's own information.
	OsName *string `json:"osName,omitempty"`

	// OsVersion Optional OS version for user's own information.
	OsVersion *string                   `json:"osVersion,omitempty"`
	Source    CustomDiskImageSpecSource `json:"source"`
}

// CustomDiskImageSpecArchitecture defines model for CustomDiskImageSpec.Architecture.
type CustomDiskImageSpecArchitecture string

// CustomDiskImageSpecDefaultDiskSize defines model for CustomDiskImageSpecDefaultDiskSize.
type CustomDiskImageSpecDefaultDiskSize struct {
	Amount int32                                  `json:"amount"`
	Unit   CustomDiskImageSpecDefaultDiskSizeUnit `json:"unit"`
}

// CustomDiskImageSpecDefaultDiskSizeUnit defines model for CustomDiskImageSpecDefaultDiskSize.Unit.
type CustomDiskImageSpecDefaultDiskSizeUnit string

// CustomDiskImageSpecSource defines model for CustomDiskImageSpecSource.
type CustomDiskImageSpecSource struct {
	// BucketRef The bucket containing the source image.
	BucketRef string `json:"bucketRef"`

	// Path The path of the source image within the bucket. Must be in '.qcow2', '.vhdx' or '.raw' format.
	Path string `json:"path"`

	// ServiceAccountRef The service account to access the bucket.
	ServiceAccountRef string `json:"serviceAccountRef"`

	// Version Optional. Latest version used if not specified.
	Version *string `json:"version,omitempty"`
}

// CustomDiskImageStatus defines model for CustomDiskImageStatus.
type CustomDiskImageStatus struct {
	// Conditions ConditionsSet is an abstraction over []metav1.Condition that handles the
	// removal of the previous occurrence of the conditionType when marking a condition.
	Conditions *[]CustomDiskImageStatusConditionsItem `json:"conditions,omitempty"`
}

// CustomDiskImageStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type CustomDiskImageStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status CustomDiskImageStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// CustomDiskImageStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type CustomDiskImageStatusConditionsItemStatus string

// GetComputeV1beta2ProjectsProjectIDRegionsRegionNameCustomDiskImagesParams defines parameters for GetComputeV1beta2ProjectsProjectIDRegionsRegionNameCustomDiskImages.
type GetComputeV1beta2ProjectsProjectIDRegionsRegionNameCustomDiskImagesParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// PostComputeV1beta2ProjectsProjectIDRegionsRegionNameCustomDiskImagesJSONRequestBody defines body for PostComputeV1beta2ProjectsProjectIDRegionsRegionNameCustomDiskImages for application/json ContentType.
type PostComputeV1beta2ProjectsProjectIDRegionsRegionNameCustomDiskImagesJSONRequestBody = CustomDiskImageRequest

// PatchComputeV1beta2ProjectsProjectIDRegionsRegionNameCustomDiskImagesCustomDiskImageIDJSONRequestBody defines body for PatchComputeV1beta2ProjectsProjectIDRegionsRegionNameCustomDiskImagesCustomDiskImageID for application/json ContentType.
type PatchComputeV1beta2ProjectsProjectIDRegionsRegionNameCustomDiskImagesCustomDiskImageIDJSONRequestBody = CustomDiskImageRequest
