// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0
//
// Package compute provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package compute

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for DiskSpecDiskSizeUnit.
const (
	DiskSpecDiskSizeUnitGB DiskSpecDiskSizeUnit = "GB"
	DiskSpecDiskSizeUnitKB DiskSpecDiskSizeUnit = "KB"
	DiskSpecDiskSizeUnitMB DiskSpecDiskSizeUnit = "MB"
	DiskSpecDiskSizeUnitTB DiskSpecDiskSizeUnit = "TB"
)

// Defines values for DiskSpecSourceType.
const (
	DiskSpecSourceTypeBlank    DiskSpecSourceType = "blank"
	DiskSpecSourceTypeImage    DiskSpecSourceType = "image"
	DiskSpecSourceTypeSnapshot DiskSpecSourceType = "snapshot"
)

// Defines values for DiskStatusConditionsItemStatus.
const (
	DiskStatusConditionsItemStatusFalse   DiskStatusConditionsItemStatus = "False"
	DiskStatusConditionsItemStatusTrue    DiskStatusConditionsItemStatus = "True"
	DiskStatusConditionsItemStatusUnknown DiskStatusConditionsItemStatus = "Unknown"
)

// Defines values for DiskStatusDiskSizeUnit.
const (
	DiskStatusDiskSizeUnitGB DiskStatusDiskSizeUnit = "GB"
	DiskStatusDiskSizeUnitKB DiskStatusDiskSizeUnit = "KB"
	DiskStatusDiskSizeUnitMB DiskStatusDiskSizeUnit = "MB"
	DiskStatusDiskSizeUnitTB DiskStatusDiskSizeUnit = "TB"
)

// Defines values for DiskStatusDiskUsageItemUseKind.
const (
	Hotswap   DiskStatusDiskUsageItemUseKind = "hotswap"
	Permanent DiskStatusDiskUsageItemUseKind = "permanent"
)

// Defines values for HotswapDiskAttachmentStatusConditionsItemStatus.
const (
	HotswapDiskAttachmentStatusConditionsItemStatusFalse   HotswapDiskAttachmentStatusConditionsItemStatus = "False"
	HotswapDiskAttachmentStatusConditionsItemStatusTrue    HotswapDiskAttachmentStatusConditionsItemStatus = "True"
	HotswapDiskAttachmentStatusConditionsItemStatusUnknown HotswapDiskAttachmentStatusConditionsItemStatus = "Unknown"
)

// Defines values for PlacementGroupSpecStrategyType.
const (
	Spread PlacementGroupSpecStrategyType = "spread"
)

// Defines values for PlacementGroupStatusConditionsItemStatus.
const (
	PlacementGroupStatusConditionsItemStatusFalse   PlacementGroupStatusConditionsItemStatus = "False"
	PlacementGroupStatusConditionsItemStatusTrue    PlacementGroupStatusConditionsItemStatus = "True"
	PlacementGroupStatusConditionsItemStatusUnknown PlacementGroupStatusConditionsItemStatus = "Unknown"
)

// Defines values for SnapshotStatusConditionsItemStatus.
const (
	SnapshotStatusConditionsItemStatusFalse   SnapshotStatusConditionsItemStatus = "False"
	SnapshotStatusConditionsItemStatusTrue    SnapshotStatusConditionsItemStatus = "True"
	SnapshotStatusConditionsItemStatusUnknown SnapshotStatusConditionsItemStatus = "Unknown"
)

// Defines values for SnapshotStatusRestoreSizeUnit.
const (
	GB SnapshotStatusRestoreSizeUnit = "GB"
	KB SnapshotStatusRestoreSizeUnit = "KB"
	MB SnapshotStatusRestoreSizeUnit = "MB"
	TB SnapshotStatusRestoreSizeUnit = "TB"
)

// Defines values for VirtualMachineSpecNetworkingStackType.
const (
	DualStack VirtualMachineSpecNetworkingStackType = "dual-stack"
	Ipv4Only  VirtualMachineSpecNetworkingStackType = "ipv4-only"
	Ipv6Only  VirtualMachineSpecNetworkingStackType = "ipv6-only"
)

// Defines values for VirtualMachineStatusConditionsItemStatus.
const (
	False   VirtualMachineStatusConditionsItemStatus = "False"
	True    VirtualMachineStatusConditionsItemStatus = "True"
	Unknown VirtualMachineStatusConditionsItemStatus = "Unknown"
)

// BaseMetadataResponse Common metadata fields for all resource responses.
type BaseMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to determine when objects have changed. Any reconciliation, or system-driven status change, can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`
}

// Disk defines model for Disk.
type Disk struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional project-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     DiskSpec                 `json:"spec"`
	Status   DiskStatus               `json:"status"`
}

// DiskList defines model for DiskList.
type DiskList struct {
	Items *[]Disk `json:"items,omitempty"`
}

// DiskRequest defines model for DiskRequest.
type DiskRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`
	Spec     DiskSpec                `json:"spec"`
}

// DiskSpec defines model for DiskSpec.
type DiskSpec struct {
	// DiskSize The size of the disk.
	// If neither `diskImageRef` or `snapshotRef` are specified, then this must be specified.
	// If a `diskImageRef` is specified and no size is specified, then the default size specified in the diskImage is used.
	// If a `snapshotRef` is specified and no size is specified, then the restoreSize specified on the snapshot is used.
	// If a `snapshotRef` is specified and a size is specified, then the requested size must be larger than or equal to the restoreSize specified on the snapshot used.
	// Disk size can be increased (but never decreased)
	DiskSize *DiskSpecDiskSize `json:"diskSize,omitempty"`

	// Placement Placement defines the placement requirements for this Disk.
	Placement DiskSpecPlacement `json:"placement"`

	// Source Information about how to initially create the disk
	// All fields under 'source' are immutable.
	Source *DiskSpecSource `json:"source,omitempty"`
}

// DiskSpecDiskSize The size of the disk.
// If neither `diskImageRef` or `snapshotRef` are specified, then this must be specified.
// If a `diskImageRef` is specified and no size is specified, then the default size specified in the diskImage is used.
// If a `snapshotRef` is specified and no size is specified, then the restoreSize specified on the snapshot is used.
// If a `snapshotRef` is specified and a size is specified, then the requested size must be larger than or equal to the restoreSize specified on the snapshot used.
// Disk size can be increased (but never decreased)
type DiskSpecDiskSize struct {
	Amount int32                `json:"amount"`
	Unit   DiskSpecDiskSizeUnit `json:"unit"`
}

// DiskSpecDiskSizeUnit defines model for DiskSpecDiskSize.Unit.
type DiskSpecDiskSizeUnit string

// DiskSpecPlacement Placement defines the placement requirements for this Disk.
type DiskSpecPlacement struct {
	// Zone The zone this Disk should be deployed to.
	Zone *string `json:"zone,omitempty"`
}

// DiskSpecSource Information about how to initially create the disk
// All fields under 'source' are immutable.
type DiskSpecSource struct {
	// DiskImageRef The reference to the DiskImage to use as the OS image for this disk. This can be any of:
	// '/compute/global/diskImages/evroc/ubuntu-minimal.24-04.1',
	// '/compute/global/diskImages/evroc/ubuntu.24-04.1',
	// '/compute/global/diskImages/evroc/ubuntu.22-04.1',
	// '/compute/global/diskImages/evroc/rocky.10-1.1',
	// '/compute/global/diskImages/evroc/rocky.9-6.1',
	// '/compute/global/diskImages/evroc/rocky.8-10.1',
	// '/compute/global/diskImages/evroc/opensuse.15-6.1',
	// '/compute/global/diskImages/evroc/opensuse.15-5.1',
	// '/compute/global/diskImages/evroc/sles.15-6.1',
	// '/compute/global/diskImages/evroc/sles.15-5.1'
	// '/compute/global/diskImages/evroc/sl-micro.6-1.1'
	DiskImageRef *string `json:"diskImageRef,omitempty"`

	// SnapshotRef The reference to the Snapshot from which to create the disk.
	SnapshotRef *string `json:"snapshotRef,omitempty"`

	// Type The source type of this disk.
	// Available options:
	//   - `blank`
	//   - `image`
	//   - `snapshot`
	// If `blank`, then no other fields are allowed under `spec.source`, AND `spec.size` is manadatory, and an empty disk will be created of the requested size.
	// If `image`, then spec.source.diskImageRef is mandatory, AND spec.source.snapshotRef is not allowed AND `spec.size` is optional, and if no size is specified, then the default size specified in the diskImage is used, and a disk will be created from an image specified.
	// If `snapshot`, then spec.source.snapshotRef is mandatory AND spec.source.diskImageRef is not allowed AND `spec.size` is optional, and if no size is specified, then the restore size specified on the snapshot is used and a disk will be created from the snapshot specified.
	Type DiskSpecSourceType `json:"type"`
}

// DiskSpecSourceType The source type of this disk.
// Available options:
//   - `blank`
//   - `image`
//   - `snapshot`
//
// If `blank`, then no other fields are allowed under `spec.source`, AND `spec.size` is manadatory, and an empty disk will be created of the requested size.
// If `image`, then spec.source.diskImageRef is mandatory, AND spec.source.snapshotRef is not allowed AND `spec.size` is optional, and if no size is specified, then the default size specified in the diskImage is used, and a disk will be created from an image specified.
// If `snapshot`, then spec.source.snapshotRef is mandatory AND spec.source.diskImageRef is not allowed AND `spec.size` is optional, and if no size is specified, then the restore size specified on the snapshot is used and a disk will be created from the snapshot specified.
type DiskSpecSourceType string

// DiskStatus defines model for DiskStatus.
type DiskStatus struct {
	// Conditions The state of the disk over time.
	// Disks will report a Ready=true condition when they are ready for use in a VM.
	// Each condition follows the Kubernetes API conventions for a condition:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
	Conditions *[]DiskStatusConditionsItem `json:"conditions,omitempty"`

	// DiskSize The allocated disk size — either user-defined or a default.
	DiskSize *DiskStatusDiskSize `json:"diskSize,omitempty"`

	// DiskUsage DiskUsage shows the where this Disk is being used.
	// It is an array to enable reporting of accidental references from multiple VMs or HotswapDiskAttachments.
	DiskUsage *[]DiskStatusDiskUsageItem `json:"diskUsage,omitempty"`

	// Placement Placement defines the placement requirements for this Disk.
	Placement *DiskStatusPlacement `json:"placement,omitempty"`
}

// DiskStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type DiskStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status DiskStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// DiskStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type DiskStatusConditionsItemStatus string

// DiskStatusDiskSize The allocated disk size — either user-defined or a default.
type DiskStatusDiskSize struct {
	Amount int32                  `json:"amount"`
	Unit   DiskStatusDiskSizeUnit `json:"unit"`
}

// DiskStatusDiskSizeUnit defines model for DiskStatusDiskSize.Unit.
type DiskStatusDiskSizeUnit string

// DiskStatusDiskUsageItem defines model for DiskStatusDiskUsageItem.
type DiskStatusDiskUsageItem struct {
	// AttachmentRef The HotswapDiskAttachment driving this usage, if the Kind is "hotswap".
	AttachmentRef *string `json:"attachmentRef,omitempty"`

	// UseKind The kind of usage.
	UseKind DiskStatusDiskUsageItemUseKind `json:"useKind"`

	// VirtualMachineRef The VM consuming this Disk.
	VirtualMachineRef string `json:"virtualMachineRef"`
}

// DiskStatusDiskUsageItemUseKind The kind of usage.
type DiskStatusDiskUsageItemUseKind string

// DiskStatusPlacement Placement defines the placement requirements for this Disk.
type DiskStatusPlacement struct {
	// Zone The zone this Disk should be deployed to.
	Zone *string `json:"zone,omitempty"`
}

// Error Standard error response sent by all endpoints on failure.
type Error struct {
	// Debug Additional human-readable diagnostic information in English. This content is safe to surface to end users. MUST NOT be used for programmatic logic. The content may evolve at any time and is not stable.
	Debug *string `json:"debug,omitempty"`

	// Reason Stable, textual error code. This MUST be used by clients for programmatic handling. Examples include: FieldValueInvalid, Unauthorized, Forbidden.
	Reason string `json:"reason"`
}

// GlobalMetadataRequest Standard metadata for global resources.
type GlobalMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// HotswapDiskAttachment defines model for HotswapDiskAttachment.
type HotswapDiskAttachment struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional project-scoped resource
	Metadata RegionalMetadataResponse    `json:"metadata"`
	Spec     HotswapDiskAttachmentSpec   `json:"spec"`
	Status   HotswapDiskAttachmentStatus `json:"status"`
}

// HotswapDiskAttachmentList defines model for HotswapDiskAttachmentList.
type HotswapDiskAttachmentList struct {
	Items *[]HotswapDiskAttachment `json:"items,omitempty"`
}

// HotswapDiskAttachmentRequest defines model for HotswapDiskAttachmentRequest.
type HotswapDiskAttachmentRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest   `json:"metadata"`
	Spec     HotswapDiskAttachmentSpec `json:"spec"`
}

// HotswapDiskAttachmentSpec defines model for HotswapDiskAttachmentSpec.
type HotswapDiskAttachmentSpec struct {
	// DiskRef The Disk which should be attached to the VM.
	DiskRef string `json:"diskRef"`

	// VirtualMachineRef The VM to which the disk should be attached.
	VirtualMachineRef string `json:"virtualMachineRef"`
}

// HotswapDiskAttachmentStatus defines model for HotswapDiskAttachmentStatus.
type HotswapDiskAttachmentStatus struct {
	// Conditions The state of this attachment over time.
	Conditions *[]HotswapDiskAttachmentStatusConditionsItem `json:"conditions,omitempty"`

	// Serial The serial identifier of the disk when attached.
	Serial *string `json:"serial,omitempty"`
}

// HotswapDiskAttachmentStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type HotswapDiskAttachmentStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status HotswapDiskAttachmentStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// HotswapDiskAttachmentStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type HotswapDiskAttachmentStatusConditionsItemStatus string

// PlacementGroup defines model for PlacementGroup.
type PlacementGroup struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional project-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     PlacementGroupSpec       `json:"spec"`
	Status   PlacementGroupStatus     `json:"status"`
}

// PlacementGroupList defines model for PlacementGroupList.
type PlacementGroupList struct {
	Items *[]PlacementGroup `json:"items,omitempty"`
}

// PlacementGroupRequest defines model for PlacementGroupRequest.
type PlacementGroupRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`
	Spec     PlacementGroupSpec      `json:"spec"`
}

// PlacementGroupSpec defines model for PlacementGroupSpec.
type PlacementGroupSpec struct {
	// Placement Placement defines the placement requirements for this Placement Group.
	Placement PlacementGroupSpecPlacement `json:"placement"`

	// Strategy The placement strategy for the placement group,
	// which determines how the virtual machines inside the placement group should be distributed.
	Strategy PlacementGroupSpecStrategy `json:"strategy"`
}

// PlacementGroupSpecPlacement Placement defines the placement requirements for this Placement Group.
type PlacementGroupSpecPlacement struct {
	// Zone The zone this Placement Group should be deployed to.
	Zone *string `json:"zone,omitempty"`
}

// PlacementGroupSpecStrategy The placement strategy for the placement group,
// which determines how the virtual machines inside the placement group should be distributed.
type PlacementGroupSpecStrategy struct {
	// Type The name of the PlacementStrategy resource
	// For now there is one placement strategy: "spread"
	Type PlacementGroupSpecStrategyType `json:"type"`
}

// PlacementGroupSpecStrategyType The name of the PlacementStrategy resource
// For now there is one placement strategy: "spread"
type PlacementGroupSpecStrategyType string

// PlacementGroupStatus defines model for PlacementGroupStatus.
type PlacementGroupStatus struct {
	// Conditions The state of the placement group over time.
	// Each condition follows the Kubernetes API conventions for a condition:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
	Conditions *[]PlacementGroupStatusConditionsItem `json:"conditions,omitempty"`

	// Placement Placement defines the placement requirements for this Placement Group.
	Placement          *PlacementGroupStatusPlacement `json:"placement,omitempty"`
	VirtualMachineRefs *[]string                      `json:"virtualMachineRefs,omitempty"`
}

// PlacementGroupStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type PlacementGroupStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status PlacementGroupStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// PlacementGroupStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type PlacementGroupStatusConditionsItemStatus string

// PlacementGroupStatusPlacement Placement defines the placement requirements for this Placement Group.
type PlacementGroupStatusPlacement struct {
	// Zone The zone this Placement Group should be deployed to.
	Zone *string `json:"zone,omitempty"`
}

// RegionalMetadataRequest defines model for RegionalMetadataRequest.
type RegionalMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Project Project identifier
	Project *string `json:"project,omitempty"`

	// Region Region identifier
	Region *string `json:"region,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// RegionalMetadataResponse defines model for RegionalMetadataResponse.
type RegionalMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Project Project identifier
	Project *string `json:"project,omitempty"`

	// Region Region identifier
	Region *string `json:"region,omitempty"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to determine when objects have changed. Any reconciliation, or system-driven status change, can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// SystemLabels Map of string keys and string values owned and managed by evroc, and automatically set by the system. SystemLabels are read-only and can be referenced by label selectors.
	SystemLabels *SystemLabels `json:"systemLabels,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// Snapshot defines model for Snapshot.
type Snapshot struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional project-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     SnapshotSpec             `json:"spec"`
	Status   SnapshotStatus           `json:"status"`
}

// SnapshotList defines model for SnapshotList.
type SnapshotList struct {
	Items *[]Snapshot `json:"items,omitempty"`
}

// SnapshotRequest defines model for SnapshotRequest.
type SnapshotRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`
	Spec     SnapshotSpec            `json:"spec"`
}

// SnapshotSpec defines model for SnapshotSpec.
type SnapshotSpec struct {
	// DiskRef The reference to the disk from which to create the Snapshot.
	DiskRef *string `json:"diskRef,omitempty"`
}

// SnapshotStatus defines model for SnapshotStatus.
type SnapshotStatus struct {
	// Conditions The state of the Snapshot over time.
	// Snapshots will report a Ready=true condition when they are ready for use in a VM.
	// Each condition follows the Kubernetes API conventions for a condition:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
	Conditions *[]SnapshotStatusConditionsItem `json:"conditions,omitempty"`

	// CreationTime The time the snapshot was created
	CreationTime *time.Time `json:"creationTime,omitempty"`

	// Placement Placement information about the snapshot.
	Placement *SnapshotStatusPlacement `json:"placement,omitempty"`

	// RestoreSize The size of the snapshot.
	RestoreSize *SnapshotStatusRestoreSize `json:"restoreSize,omitempty"`
}

// SnapshotStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type SnapshotStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status SnapshotStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// SnapshotStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type SnapshotStatusConditionsItemStatus string

// SnapshotStatusPlacement Placement information about the snapshot.
type SnapshotStatusPlacement struct {
	// Zones The zone this snapshot is in. This is also precisely the only zone that the snapshot can be restored into.
	Zones *string `json:"zones,omitempty"`
}

// SnapshotStatusRestoreSize The size of the snapshot.
type SnapshotStatusRestoreSize struct {
	Amount int32                         `json:"amount"`
	Unit   SnapshotStatusRestoreSizeUnit `json:"unit"`
}

// SnapshotStatusRestoreSizeUnit defines model for SnapshotStatusRestoreSize.Unit.
type SnapshotStatusRestoreSizeUnit string

// SystemLabels Map of string keys and string values owned and managed by evroc, and automatically set by the system. SystemLabels are read-only and can be referenced by label selectors.
type SystemLabels map[string]string

// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
type UserLabels map[string]string

// VirtualMachine defines model for VirtualMachine.
type VirtualMachine struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional project-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     VirtualMachineSpec       `json:"spec"`
	Status   VirtualMachineStatus     `json:"status"`
}

// VirtualMachineList defines model for VirtualMachineList.
type VirtualMachineList struct {
	Items *[]VirtualMachine `json:"items,omitempty"`
}

// VirtualMachineRequest defines model for VirtualMachineRequest.
type VirtualMachineRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`
	Spec     VirtualMachineSpec      `json:"spec"`
}

// VirtualMachineSpec defines model for VirtualMachineSpec.
type VirtualMachineSpec struct {
	// ComputeProfileRef A reference to a ComputeProfile object, which in turn defines the number of vCPUs, memory and the processor
	// architecture that this VM will use. Profile IDs generally have the form <series>.<size> where
	// series is one of, but not limited to 'a1a', 'c1a', or 'm1a' and size is one of 'xs', 's', 'm', 'l', 'xl', or
	// '2xl'.
	// See the documentation for an authoritative list of supported profiles.
	ComputeProfileRef string `json:"computeProfileRef"`

	// Disks The VM's Disks.
	Disks *[]VirtualMachineSpecDisksItem `json:"disks,omitempty"`

	// LoadBalancerMemberships Load Balancer membership configuration for the VM.
	LoadBalancerMemberships *VirtualMachineSpecLoadBalancerMemberships `json:"loadBalancerMemberships,omitempty"`

	// Networking Networking settings for the VM.
	Networking VirtualMachineSpecNetworking `json:"networking"`

	// OsSettings Settings that are applied to the guest operating system.
	OsSettings *VirtualMachineSpecOsSettings `json:"osSettings,omitempty"`

	// Placement Placement defines the placement requirements for this Virtual Machine.
	Placement VirtualMachineSpecPlacement `json:"placement"`

	// Running Whether the VM should be running or not. If not set, this defaults to true
	Running *bool `json:"running,omitempty"`
}

// VirtualMachineSpecDisksItem A reference to a Disk object. If marked as bootFrom, the VM will boot from the Disk.
type VirtualMachineSpecDisksItem struct {
	// BootFrom BootFrom indicates whether the VM should boot from this Disk.  Only one Disk can be
	// marked as BootFrom.
	BootFrom *bool `json:"bootFrom,omitempty"`

	// DiskRef The Disk object which should be attached to the VM.
	DiskRef string `json:"diskRef"`
}

// VirtualMachineSpecLoadBalancerMemberships Load Balancer membership configuration for the VM.
type VirtualMachineSpecLoadBalancerMemberships struct {
	// BackendPoolRefs The set of Load Balancer Pools to which this VM belongs.
	BackendPoolRefs *[]string `json:"backendPoolRefs,omitempty"`
}

// VirtualMachineSpecNetworking Networking settings for the VM.
type VirtualMachineSpecNetworking struct {
	// PublicIPv4Address Options that control whether and how the VM is assigned a public IPv4 address.
	// If this structure is not specified, the VM will not be assigned a public address.
	// This means the machine will only be able to receive inbound flows from the private network (though it can still
	// start outbound flows to outside the private network if an external gateway is configured in the VPC).
	PublicIPv4Address *struct {
		// Static Settings related to static public IPv4 addressing.
		// Static addresses are not released when the VM is stopped.
		Static *VirtualMachineSpecNetworkingStatic `json:"static,omitempty"`
	} `json:"publicIPv4Address,omitempty"`

	// SecurityGroupSettings Options related to security groups.
	SecurityGroupSettings *struct {
		// SecurityGroupMemberRefs The Security Groups the VM belongs to.
		SecurityGroupMemberRefs *[]string `json:"securityGroupMemberRefs,omitempty"`
	} `json:"securityGroupSettings,omitempty"`

	// StackType The stack type of this VM.  Can either be "dual-stack", meaning that both IPv4 and IPv6
	// addresses are provisioned, or "ipv6-only".  The Subnet must support the chosen stack.
	// The stack type of the Subnet will be used if it is not specified on the VM.
	// During the migration period, "ipv4-only" is also allowed.
	StackType *VirtualMachineSpecNetworkingStackType `json:"stackType,omitempty"`

	// SubnetRef The Subnet that this VM should be attached to.  The VM must be attached to a Subnet.
	SubnetRef string `json:"subnetRef"`
}

// VirtualMachineSpecNetworkingStackType The stack type of this VM.  Can either be "dual-stack", meaning that both IPv4 and IPv6
// addresses are provisioned, or "ipv6-only".  The Subnet must support the chosen stack.
// The stack type of the Subnet will be used if it is not specified on the VM.
// During the migration period, "ipv4-only" is also allowed.
type VirtualMachineSpecNetworkingStackType string

// VirtualMachineSpecNetworkingStatic Settings related to static public IPv4 addressing.
// Static addresses are not released when the VM is stopped.
type VirtualMachineSpecNetworkingStatic struct {
	// PublicIPRef The public IP that the VM will attach to.
	PublicIPRef *string `json:"publicIPRef,omitempty"`
}

// VirtualMachineSpecOsSettings Settings that are applied to the guest operating system.
type VirtualMachineSpecOsSettings struct {
	// CloudInitUserData User-data passed to the VM.
	// This can either be a base64 string, or a multi-line string.
	// This cannot be updated after the VM is created, and is only supported on Linux VMs.
	// See the documentation at https://docs.evroc.com/products/compute/guides/use-custom-cloud-init.html
	// for more information.
	CloudInitUserData *string `json:"cloudInitUserData,omitempty"`

	// Ssh SSH settings in the guest operating system.
	// This field is only supported for Linux VMs. It is ignored for other operating systems.
	Ssh *struct {
		// AuthorizedKeys A list of public SSH keys that will be added to the "evroc-user" user created in the guest VM. This allows
		// operators/tools to log in over SSH using the corresponding private key.
		//
		// The acceptable public key algorithms depend on the operating system. For example, on Ubuntu 24.04, the accepted
		// algorithms are defined by `sshd_config`. No validation is performed to ensure that a given algorithm is
		// acceptable for the VM.
		//
		// The keys supplied here are written to /home/evroc-user/.ssh/authorized_keys on first boot. After first boot,
		// changes to this field have no effect. If the operator wants to add more authorized keys, they must connect to
		// the VM and add them to the authorized_keys file directly.
		//
		// If cloudInitUserData is specified, then these keys will only be applied to your VM if your CloudConfig
		// references them - see the documentation at https://docs.evroc.com/products/compute/guides/use-custom-cloud-init.html
		// for more information.
		AuthorizedKeys *[]VirtualMachineSpecOsSettingsAuthorizedKeysItem `json:"authorizedKeys,omitempty"`
	} `json:"ssh,omitempty"`
}

// VirtualMachineSpecOsSettingsAuthorizedKeysItem defines model for VirtualMachineSpecOsSettingsAuthorizedKeysItem.
type VirtualMachineSpecOsSettingsAuthorizedKeysItem struct {
	// Value The content of an authorized key, must be a valid SSH public key according to the sshd(8) manual page.
	Value string `json:"value"`
}

// VirtualMachineSpecPlacement Placement defines the placement requirements for this Virtual Machine.
type VirtualMachineSpecPlacement struct {
	// PlacementGroupRef The placement group to use for this VM.
	//
	// This is used to control the placement of the VM on the underlying hardware.
	PlacementGroupRef *string `json:"placementGroupRef,omitempty"`

	// Zone The zone this Virtual Machine should be deployed to.
	Zone *string `json:"zone,omitempty"`
}

// VirtualMachineStatus defines model for VirtualMachineStatus.
type VirtualMachineStatus struct {
	// AttachedDisks The current mapping between permanent evroc Disks and Devices on the VM.
	AttachedDisks *[]VirtualMachineStatusAttachedDisksItem `json:"attachedDisks,omitempty"`

	// Conditions The state of the Virtual Machine over time.
	// Each condition follows the Kubernetes API conventions for a condition:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
	Conditions *[]VirtualMachineStatusConditionsItem `json:"conditions,omitempty"`

	// HotswapDiskAttachments The current requested Hotswap Disk Attachments for this VM.
	HotswapDiskAttachments *[]VirtualMachineStatusHotswapDiskAttachmentsItem `json:"hotswapDiskAttachments,omitempty"`

	// Networking The current status of the networking set up on the VM.
	Networking *VirtualMachineStatusNetworking `json:"networking,omitempty"`

	// Placement Placement defines the placement requirements for this Virtual Machine.
	Placement *VirtualMachineStatusPlacement `json:"placement,omitempty"`

	// VirtualMachineStatus The status of the VM. It can be one of:
	// e.g. "Running", "Stopped", "Creating" etc. Refer to the documentation for a
	// full list of the possible values.
	VirtualMachineStatus *string `json:"virtualMachineStatus,omitempty"`
}

// VirtualMachineStatusAttachedDisksItem The current mapping of a permanent Disk to a Device on the VM.
type VirtualMachineStatusAttachedDisksItem struct {
	// Device The device the Disk corresponds to on the VM (e.g. /dev/vda).
	Device *string `json:"device,omitempty"`

	// DiskRef The attached Disk.
	DiskRef *string `json:"diskRef,omitempty"`
}

// VirtualMachineStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type VirtualMachineStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status VirtualMachineStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// VirtualMachineStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type VirtualMachineStatusConditionsItemStatus string

// VirtualMachineStatusHotswapDiskAttachmentsItem Capture the status of a HotswapDiskAttachment targeting this VM.
type VirtualMachineStatusHotswapDiskAttachmentsItem struct {
	// Attached Attachment status.
	Attached bool `json:"attached"`

	// Device The device that an attached Disk corresponds to on the VM (e.g. /dev/vda).
	Device *string `json:"device,omitempty"`

	// DiskRef The Disk being attached.
	DiskRef *string `json:"diskRef,omitempty"`

	// HotswapDiskAttachmentRef The HotswapDiskAttachment being requested.
	HotswapDiskAttachmentRef string `json:"hotswapDiskAttachmentRef"`

	// Message Message indicating the reason for a non-attached Disk.
	Message *string `json:"message,omitempty"`

	// Reason Reason code for non-attached Disk.
	// One of: "HotswapDiskInvalid" or "HotswapVMInvalid".
	Reason *string `json:"reason,omitempty"`

	// Serial Serial of an attached Disk.
	Serial *string `json:"serial,omitempty"`
}

// VirtualMachineStatusNetworking The current status of the networking set up on the VM.
type VirtualMachineStatusNetworking struct {
	// Ipv6Address The assigned IPv6 address of the VM.
	Ipv6Address *string `json:"ipv6Address,omitempty"`

	// PrivateIPv4Address The assigned private IPv4 address of the VM.
	PrivateIPv4Address *string `json:"privateIPv4Address,omitempty"`

	// PublicIPv4Address The assigned public IPv4 address of the VM.
	PublicIPv4Address *string `json:"publicIPv4Address,omitempty"`

	// SecurityGroupActiveMembershipRefs The active security groups the VM currently belongs to.
	SecurityGroupActiveMembershipRefs *[]string `json:"securityGroupActiveMembershipRefs,omitempty"`

	// SecurityGroupFailedMembershipRefs Security groups the VM belongs to which are not healthy.
	SecurityGroupFailedMembershipRefs *[]string `json:"securityGroupFailedMembershipRefs,omitempty"`

	// SecurityGroupPendingMembershipRefs Security groups the VM is attempting to join.
	SecurityGroupPendingMembershipRefs *[]string `json:"securityGroupPendingMembershipRefs,omitempty"`

	// StackType The stack type of this VM.
	StackType *string `json:"stackType,omitempty"`
}

// VirtualMachineStatusPlacement Placement defines the placement requirements for this Virtual Machine.
type VirtualMachineStatusPlacement struct {
	// PlacementGroupRef The placement group to use for this VM.
	//
	// This is used to control the placement of the VM on the underlying hardware.
	PlacementGroupRef *string `json:"placementGroupRef,omitempty"`

	// Zone The zone this Virtual Machine should be deployed to.
	Zone *string `json:"zone,omitempty"`
}

// ApiVersion Identifies the version of the API schema used for this resource.
// It should be the same than the version in the path, otherwise the request will be rejected.
type ApiVersion = string

// Kind Specifies the type of resource this object represents.
type Kind = string

// GetComputeV1beta2ProjectsProjectIDRegionsRegionNameDisksParams defines parameters for GetComputeV1beta2ProjectsProjectIDRegionsRegionNameDisks.
type GetComputeV1beta2ProjectsProjectIDRegionsRegionNameDisksParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetComputeV1beta2ProjectsProjectIDRegionsRegionNameHotswapDiskAttachmentsParams defines parameters for GetComputeV1beta2ProjectsProjectIDRegionsRegionNameHotswapDiskAttachments.
type GetComputeV1beta2ProjectsProjectIDRegionsRegionNameHotswapDiskAttachmentsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetComputeV1beta2ProjectsProjectIDRegionsRegionNamePlacementGroupsParams defines parameters for GetComputeV1beta2ProjectsProjectIDRegionsRegionNamePlacementGroups.
type GetComputeV1beta2ProjectsProjectIDRegionsRegionNamePlacementGroupsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetComputeV1beta2ProjectsProjectIDRegionsRegionNameSnapshotsParams defines parameters for GetComputeV1beta2ProjectsProjectIDRegionsRegionNameSnapshots.
type GetComputeV1beta2ProjectsProjectIDRegionsRegionNameSnapshotsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetComputeV1beta2ProjectsProjectIDRegionsRegionNameVirtualMachinesParams defines parameters for GetComputeV1beta2ProjectsProjectIDRegionsRegionNameVirtualMachines.
type GetComputeV1beta2ProjectsProjectIDRegionsRegionNameVirtualMachinesParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// PostComputeV1beta2ProjectsProjectIDRegionsRegionNameDisksJSONRequestBody defines body for PostComputeV1beta2ProjectsProjectIDRegionsRegionNameDisks for application/json ContentType.
type PostComputeV1beta2ProjectsProjectIDRegionsRegionNameDisksJSONRequestBody = DiskRequest

// PatchComputeV1beta2ProjectsProjectIDRegionsRegionNameDisksDiskIDJSONRequestBody defines body for PatchComputeV1beta2ProjectsProjectIDRegionsRegionNameDisksDiskID for application/json ContentType.
type PatchComputeV1beta2ProjectsProjectIDRegionsRegionNameDisksDiskIDJSONRequestBody = DiskRequest

// PostComputeV1beta2ProjectsProjectIDRegionsRegionNameHotswapDiskAttachmentsJSONRequestBody defines body for PostComputeV1beta2ProjectsProjectIDRegionsRegionNameHotswapDiskAttachments for application/json ContentType.
type PostComputeV1beta2ProjectsProjectIDRegionsRegionNameHotswapDiskAttachmentsJSONRequestBody = HotswapDiskAttachmentRequest

// PatchComputeV1beta2ProjectsProjectIDRegionsRegionNameHotswapDiskAttachmentsHotswapDiskAttachmentIDJSONRequestBody defines body for PatchComputeV1beta2ProjectsProjectIDRegionsRegionNameHotswapDiskAttachmentsHotswapDiskAttachmentID for application/json ContentType.
type PatchComputeV1beta2ProjectsProjectIDRegionsRegionNameHotswapDiskAttachmentsHotswapDiskAttachmentIDJSONRequestBody = HotswapDiskAttachmentRequest

// PostComputeV1beta2ProjectsProjectIDRegionsRegionNamePlacementGroupsJSONRequestBody defines body for PostComputeV1beta2ProjectsProjectIDRegionsRegionNamePlacementGroups for application/json ContentType.
type PostComputeV1beta2ProjectsProjectIDRegionsRegionNamePlacementGroupsJSONRequestBody = PlacementGroupRequest

// PatchComputeV1beta2ProjectsProjectIDRegionsRegionNamePlacementGroupsPlacementGroupIDJSONRequestBody defines body for PatchComputeV1beta2ProjectsProjectIDRegionsRegionNamePlacementGroupsPlacementGroupID for application/json ContentType.
type PatchComputeV1beta2ProjectsProjectIDRegionsRegionNamePlacementGroupsPlacementGroupIDJSONRequestBody = PlacementGroupRequest

// PostComputeV1beta2ProjectsProjectIDRegionsRegionNameSnapshotsJSONRequestBody defines body for PostComputeV1beta2ProjectsProjectIDRegionsRegionNameSnapshots for application/json ContentType.
type PostComputeV1beta2ProjectsProjectIDRegionsRegionNameSnapshotsJSONRequestBody = SnapshotRequest

// PatchComputeV1beta2ProjectsProjectIDRegionsRegionNameSnapshotsSnapshotIDJSONRequestBody defines body for PatchComputeV1beta2ProjectsProjectIDRegionsRegionNameSnapshotsSnapshotID for application/json ContentType.
type PatchComputeV1beta2ProjectsProjectIDRegionsRegionNameSnapshotsSnapshotIDJSONRequestBody = SnapshotRequest

// PostComputeV1beta2ProjectsProjectIDRegionsRegionNameVirtualMachinesJSONRequestBody defines body for PostComputeV1beta2ProjectsProjectIDRegionsRegionNameVirtualMachines for application/json ContentType.
type PostComputeV1beta2ProjectsProjectIDRegionsRegionNameVirtualMachinesJSONRequestBody = VirtualMachineRequest

// PatchComputeV1beta2ProjectsProjectIDRegionsRegionNameVirtualMachinesVirtualMachineIDJSONRequestBody defines body for PatchComputeV1beta2ProjectsProjectIDRegionsRegionNameVirtualMachinesVirtualMachineID for application/json ContentType.
type PatchComputeV1beta2ProjectsProjectIDRegionsRegionNameVirtualMachinesVirtualMachineIDJSONRequestBody = VirtualMachineRequest
