// Copyright 2026 evroc
// SPDX-License-Identifier: Apache-2.0
//
// Package networking provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package networking

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for PublicIPStatusConditionsItemStatus.
const (
	PublicIPStatusConditionsItemStatusFalse   PublicIPStatusConditionsItemStatus = "False"
	PublicIPStatusConditionsItemStatusTrue    PublicIPStatusConditionsItemStatus = "True"
	PublicIPStatusConditionsItemStatusUnknown PublicIPStatusConditionsItemStatus = "Unknown"
)

// Defines values for SecurityGroupSpecRulesItemDirection.
const (
	Egress  SecurityGroupSpecRulesItemDirection = "Egress"
	Ingress SecurityGroupSpecRulesItemDirection = "Ingress"
)

// Defines values for SecurityGroupSpecRulesItemProtocol.
const (
	All  SecurityGroupSpecRulesItemProtocol = "All"
	ICMP SecurityGroupSpecRulesItemProtocol = "ICMP"
	TCP  SecurityGroupSpecRulesItemProtocol = "TCP"
	UDP  SecurityGroupSpecRulesItemProtocol = "UDP"
)

// Defines values for SecurityGroupStatusConditionsItemStatus.
const (
	SecurityGroupStatusConditionsItemStatusFalse   SecurityGroupStatusConditionsItemStatus = "False"
	SecurityGroupStatusConditionsItemStatusTrue    SecurityGroupStatusConditionsItemStatus = "True"
	SecurityGroupStatusConditionsItemStatusUnknown SecurityGroupStatusConditionsItemStatus = "Unknown"
)

// Defines values for SecurityGroupStatusMembersItemStatus.
const (
	Active  SecurityGroupStatusMembersItemStatus = "Active"
	Pending SecurityGroupStatusMembersItemStatus = "Pending"
)

// Defines values for SubnetSpecStackType.
const (
	SubnetSpecStackTypeDualStack SubnetSpecStackType = "dual-stack"
	SubnetSpecStackTypeIpv6Only  SubnetSpecStackType = "ipv6-only"
)

// Defines values for SubnetStatusConditionsItemStatus.
const (
	SubnetStatusConditionsItemStatusFalse   SubnetStatusConditionsItemStatus = "False"
	SubnetStatusConditionsItemStatusTrue    SubnetStatusConditionsItemStatus = "True"
	SubnetStatusConditionsItemStatusUnknown SubnetStatusConditionsItemStatus = "Unknown"
)

// Defines values for VirtualPrivateCloudSpecStackType.
const (
	VirtualPrivateCloudSpecStackTypeDualStack VirtualPrivateCloudSpecStackType = "dual-stack"
	VirtualPrivateCloudSpecStackTypeIpv6Only  VirtualPrivateCloudSpecStackType = "ipv6-only"
)

// Defines values for VirtualPrivateCloudStatusConditionsItemStatus.
const (
	VirtualPrivateCloudStatusConditionsItemStatusFalse   VirtualPrivateCloudStatusConditionsItemStatus = "False"
	VirtualPrivateCloudStatusConditionsItemStatusTrue    VirtualPrivateCloudStatusConditionsItemStatus = "True"
	VirtualPrivateCloudStatusConditionsItemStatusUnknown VirtualPrivateCloudStatusConditionsItemStatus = "Unknown"
)

// BaseMetadataResponse Common metadata fields for all resource responses.
type BaseMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to determine when objects have changed. Any reconciliation, or system-driven status change, can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`
}

// Error Standard error response sent by all endpoints on failure.
type Error struct {
	// Debug Additional human-readable diagnostic information in English. This content is safe to surface to end users. MUST NOT be used for programmatic logic. The content may evolve at any time and is not stable.
	Debug *string `json:"debug,omitempty"`

	// Reason Stable, textual error code. This MUST be used by clients for programmatic handling. Examples include: FieldValueInvalid, Unauthorized, Forbidden.
	Reason string `json:"reason"`
}

// GlobalMetadataRequest Standard metadata for global resources.
type GlobalMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// PublicIP defines model for PublicIP.
type PublicIP struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional project-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     PublicIPSpec             `json:"spec"`
	Status   PublicIPStatus           `json:"status"`
}

// PublicIPList defines model for PublicIPList.
type PublicIPList struct {
	Items *[]PublicIP `json:"items,omitempty"`
}

// PublicIPRequest defines model for PublicIPRequest.
type PublicIPRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`
	Spec     PublicIPSpec            `json:"spec"`
}

// PublicIPSpec defines model for PublicIPSpec.
type PublicIPSpec = map[string]interface{}

// PublicIPStatus defines model for PublicIPStatus.
type PublicIPStatus struct {
	// Conditions The state of the PublicIP over time.
	// Each condition follows the Kubernetes API conventions for a condition:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
	Conditions *[]PublicIPStatusConditionsItem `json:"conditions,omitempty"`

	// PublicIPv4Address The IPv4 address that has been reserved.
	PublicIPv4Address *string `json:"publicIPv4Address,omitempty"`

	// UsedByRef The object that is currently using this PublicIP object.
	// If a there is an attempt to delete a PublicIP object while it is in use, the deletion will be blocked until the
	// user no longer needs the PublicIP (either because it has been deleted, or has been reconfigured to no longer
	// need the PublicIP).
	UsedByRef *string `json:"usedByRef,omitempty"`
}

// PublicIPStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type PublicIPStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status PublicIPStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// PublicIPStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type PublicIPStatusConditionsItemStatus string

// RegionalMetadataRequest defines model for RegionalMetadataRequest.
type RegionalMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Project Project identifier
	Project *string `json:"project,omitempty"`

	// Region Region identifier
	Region *string `json:"region,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// RegionalMetadataResponse defines model for RegionalMetadataResponse.
type RegionalMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Id Unique identifier for the resource within its namespace. Immutable.
	Id string `json:"id"`

	// Project Project identifier
	Project *string `json:"project,omitempty"`

	// Region Region identifier
	Region *string `json:"region,omitempty"`

	// ResourceVersion String that identifies the internal version of this object that can be used by clients to determine when objects have changed. Any reconciliation, or system-driven status change, can change the resourceVersion, not only a change of spec.
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// SystemLabels Map of string keys and string values owned and managed by evroc, and automatically set by the system. SystemLabels are read-only and can be referenced by label selectors.
	SystemLabels *SystemLabels `json:"systemLabels,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// SecurityGroup defines model for SecurityGroup.
type SecurityGroup struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional project-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     SecurityGroupSpec        `json:"spec"`
	Status   SecurityGroupStatus      `json:"status"`
}

// SecurityGroupList defines model for SecurityGroupList.
type SecurityGroupList struct {
	Items *[]SecurityGroup `json:"items,omitempty"`
}

// SecurityGroupRequest defines model for SecurityGroupRequest.
type SecurityGroupRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`
	Spec     SecurityGroupSpec       `json:"spec"`
}

// SecurityGroupSpec defines model for SecurityGroupSpec.
type SecurityGroupSpec struct {
	// Rules The rules for this security group.
	Rules *[]SecurityGroupSpecRulesItem `json:"rules,omitempty"`

	// VpcRef VpcRef is the reference to the VPC that the security group is a member of.
	VpcRef string `json:"vpcRef"`
}

// SecurityGroupSpecRulesItem defines model for SecurityGroupSpecRulesItem.
type SecurityGroupSpecRulesItem struct {
	// Direction The direction of traffic the rule applies to. Can be 'Ingress' or 'Egress'.
	Direction SecurityGroupSpecRulesItemDirection `json:"direction"`

	// EndPort If specified, means that the rule applies to all ports from port to endPort. Empty or '0' indicates that only
	// port is opened (if port is specified) or all ports are opened (if port is not specified).
	EndPort *int32 `json:"endPort,omitempty"`

	// Name The name of the rule. Optional. Must be unique per security group.
	Name *string `json:"name,omitempty"`

	// Port The port the rule applies to. Empty or '0' indicates all ports.  Can only be set if the Protocol is TCP or UDP.
	Port *int32 `json:"port,omitempty"`

	// Protocol The protocol the rule applies to. Can be 'TCP', 'UDP', 'ICMP' or 'All'. Empty indicates all protocols.
	Protocol *SecurityGroupSpecRulesItemProtocol `json:"protocol,omitempty"`

	// Remote The source (for ingress) or destination (for egress) that the rule applies to.
	Remote struct {
		// Address The IP address or CIDR that traffic is allowed to/from.
		Address *SecurityGroupSpecRulesItemAddress `json:"address,omitempty"`

		// SecurityGroupRef The security group that traffic is allowed to/from.
		SecurityGroupRef *string `json:"securityGroupRef,omitempty"`

		// SubnetRef The subnet that traffic is allowed to/from.
		SubnetRef *string `json:"subnetRef,omitempty"`

		// VpcRef The virtual private cloud that traffic is allowed to/from.  This must match the VPC
		// referenced on the security group itself (the VPC that the security group is a member of).
		VpcRef *string `json:"vpcRef,omitempty"`
	} `json:"remote"`
}

// SecurityGroupSpecRulesItemDirection The direction of traffic the rule applies to. Can be 'Ingress' or 'Egress'.
type SecurityGroupSpecRulesItemDirection string

// SecurityGroupSpecRulesItemProtocol The protocol the rule applies to. Can be 'TCP', 'UDP', 'ICMP' or 'All'. Empty indicates all protocols.
type SecurityGroupSpecRulesItemProtocol string

// SecurityGroupSpecRulesItemAddress The IP address or CIDR that traffic is allowed to/from.
type SecurityGroupSpecRulesItemAddress struct {
	// IpAddressOrCIDR The IP address or CIDR (IPv4 or IPv6) that traffic is allowed to/from.
	IpAddressOrCIDR string `json:"ipAddressOrCIDR"`
}

// SecurityGroupStatus defines model for SecurityGroupStatus.
type SecurityGroupStatus struct {
	// Conditions ConditionsSet is an abstraction over []metav1.Condition that handles the
	// removal of the previous occurrence of the conditionType when marking a condition.
	Conditions *[]SecurityGroupStatusConditionsItem `json:"conditions,omitempty"`
	Members    *[]SecurityGroupStatusMembersItem    `json:"members,omitempty"`
}

// SecurityGroupStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type SecurityGroupStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status SecurityGroupStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// SecurityGroupStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type SecurityGroupStatusConditionsItemStatus string

// SecurityGroupStatusMembersItem defines model for SecurityGroupStatusMembersItem.
type SecurityGroupStatusMembersItem struct {
	SecurityGroupMemberRef string                               `json:"securityGroupMemberRef"`
	Status                 SecurityGroupStatusMembersItemStatus `json:"status"`
}

// SecurityGroupStatusMembersItemStatus defines model for SecurityGroupStatusMembersItem.Status.
type SecurityGroupStatusMembersItemStatus string

// Subnet defines model for Subnet.
type Subnet struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional project-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     SubnetSpec               `json:"spec"`
	Status   SubnetStatus             `json:"status"`
}

// SubnetList defines model for SubnetList.
type SubnetList struct {
	Items *[]Subnet `json:"items,omitempty"`
}

// SubnetRequest defines model for SubnetRequest.
type SubnetRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`
	Spec     SubnetSpec              `json:"spec"`
}

// SubnetSpec defines model for SubnetSpec.
type SubnetSpec struct {
	// Ipv4CidrBlock An IPv4 CIDR block.  Must be contained within its VPC's IPv4 CIDR Block, and must have
	// a prefix between /16 and /29.
	Ipv4CidrBlock *string `json:"ipv4CidrBlock,omitempty"`

	// Placement Placement defines the placement requirements for this Subnet.
	Placement SubnetSpecPlacement `json:"placement"`

	// StackType The stack type of this Subnet.  Can either be "dual-stack", meaning that both IPv4 and IPv6
	// addresses are provisioned, or "ipv6-only".  If "dual-stack", an IPv4 CIDR Block must be
	// specified for the Subnet.
	StackType SubnetSpecStackType `json:"stackType"`
	VpcRef    string              `json:"vpcRef"`
}

// SubnetSpecStackType The stack type of this Subnet.  Can either be "dual-stack", meaning that both IPv4 and IPv6
// addresses are provisioned, or "ipv6-only".  If "dual-stack", an IPv4 CIDR Block must be
// specified for the Subnet.
type SubnetSpecStackType string

// SubnetSpecPlacement Placement defines the placement requirements for this Subnet.
type SubnetSpecPlacement struct {
	// Zone The zone this Subnet should be deployed to.
	Zone *string `json:"zone,omitempty"`
}

// SubnetStatus defines model for SubnetStatus.
type SubnetStatus struct {
	// AssignedIPv6GUABlock The range of publicly routable IPv6 addresses assigned to this Subnet.
	AssignedIPv6GUABlock *string `json:"assignedIPv6GUABlock,omitempty"`

	// AttachmentRefs attachmentRefs is a list of references to resources attached to this Subnet.
	AttachmentRefs *[]string `json:"attachmentRefs,omitempty"`

	// AvailableIPv4AddressCount availableIPv4AddressCount is a count of the number of IPv4 addresses not yet assigned in this Subnet.
	AvailableIPv4AddressCount *int `json:"availableIPv4AddressCount,omitempty"`

	// AvailableIPv4Ranges availableIPv4Ranges is a list of either single IPs (e.g. "10.0.0.2") or IP ranges ("10.0.0.4-10.0.0.7") of IPv4
	// addresses currently not in use in this Subnet.
	AvailableIPv4Ranges *[]string `json:"availableIPv4Ranges,omitempty"`

	// Conditions The state of the Subnet over time.
	// Each condition follows the Kubernetes API conventions for a condition:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
	Conditions *[]SubnetStatusConditionsItem `json:"conditions,omitempty"`

	// Placement Placement defines the placement requirements for this Subnet.
	Placement *SubnetStatusPlacement `json:"placement,omitempty"`

	// UsingIPv4AddressCount usingIPv4AddressCount is a count of the number of IPv4 addresses currently in use in this Subnet. Deletion of
	// this Subnet will be blocked if there are IPs in the Subnet in use. Those resources need to be deleted first.
	UsingIPv4AddressCount *int `json:"usingIPv4AddressCount,omitempty"`

	// UsingIPv4Ranges usingIPv4Ranges is a list of either single IPs (e.g. "10.0.0.2") or IP ranges ("10.0.0.4-10.0.0.7") of IPv4
	// addresses currently in use in this Subnet.
	UsingIPv4Ranges *[]string `json:"usingIPv4Ranges,omitempty"`

	// UsingIPv6AddressCount usingIPv6AddressCount is a count of the number of IPv6 addresses currently in use in this Subnet. Deletion of
	// this Subnet will be blocked if there are IPs in the Subnet in use. Those resources need to be deleted first.
	UsingIPv6AddressCount *int `json:"usingIPv6AddressCount,omitempty"`

	// UsingIPv6Ranges UsingIPv6Ranges is a list of either single IPs (e.g. "2001:db8::2") or IP ranges
	// ("2001:db8::4-2001:db8::7") of IPv6 addresses currently in use in this Subnet.
	UsingIPv6Ranges *[]string `json:"usingIPv6Ranges,omitempty"`
}

// SubnetStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type SubnetStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status SubnetStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// SubnetStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type SubnetStatusConditionsItemStatus string

// SubnetStatusPlacement Placement defines the placement requirements for this Subnet.
type SubnetStatusPlacement struct {
	// Zone The zone this Subnet should be deployed to.
	Zone *string `json:"zone,omitempty"`
}

// SystemLabels Map of string keys and string values owned and managed by evroc, and automatically set by the system. SystemLabels are read-only and can be referenced by label selectors.
type SystemLabels map[string]string

// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
type UserLabels map[string]string

// VirtualPrivateCloud defines model for VirtualPrivateCloud.
type VirtualPrivateCloud struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for regional project-scoped resource
	Metadata RegionalMetadataResponse  `json:"metadata"`
	Spec     VirtualPrivateCloudSpec   `json:"spec"`
	Status   VirtualPrivateCloudStatus `json:"status"`
}

// VirtualPrivateCloudList defines model for VirtualPrivateCloudList.
type VirtualPrivateCloudList struct {
	Items *[]VirtualPrivateCloud `json:"items,omitempty"`
}

// VirtualPrivateCloudRequest defines model for VirtualPrivateCloudRequest.
type VirtualPrivateCloudRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`
	Spec     VirtualPrivateCloudSpec `json:"spec"`
}

// VirtualPrivateCloudSpec defines model for VirtualPrivateCloudSpec.
type VirtualPrivateCloudSpec struct {
	// Ipv4CidrBlocks The IPv4 CIDR Blocks to assign to this VPC.  Each of these blocks must be contained must be contained
	// within one of the three RFC 1918 private IP address ranges: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16.
	// Defaults to ["10.0.0.0/16"] if not set.
	Ipv4CidrBlocks *[]string `json:"ipv4CidrBlocks,omitempty"`

	// StackType The stack type of this VPC.  Can either be "dual-stack", meaning that both IPv4 and IPv6
	// addresses are provisioned, or "ipv6-only".  Defaults to dual-stack behaviour if not set.
	StackType *VirtualPrivateCloudSpecStackType `json:"stackType,omitempty"`
}

// VirtualPrivateCloudSpecStackType The stack type of this VPC.  Can either be "dual-stack", meaning that both IPv4 and IPv6
// addresses are provisioned, or "ipv6-only".  Defaults to dual-stack behaviour if not set.
type VirtualPrivateCloudSpecStackType string

// VirtualPrivateCloudStatus defines model for VirtualPrivateCloudStatus.
type VirtualPrivateCloudStatus struct {
	// AssignedIPv4CidrBlocks The IPv4 CIDR Blocks that are assigned to this VPC.
	AssignedIPv4CidrBlocks *[]string `json:"assignedIPv4CidrBlocks,omitempty"`

	// AssignedIPv6GUABlock The range of publicly routable IPv6 addresses assigned to this VPC.
	AssignedIPv6GUABlock *string `json:"assignedIPv6GUABlock,omitempty"`

	// AvailableIPv4CidrBlocks The CIDRs that are available for use (not allocated) on this VPC.
	AvailableIPv4CidrBlocks *[]string `json:"availableIPv4CidrBlocks,omitempty"`

	// Conditions The state of the Virtual Private Cloud over time.
	// Each condition follows the Kubernetes API conventions for a condition:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
	Conditions *[]VirtualPrivateCloudStatusConditionsItem `json:"conditions,omitempty"`

	// StackType The stack type of this VPC.
	StackType *string `json:"stackType,omitempty"`

	// Subnets The current status of Subnet CIDRs in this VPC.
	Subnets *VirtualPrivateCloudStatusSubnets `json:"subnets,omitempty"`
}

// VirtualPrivateCloudStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type VirtualPrivateCloudStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status VirtualPrivateCloudStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// VirtualPrivateCloudStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type VirtualPrivateCloudStatusConditionsItemStatus string

// VirtualPrivateCloudStatusSubnets The current status of Subnet CIDRs in this VPC.
type VirtualPrivateCloudStatusSubnets struct {
	// AllocatedSubnets Subnets in this VPC which are programmed and active.
	AllocatedSubnets *[]struct {
		// Ipv4CidrBlock IPv4 CIDR block associated with this Subnet.
		Ipv4CidrBlock *string `json:"ipv4CidrBlock,omitempty"`

		// Ipv6GUABlock IPv6 GUA CIDR block associated with this Subnet.
		Ipv6GUABlock *string `json:"ipv6GUABlock,omitempty"`

		// Placement The Placement of the Subnet.
		Placement *VirtualPrivateCloudStatusSubnetsPlacement `json:"placement,omitempty"`

		// SubnetRef The Subnet.
		SubnetRef *string `json:"subnetRef,omitempty"`
	} `json:"allocatedSubnets,omitempty"`

	// InvalidSubnets Subnets in this VPC which are invalid and unable to be programmed.
	InvalidSubnets *[]struct {
		// Ipv4CidrBlock IPv4 CIDR block associated with this Subnet.
		Ipv4CidrBlock *string `json:"ipv4CidrBlock,omitempty"`

		// Ipv6GUABlock IPv6 GUA CIDR block associated with this Subnet.
		Ipv6GUABlock *string `json:"ipv6GUABlock,omitempty"`

		// Placement The Placement of the Subnet.
		Placement *VirtualPrivateCloudStatusSubnetsPlacement `json:"placement,omitempty"`

		// SubnetRef The Subnet.
		SubnetRef *string `json:"subnetRef,omitempty"`
	} `json:"invalidSubnets,omitempty"`
}

// VirtualPrivateCloudStatusSubnetsPlacement The Placement of the Subnet.
type VirtualPrivateCloudStatusSubnetsPlacement struct {
	// Zone The zone this Subnet should be deployed to.
	Zone *string `json:"zone,omitempty"`
}

// ApiVersion Identifies the version of the API schema used for this resource.
// It should be the same than the version in the path, otherwise the request will be rejected.
type ApiVersion = string

// Kind Specifies the type of resource this object represents.
type Kind = string

// GetNetworkingV1beta2ProjectsProjectIDRegionsRegionNamePublicIPsParams defines parameters for GetNetworkingV1beta2ProjectsProjectIDRegionsRegionNamePublicIPs.
type GetNetworkingV1beta2ProjectsProjectIDRegionsRegionNamePublicIPsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSecurityGroupsParams defines parameters for GetNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSecurityGroups.
type GetNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSecurityGroupsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSubnetsParams defines parameters for GetNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSubnets.
type GetNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSubnetsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetNetworkingV1beta2ProjectsProjectIDRegionsRegionNameVirtualPrivateCloudsParams defines parameters for GetNetworkingV1beta2ProjectsProjectIDRegionsRegionNameVirtualPrivateClouds.
type GetNetworkingV1beta2ProjectsProjectIDRegionsRegionNameVirtualPrivateCloudsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// PostNetworkingV1beta2ProjectsProjectIDRegionsRegionNamePublicIPsJSONRequestBody defines body for PostNetworkingV1beta2ProjectsProjectIDRegionsRegionNamePublicIPs for application/json ContentType.
type PostNetworkingV1beta2ProjectsProjectIDRegionsRegionNamePublicIPsJSONRequestBody = PublicIPRequest

// PatchNetworkingV1beta2ProjectsProjectIDRegionsRegionNamePublicIPsPublicIPIDJSONRequestBody defines body for PatchNetworkingV1beta2ProjectsProjectIDRegionsRegionNamePublicIPsPublicIPID for application/json ContentType.
type PatchNetworkingV1beta2ProjectsProjectIDRegionsRegionNamePublicIPsPublicIPIDJSONRequestBody = PublicIPRequest

// PostNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSecurityGroupsJSONRequestBody defines body for PostNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSecurityGroups for application/json ContentType.
type PostNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSecurityGroupsJSONRequestBody = SecurityGroupRequest

// PatchNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSecurityGroupsSecurityGroupIDJSONRequestBody defines body for PatchNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSecurityGroupsSecurityGroupID for application/json ContentType.
type PatchNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSecurityGroupsSecurityGroupIDJSONRequestBody = SecurityGroupRequest

// PostNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSubnetsJSONRequestBody defines body for PostNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSubnets for application/json ContentType.
type PostNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSubnetsJSONRequestBody = SubnetRequest

// PatchNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSubnetsSubnetIDJSONRequestBody defines body for PatchNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSubnetsSubnetID for application/json ContentType.
type PatchNetworkingV1beta2ProjectsProjectIDRegionsRegionNameSubnetsSubnetIDJSONRequestBody = SubnetRequest

// PostNetworkingV1beta2ProjectsProjectIDRegionsRegionNameVirtualPrivateCloudsJSONRequestBody defines body for PostNetworkingV1beta2ProjectsProjectIDRegionsRegionNameVirtualPrivateClouds for application/json ContentType.
type PostNetworkingV1beta2ProjectsProjectIDRegionsRegionNameVirtualPrivateCloudsJSONRequestBody = VirtualPrivateCloudRequest

// PatchNetworkingV1beta2ProjectsProjectIDRegionsRegionNameVirtualPrivateCloudsVirtualPrivateCloudIDJSONRequestBody defines body for PatchNetworkingV1beta2ProjectsProjectIDRegionsRegionNameVirtualPrivateCloudsVirtualPrivateCloudID for application/json ContentType.
type PatchNetworkingV1beta2ProjectsProjectIDRegionsRegionNameVirtualPrivateCloudsVirtualPrivateCloudIDJSONRequestBody = VirtualPrivateCloudRequest
