// Package networking provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package networking

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for PublicIPStatusConditionsItemStatus.
const (
	PublicIPStatusConditionsItemStatusFalse   PublicIPStatusConditionsItemStatus = "False"
	PublicIPStatusConditionsItemStatusTrue    PublicIPStatusConditionsItemStatus = "True"
	PublicIPStatusConditionsItemStatusUnknown PublicIPStatusConditionsItemStatus = "Unknown"
)

// Defines values for SecurityGroupSpecRulesItemDirection.
const (
	Egress  SecurityGroupSpecRulesItemDirection = "Egress"
	Ingress SecurityGroupSpecRulesItemDirection = "Ingress"
)

// Defines values for SecurityGroupSpecRulesItemProtocol.
const (
	All  SecurityGroupSpecRulesItemProtocol = "All"
	ICMP SecurityGroupSpecRulesItemProtocol = "ICMP"
	TCP  SecurityGroupSpecRulesItemProtocol = "TCP"
	UDP  SecurityGroupSpecRulesItemProtocol = "UDP"
)

// Defines values for SecurityGroupStatusConditionsItemStatus.
const (
	SecurityGroupStatusConditionsItemStatusFalse   SecurityGroupStatusConditionsItemStatus = "False"
	SecurityGroupStatusConditionsItemStatusTrue    SecurityGroupStatusConditionsItemStatus = "True"
	SecurityGroupStatusConditionsItemStatusUnknown SecurityGroupStatusConditionsItemStatus = "Unknown"
)

// Defines values for SecurityGroupStatusMembersItemStatus.
const (
	Active  SecurityGroupStatusMembersItemStatus = "Active"
	Pending SecurityGroupStatusMembersItemStatus = "Pending"
)

// Defines values for SubnetStatusConditionsItemStatus.
const (
	SubnetStatusConditionsItemStatusFalse   SubnetStatusConditionsItemStatus = "False"
	SubnetStatusConditionsItemStatusTrue    SubnetStatusConditionsItemStatus = "True"
	SubnetStatusConditionsItemStatusUnknown SubnetStatusConditionsItemStatus = "Unknown"
)

// Defines values for VirtualPrivateCloudStatusConditionsItemStatus.
const (
	VirtualPrivateCloudStatusConditionsItemStatusFalse   VirtualPrivateCloudStatusConditionsItemStatus = "False"
	VirtualPrivateCloudStatusConditionsItemStatusTrue    VirtualPrivateCloudStatusConditionsItemStatus = "True"
	VirtualPrivateCloudStatusConditionsItemStatusUnknown VirtualPrivateCloudStatusConditionsItemStatus = "Unknown"
)

// BaseMetadataResponse Common metadata fields for all resource responses.
type BaseMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`
}

// Error Standard error response sent by all endpoints on failure.
type Error struct {
	// Debug Additional human-readable diagnostic information in English. This content is safe to surface to end users. MUST NOT be used for programmatic logic. The content may evolve at any time and is not stable.
	Debug *string `json:"debug,omitempty"`

	// Reason Stable, textual error code. This MUST be used by clients for programmatic handling. Examples include: FieldValueInvalid, Unauthorized, Forbidden.
	Reason string `json:"reason"`
}

// GlobalMetadataRequest Standard metadata for global resources.
type GlobalMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id *string `json:"id,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// PublicIP defines model for PublicIP.
type PublicIP struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	// For example: "VirtualMachine", or "Bucket".
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     PublicIPSpec             `json:"spec"`
	Status   PublicIPStatus           `json:"status"`
}

// PublicIPList defines model for PublicIPList.
type PublicIPList struct {
	Items *[]PublicIP `json:"items,omitempty"`
}

// PublicIPRequest defines model for PublicIPRequest.
type PublicIPRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	// For example: "VirtualMachine", or "Bucket".
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`
	Spec     PublicIPSpec            `json:"spec"`
}

// PublicIPSpec defines model for PublicIPSpec.
type PublicIPSpec = map[string]interface{}

// PublicIPStatus defines model for PublicIPStatus.
type PublicIPStatus struct {
	// Conditions The state of the PublicIP over time.
	// Each condition follows the Kubernetes API conventions for a condition:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
	Conditions *[]PublicIPStatusConditionsItem `json:"conditions,omitempty"`

	// PublicIPv4Address The IPv4 address that has been reserved.
	PublicIPv4Address *string `json:"publicIPv4Address,omitempty"`

	// UsedByRef The object that is currently using this PublicIP object.
	// If a there is an attempt to delete a PublicIP object while it is in use, the deletion will be blocked until the
	// user no longer needs the PublicIP (either because it has been deleted, or has been reconfigured to no longer
	// need the PublicIP).
	UsedByRef *string `json:"usedByRef,omitempty"`
}

// PublicIPStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type PublicIPStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status PublicIPStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// PublicIPStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type PublicIPStatusConditionsItemStatus string

// RegionalMetadataRequest defines model for RegionalMetadataRequest.
type RegionalMetadataRequest struct {
	// Id Unique identifier for the resource within its namespace. Immutable.
	Id *string `json:"id,omitempty"`

	// Project Project identifier
	Project *string `json:"project,omitempty"`

	// Region Region identifier
	Region *string `json:"region,omitempty"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// RegionalMetadataResponse defines model for RegionalMetadataResponse.
type RegionalMetadataResponse struct {
	// CreationTimestamp Timestamp representing when the resource was created. Set by the system and immutable.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Sequential number representing the desired state of the resource. Incremented by the system whenever the spec is updated by a client. Mirrors Kubernetes’ `metadata.generation`.
	Generation int64 `json:"generation"`

	// Id Unique identifier for the resource within its namespace. Immutable.
	Id *string `json:"id,omitempty"`

	// Project Project identifier
	Project *string `json:"project,omitempty"`

	// Region Region identifier
	Region *string `json:"region,omitempty"`

	// SystemLabels Map of string keys and string values owned and managed by evroc, and automatically set by the system. SystemLabels are read-only and can be referenced by label selectors.
	SystemLabels *SystemLabels `json:"systemLabels,omitempty"`

	// Uid System-assigned unique identifier for the resource. Immutable.
	Uid openapi_types.UUID `json:"uid"`

	// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
	UserLabels *UserLabels `json:"userLabels,omitempty"`
}

// SecurityGroup defines model for SecurityGroup.
type SecurityGroup struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	// For example: "VirtualMachine", or "Bucket".
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     SecurityGroupSpec        `json:"spec"`
	Status   SecurityGroupStatus      `json:"status"`
}

// SecurityGroupList defines model for SecurityGroupList.
type SecurityGroupList struct {
	Items *[]SecurityGroup `json:"items,omitempty"`
}

// SecurityGroupRequest defines model for SecurityGroupRequest.
type SecurityGroupRequest struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	// For example: "VirtualMachine", or "Bucket".
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataRequest `json:"metadata"`
	Spec     SecurityGroupSpec       `json:"spec"`
}

// SecurityGroupSpec defines model for SecurityGroupSpec.
type SecurityGroupSpec struct {
	// Rules The rules for this security group.
	Rules *[]SecurityGroupSpecRulesItem `json:"rules,omitempty"`
}

// SecurityGroupSpecRulesItem defines model for SecurityGroupSpecRulesItem.
type SecurityGroupSpecRulesItem struct {
	// Direction The direction of traffic the rule applies to. Can be 'Ingress' or 'Egress'.
	Direction SecurityGroupSpecRulesItemDirection `json:"direction"`

	// EndPort If specified, means that the rule applies to all ports from port to endPort. Empty or '0' indicates that only
	// port is opened (if port is specified) or all ports are opened (if port is not specified).
	EndPort *int32 `json:"endPort,omitempty"`

	// Name The name of the rule. Optional. Must be unique per security group.
	Name *string `json:"name,omitempty"`

	// Port The port the rule applies to. Empty or '0' indicates all ports.  Can only be set if the Protocol is TCP or UDP.
	Port *int32 `json:"port,omitempty"`

	// Protocol The protocol the rule applies to. Can be 'TCP', 'UDP', 'ICMP' or 'All'. Empty indicates all protocols.
	Protocol *SecurityGroupSpecRulesItemProtocol `json:"protocol,omitempty"`

	// Remote The source (for ingress) or destination (for egress) that the rule applies to.
	Remote struct {
		// Address The IP address or CIDR that traffic is allowed to/from.
		Address *SecurityGroupSpecRulesItemAddress `json:"address,omitempty"`

		// SecurityGroupRef The security group that traffic is allowed to/from.
		SecurityGroupRef *string `json:"securityGroupRef,omitempty"`

		// SubnetRef The subnet that traffic is allowed to/from.
		SubnetRef *string `json:"subnetRef,omitempty"`
	} `json:"remote"`
}

// SecurityGroupSpecRulesItemDirection The direction of traffic the rule applies to. Can be 'Ingress' or 'Egress'.
type SecurityGroupSpecRulesItemDirection string

// SecurityGroupSpecRulesItemProtocol The protocol the rule applies to. Can be 'TCP', 'UDP', 'ICMP' or 'All'. Empty indicates all protocols.
type SecurityGroupSpecRulesItemProtocol string

// SecurityGroupSpecRulesItemAddress The IP address or CIDR that traffic is allowed to/from.
type SecurityGroupSpecRulesItemAddress struct {
	// IpAddressOrCIDR The IP address or CIDR that traffic is allowed to/from. Can be any IPv4 address with any valid mask.
	IpAddressOrCIDR string `json:"ipAddressOrCIDR"`
}

// SecurityGroupStatus defines model for SecurityGroupStatus.
type SecurityGroupStatus struct {
	// Conditions ConditionsSet is an abstraction over []metav1.Condition that handles the
	// removal of the previous occurrence of the conditionType when marking a condition.
	Conditions *[]SecurityGroupStatusConditionsItem `json:"conditions,omitempty"`
	Members    *[]SecurityGroupStatusMembersItem    `json:"members,omitempty"`
}

// SecurityGroupStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type SecurityGroupStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status SecurityGroupStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// SecurityGroupStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type SecurityGroupStatusConditionsItemStatus string

// SecurityGroupStatusMembersItem defines model for SecurityGroupStatusMembersItem.
type SecurityGroupStatusMembersItem struct {
	SecurityGroupMemberRef string                               `json:"securityGroupMemberRef"`
	Status                 SecurityGroupStatusMembersItemStatus `json:"status"`
}

// SecurityGroupStatusMembersItemStatus defines model for SecurityGroupStatusMembersItem.Status.
type SecurityGroupStatusMembersItemStatus string

// Subnet defines model for Subnet.
type Subnet struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	// For example: "VirtualMachine", or "Bucket".
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataResponse `json:"metadata"`
	Spec     SubnetSpec               `json:"spec"`
	Status   SubnetStatus             `json:"status"`
}

// SubnetList defines model for SubnetList.
type SubnetList struct {
	Items *[]Subnet `json:"items,omitempty"`
}

// SubnetSpec defines model for SubnetSpec.
type SubnetSpec struct {
	// Ipv4CidrBlock An IPv4 CIDR block.
	Ipv4CidrBlock string `json:"ipv4CidrBlock"`

	// Placement Placement defines the placement requirements for this Subnet.
	Placement SubnetSpecPlacement `json:"placement"`
	VpcRef    string              `json:"vpcRef"`
}

// SubnetSpecPlacement Placement defines the placement requirements for this Subnet.
type SubnetSpecPlacement struct {
	// Zone The zone this Subnet should be deployed to.
	Zone *string `json:"zone,omitempty"`
}

// SubnetStatus defines model for SubnetStatus.
type SubnetStatus struct {
	// AvailableIPv4AddressCount availableIPv4AddressCount is a count of the number of IPv4 addresses not yet assigned in this subnet.
	AvailableIPv4AddressCount *int `json:"availableIPv4AddressCount,omitempty"`

	// AvailableIPv4Ranges availableIPv4Ranges is a list of either single IPs (e.g. "10.0.0.2") or IP ranges ("10.0.0.4-10.0.0.7") of IPv4
	// addresses currently not in use in this subnet.
	AvailableIPv4Ranges *[]string `json:"availableIPv4Ranges,omitempty"`

	// Conditions The state of the Subnet over time.
	// Each condition follows the Kubernetes API conventions for a condition:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
	Conditions *[]SubnetStatusConditionsItem `json:"conditions,omitempty"`

	// Placement Placement defines the placement requirements for this Subnet.
	Placement *SubnetStatusPlacement `json:"placement,omitempty"`

	// UsingIPv4AddressCount usingIPv4AddressCount is a count of the number of IPv4 addresses currently in use in this subnet. Deletion of
	// this subnet will be blocked if there are IPs in the subnet in use. Those resources need to be deleted first.
	UsingIPv4AddressCount *int `json:"usingIPv4AddressCount,omitempty"`

	// UsingIPv4Ranges usingIPv4Ranges is a list of either single IPs (e.g. "10.0.0.2") or IP ranges ("10.0.0.4-10.0.0.7") of IPv4
	// addresses currently in use  in this subnet.
	UsingIPv4Ranges *[]string `json:"usingIPv4Ranges,omitempty"`
}

// SubnetStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type SubnetStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status SubnetStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// SubnetStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type SubnetStatusConditionsItemStatus string

// SubnetStatusPlacement Placement defines the placement requirements for this Subnet.
type SubnetStatusPlacement struct {
	// Zone The zone this Subnet should be deployed to.
	Zone *string `json:"zone,omitempty"`
}

// SystemLabels Map of string keys and string values owned and managed by evroc, and automatically set by the system. SystemLabels are read-only and can be referenced by label selectors.
type SystemLabels map[string]string

// UserLabels Map of string keys and string values used to organize and select resources. UserLabels are fully managed by the user and can be referenced by label selectors.
type UserLabels map[string]string

// VirtualPrivateCloud defines model for VirtualPrivateCloud.
type VirtualPrivateCloud struct {
	// ApiVersion Identifies the version of the API schema used for this resource.
	// It should be the same than the version in the path, otherwise the request will be rejected.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Specifies the type of resource this object represents.
	// For example: "VirtualMachine", or "Bucket".
	Kind Kind `json:"kind"`

	// Metadata Standard metadata for region-scoped resource
	Metadata RegionalMetadataResponse  `json:"metadata"`
	Spec     VirtualPrivateCloudSpec   `json:"spec"`
	Status   VirtualPrivateCloudStatus `json:"status"`
}

// VirtualPrivateCloudList defines model for VirtualPrivateCloudList.
type VirtualPrivateCloudList struct {
	Items *[]VirtualPrivateCloud `json:"items,omitempty"`
}

// VirtualPrivateCloudSpec defines model for VirtualPrivateCloudSpec.
type VirtualPrivateCloudSpec = map[string]interface{}

// VirtualPrivateCloudStatus defines model for VirtualPrivateCloudStatus.
type VirtualPrivateCloudStatus struct {
	// Conditions The state of the Virtual Private Cloud over time.
	// Each condition follows the Kubernetes API conventions for a condition:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
	Conditions *[]VirtualPrivateCloudStatusConditionsItem `json:"conditions,omitempty"`
}

// VirtualPrivateCloudStatusConditionsItem Condition contains details for one aspect of the current state of this API Resource.
type VirtualPrivateCloudStatusConditionsItem struct {
	// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
	// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message message is a human readable message indicating details about the transition.
	// This may be an empty string.
	Message string `json:"message"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
	// Producers of specific condition types may define expected values and meanings for this field,
	// and whether the values are considered a guaranteed API.
	// The value should be a CamelCase string.
	// This field may not be empty.
	Reason string `json:"reason"`

	// Status status of the condition, one of True, False, Unknown.
	Status VirtualPrivateCloudStatusConditionsItemStatus `json:"status"`

	// Type type of condition in CamelCase or in foo.example.com/CamelCase.
	Type string `json:"type"`
}

// VirtualPrivateCloudStatusConditionsItemStatus status of the condition, one of True, False, Unknown.
type VirtualPrivateCloudStatusConditionsItemStatus string

// ApiVersion Identifies the version of the API schema used for this resource.
// It should be the same than the version in the path, otherwise the request will be rejected.
type ApiVersion = string

// Kind Specifies the type of resource this object represents.
// For example: "VirtualMachine", or "Bucket".
type Kind = string

// GetNetworkingV1beta1ProjectsProjectIDRegionsRegionNamePublicIPsParams defines parameters for GetNetworkingV1beta1ProjectsProjectIDRegionsRegionNamePublicIPs.
type GetNetworkingV1beta1ProjectsProjectIDRegionsRegionNamePublicIPsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetNetworkingV1beta1ProjectsProjectIDRegionsRegionNameSecurityGroupsParams defines parameters for GetNetworkingV1beta1ProjectsProjectIDRegionsRegionNameSecurityGroups.
type GetNetworkingV1beta1ProjectsProjectIDRegionsRegionNameSecurityGroupsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetNetworkingV1beta1ProjectsProjectIDRegionsRegionNameSubnetsParams defines parameters for GetNetworkingV1beta1ProjectsProjectIDRegionsRegionNameSubnets.
type GetNetworkingV1beta1ProjectsProjectIDRegionsRegionNameSubnetsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetNetworkingV1beta1ProjectsProjectIDRegionsRegionNameVirtualPrivateCloudsParams defines parameters for GetNetworkingV1beta1ProjectsProjectIDRegionsRegionNameVirtualPrivateClouds.
type GetNetworkingV1beta1ProjectsProjectIDRegionsRegionNameVirtualPrivateCloudsParams struct {
	// LabelSelector Optional label selector to select resources using Kubernetes-style selector syntax. This can be used with label keys from userLabels and systemLabels, using the prefixed syntax (e.g. "team in (frontend,backend)", "networking.evroc.com/managed-network=default").
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// PostNetworkingV1beta1ProjectsProjectIDRegionsRegionNamePublicIPsJSONRequestBody defines body for PostNetworkingV1beta1ProjectsProjectIDRegionsRegionNamePublicIPs for application/json ContentType.
type PostNetworkingV1beta1ProjectsProjectIDRegionsRegionNamePublicIPsJSONRequestBody = PublicIPRequest

// PatchNetworkingV1beta1ProjectsProjectIDRegionsRegionNamePublicIPsPublicIPIDJSONRequestBody defines body for PatchNetworkingV1beta1ProjectsProjectIDRegionsRegionNamePublicIPsPublicIPID for application/json ContentType.
type PatchNetworkingV1beta1ProjectsProjectIDRegionsRegionNamePublicIPsPublicIPIDJSONRequestBody = PublicIPRequest

// PutNetworkingV1beta1ProjectsProjectIDRegionsRegionNamePublicIPsPublicIPIDJSONRequestBody defines body for PutNetworkingV1beta1ProjectsProjectIDRegionsRegionNamePublicIPsPublicIPID for application/json ContentType.
type PutNetworkingV1beta1ProjectsProjectIDRegionsRegionNamePublicIPsPublicIPIDJSONRequestBody = PublicIPRequest

// PostNetworkingV1beta1ProjectsProjectIDRegionsRegionNameSecurityGroupsJSONRequestBody defines body for PostNetworkingV1beta1ProjectsProjectIDRegionsRegionNameSecurityGroups for application/json ContentType.
type PostNetworkingV1beta1ProjectsProjectIDRegionsRegionNameSecurityGroupsJSONRequestBody = SecurityGroupRequest

// PatchNetworkingV1beta1ProjectsProjectIDRegionsRegionNameSecurityGroupsSecurityGroupIDJSONRequestBody defines body for PatchNetworkingV1beta1ProjectsProjectIDRegionsRegionNameSecurityGroupsSecurityGroupID for application/json ContentType.
type PatchNetworkingV1beta1ProjectsProjectIDRegionsRegionNameSecurityGroupsSecurityGroupIDJSONRequestBody = SecurityGroupRequest

// PutNetworkingV1beta1ProjectsProjectIDRegionsRegionNameSecurityGroupsSecurityGroupIDJSONRequestBody defines body for PutNetworkingV1beta1ProjectsProjectIDRegionsRegionNameSecurityGroupsSecurityGroupID for application/json ContentType.
type PutNetworkingV1beta1ProjectsProjectIDRegionsRegionNameSecurityGroupsSecurityGroupIDJSONRequestBody = SecurityGroupRequest
